### ISSUE TITLE
Question: Send to php script

### ISSUE THREAD

**Issue by krzyszaf** [scaleflex/filerobot-image-editor#10]
Please tell me how can I send edited image into a php script, I was trying on few times and I don't have any idea, I can only download it. Thanks for your response.

**Comment by dzmitry-stramavus** [comment]
hey @krzyszaf , check [here](https://github.com/scaleflex/filerobot-image-editor/issues/6). It's similar question

**Comment by krzyszaf** [comment]
Thanks, can you tell me how I need to send it? I was trying in JS but it doesn't work. I think that this example code is in NodeJS and I don't know hot to write it in JavaScript.

**Comment by Klaas-V** [comment]
Hi @krzyszaf , I wrote a small example

```javascript
    const config = {
        tools:["crop", "resize", "adjust", "effects", "filters", "rotate"]
    };

    const onComplete = function(newUrl) {
        //
    };

    const onBeforeComplete = function(props) {
        console.log(props);
        console.log(props.canvas.toDataURL());
        return false;
    };

   const ImageEditor = new window.FilerobotImageEditor(config,
       {
        onComplete: onComplete,
        onBeforeComplete: onBeforeComplete
        }
    );

    ImageEditor.open(
        "https://scaleflex.airstore.io/demo/stephen-walker-unsplash.jpg"
    );
```

**Comment by krzyszaf** [comment]
Thanks @Klaas-V for your code. I change it a little bit and it works perfect. Now I understand how to work with it.

**Comment by TukuToi** [comment]
I do not understand how this works.

I use the CDN bundle, and successfully implemented the editor.
Now, on save, I want to save the file to the PHP folder.

The function mentioned above (`onBeforeComplete`) is not documented, all I can find is [`onBeforeSave`](https://github.com/scaleflex/filerobot-image-editor#onbeforesave).
I tried above example script, but that does not implement editor on my end, it breaks it.

Is this perhaps a meanwhile outdated approach?
What would be the correct approach with latest Bundle to save the edited file on server, using PHP?

Thank you for any hints :)

The tool is very cool so far!

**Comment by AhmeeedMostafa** [comment]
@TukuToi this issue was related to ex version, now we have v4 as the major version,
You could check its docs and you'll find it easy to send the file to backend check `onSave` callback method

**Comment by TukuToi** [comment]
Ok, that's what I suspected. Got it working in `onSave`, thanks!

Found a puzzling behaviour with the latter, opened another issue for that.

Thanks!

**Comment by omarshamali** [comment]
ImageEditor.open is not a function
