### ISSUE TITLE
Line drawing feature?

### ISSUE THREAD

**Issue by nikto1** [scaleflex/filerobot-image-editor#100]
Possible to add a line drawing feature?

**Comment by AhmeeedMostafa** [comment]
Yes it is considered in the future line & free drawing feature

**Comment by prakis** [comment]
Will you consider a PR if I implement drawing tool? Do you have any specific requirements/plans in implementing drawing feature?

**Comment by nikto1** [comment]
Sorry, too much time has passed, i don't remember what was the issue.
Thanks anyway.

**Comment by AhmeeedMostafa** [comment]
@prakis @nikto1 such a feature is done in the new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) that is released in BETA now  it would be nice to give it a try, thanks
