### ISSUE TITLE
Fullscreen documentation + mobile pinch zoom

### ISSUE THREAD

**Issue by vincentcox** [scaleflex/filerobot-image-editor#101]
Hi there,

What configuration option should I use to let it view the editor fullscreen?

I think this will help on mobile to properly zoom in with pinch.

Thanks in advance!

EDIT: This is what I mean with zooming on mobile not being properly:

https://user-images.githubusercontent.com/9286611/105233656-7014bb80-5b6a-11eb-8fe9-070982baed80.mp4

**Comment by AhmeeedMostafa** [comment]
Hey @vincentcox , Sorry for late reply what u r asking about is related to touch support & we haven't the touch supported fully yet, it's expected to be in the future releases but no ETA for it yet.

**Comment by vincentcox** [comment]
Hi @AhmeeedMostafa, thanks for your reaction. Is it expected to be implemented in the upcoming months or is it really at the end of the priority list? (It's just for a decision I have to make if I want to implement this in my application or not). If I get your reply, I'll close this issue so it doesn't linker around. Thanks again!

**Comment by AhmeeedMostafa** [comment]
@vincentcox Unfortunately, it is not very soon yet as no specific date is determined for it cuz we are considering it in the next major update that would contain a lot of improvements & differences as we hope

**Comment by vincentcox** [comment]
Ok no worries! Thanks for the honest reply and good luck! I'll close the issue.
