### ISSUE TITLE
The popup is getting distorted after CROP operation

### ISSUE THREAD

**Issue by ravisingh10** [scaleflex/filerobot-image-editor#102]
Steps to reproduce:

Select an image
Go to corp
Select any shape/aspect ration
Crop Image
Click Apply

I am attaching an image for the same:

![image](https://user-images.githubusercontent.com/25878409/105633573-58497a00-5e7f-11eb-92ce-7c618af6e604.png)

The Browser user: Google Chrome Version 88.0.4324.96 (Official Build) (64-bit)
OS: Pop!_OS 20.04 LTS
using latest version with react 17.0.1

**Comment by AhmeeedMostafa** [comment]
@ravisingh10 could u please check, it should be solved since v3.12.13?

**Comment by AhmeeedMostafa** [comment]
closed for non-activity.
