### ISSUE TITLE
I want to contribe for enahancing watermarking feature.

### ISSUE THREAD

**Issue by prakis** [scaleflex/filerobot-image-editor#103]
Hi there,

Thanks for wonderful filerobot image editor. I am planning to use it in my project. For my requirment I need to provide few enhancments for watermarking. ex:- instead of dropdown to select a watermark, provide a dialog with preview for watermarking.. etc.

I like to know if anyone else doing something similar so we can contribute. If there are any particular guidelines the main devs like us to follow I am happy to hear that.

Regards,
Kishore

**Comment by AhmeeedMostafa** [comment]
Hello @prakis , sorry for the late reply.
currently, we are working on a new major version so better to wait for it if it doesn't meet your use-case and need to provide some PR we are welcoming that.

**Comment by AhmeeedMostafa** [comment]
Hey @prakis u could check the v4 beta from [here](https://github.com/scaleflex/filerobot-image-editor/tree/v4)  if u still see you need some improvement related to watermark you are welcome to contribute to the new version
