### ISSUE TITLE
A way to return the edited image instead of downloading it

### ISSUE THREAD

**Issue by fluorspar20** [scaleflex/filerobot-image-editor#104]
I'm actually working on something which requires me to display the edited image directly on the screen instead of downloading it. Is there a way to do this?

**Comment by Lesruez93** [comment]
Same here

**Comment by kfarr** [comment]
This might help https://github.com/scaleflex/filerobot-image-editor/issues/6

**Comment by AhmeeedMostafa** [comment]
Closing this issue as @kfarr (thanks) referred to the right solution.
