### ISSUE TITLE
Problem saving images using onBeforeComplete with heights greater than 800px

### ISSUE THREAD

**Issue by meesterguyman** [scaleflex/filerobot-image-editor#105]
https://github.com/scaleflex/filerobot-image-editor/blob/307b00c309ac765ded1eca429eceb6fc68822e60/src/components/Preview/ImageManipulator.js#L169

The editor has two canvases:
1. filerobot-image-editor_filerobot-image-edit-box-original
2. filerobot-image-editor_filerobot-image-edit-box 

The original always has the correct dimensions. The latter is limited to a max of 800px. This results in a limitation for images uploaded to a third-party service via the onBeforeComplete listener, since this canvas will never be anything more than 800px. For smaller images, this doesn't matter. But a 3648x2736 image, for example, will load as a 1066x800 image in the edit canvas, and no matter how it has been resized, this will be the size sent up.

The reason for this issue is the resize method here which limits the size of the edit canvas to 800px high (see a few lines up). By simply removing this call, the edit canvas gets the correct dimensions, and these dimensions are accessible to the onBeforeComplete listener for third-party upload.

**Comment by AhmeeedMostafa** [comment]
Hey @meesterguyman , sorry for the late reply,
we should resize the image to fit the available width and height of the browser's window unless that it would be hard to edit, but at the end, we should consider mapping back to the original size.
currently, we are working on a new major version and we would make sure we don't have such behaviour, so if know what's the issue & solution for that current version we are welcome to your PR with the solution :)

**Comment by AhmeeedMostafa** [comment]
@meesterguyman new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) is released in BETA now it would be nice if you want to check your issue and let us know the feedback
