### ISSUE TITLE
invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by MasterMarandu** [scaleflex/filerobot-image-editor#107]

**Comment by HarishReddyCH** [comment]
Same issue, any solution ?

**Comment by AhmeeedMostafa** [comment]
Hello, sorry for late reply.
@MasterMarandu @HarishReddyCH could u please clarify more the error with some screenshot and when does this happen?
please note we are working on a new major version that would have additional features and might wouldn't have such a bug but we need to know the error generating steps to make sure we avoid it in the new release.

**Comment by imdkbj** [comment]
I am also facing the same issue with the next js

![image](https://user-images.githubusercontent.com/46839821/126878103-e8a1f6a4-0995-4eae-8e29-a5108549295c.png)

**Comment by AhmeeedMostafa** [comment]
@imdkbj  are u having the same react & react-dom  versions?

**Comment by imdkbj** [comment]
Ya! I am able to fix this by following workaround

I found that react version in package.json and react inside the filerobot are different, So added same version in both and then did following changes.

https://github.com/facebook/react/issues/13991#issuecomment-870536281

https://github.com/scaleflex/filerobot-image-editor/issues/32#issuecomment-825788823

**Comment by AhmeeedMostafa** [comment]
@imdkbj  yup, we would consider using react as peer dependency from the new release which would be better for react versions lower than v17,
thanks for sharing your solution,
closing the issue as it's solved
