### ISSUE TITLE
React crop issues with React.StrictMode 

### ISSUE THREAD

**Issue by dreadsfun** [scaleflex/filerobot-image-editor#108]
Hello

Found some issues with the crop tool when React.StrictMode is enabled for the Editor component.
See this sandbox: [Crop issue](https://codesandbox.io/s/angry-blackwell-4gpsy)
I've set up versions as I currently have them in my project, not sure how it works with other versions

- Selecting a crop preset does not change or enforce the aspect ratio of the actual selection
- Applying the selected crop makes the resulting image to disappear/shift from view

Other tools seem to be not affected by strict mode

**Comment by AhmeeedMostafa** [comment]
Hey @dreadsfun , sorry for the late reply...
We are working on a new major version that would contain more features and would avoid having such an issue in that new release.

**Comment by javashaman** [comment]
We are seeing this issue as well. Excited for the update!

**Comment by AhmeeedMostafa** [comment]
@dreadsfun @javashaman please consider checking new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) it's in BETA now it should have the fix for this issue, let us know your feedback
