### ISSUE TITLE
Stop closing the ImageEditor after download image while using "showInModal" as false

### ISSUE THREAD

**Issue by darshanabhuse1989** [scaleflex/filerobot-image-editor#109]
I am trying to render ImageEditor with configuration:
showInModal as false

Everything is working as expected except, "Download" button. When I click on the "Download" button, the updated image file gets downloaded but it seems, after downloading modal is getting closed so getting a blank screen.

Codesandbox Link: https://codesandbox.io/s/laughing-villani-zrk6v?file=/src/index.js

Expected Results should be:
When we have "showInModal" as false, after download, the editor should remain open.

**Comment by AhmeeedMostafa** [comment]
Hey @darshanabhuse1989 ,
sorry for the late reply, nice catch we would consider that behaviour in the next major version we are working on currently.
thanks

**Comment by oZeca** [comment]
this would be great to have!

**Comment by AhmeeedMostafa** [comment]
@oZeca it still in development, but no ETA yet

**Comment by AhmeeedMostafa** [comment]
@oZeca new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) is released in BETA now it would be nice if you want to check your issue and let us know the feedback, we have dismissed the modal at all and it's back to the developer to have it in modal or in page while implementing from the developer's side
