### ISSUE TITLE
Change the default aspect ratio for crop and additional button for custom operations

### ISSUE THREAD

**Issue by loveena27** [scaleflex/filerobot-image-editor#110]
Hi,

Firstly, a big thank you for creating such an amazing open-source Image Editor, scanned through a ton your's is perfectly bundled with all the essential features.. Keep up the amazing work!!

I am using the Vanilla JS version and looking at adding another button alongside the Download button, giving the option to either download or do something custom like upload to S3, Can you please let me know if that would be capable and how do I achieve it?

Secondly, in the crop feature, I was to make the current image aspect ratio to be set as default instead of the custom NaN that is currently there. It would be great if you can let me know how do I achieve it, please.

Thanks in advance!
Loveena.

**Comment by AhmeeedMostafa** [comment]
Hi @loveena27 ,
For first question, please check the callbacks `onBeforeComplete` & `onComplete` in addition to `finishButtonLabel` property in the [docs](https://github.com/scaleflex/filerobot-image-editor#filerobotimageeditorconfig--callbacks--function) you would achieve that (uploading to 3rd party provided) through those.

for the second question, it is not clear to me could u please clarify more?

**Comment by loveena27** [comment]
Thanks @AhmeeedMostafa  for your prompt reply.. appreciate it.

For my first question, I want to have both the options available to download and save, if I overwrite the onBeforeComplete the ability to download is lost, so is there a way I can have 2 buttons like Download and Save both asides each other?

For my second question, suppose if I have an image of width 600px and height 450px, by default I want to lock the aspectRatio to the image selected which in the example would be 4/3 = 1.33 instead of custom or NaN. I want to set the default aspectRatio based on the selected image and still giving the user the ability to change it if required. I hope I make sense in my question this time.

**Comment by AhmeeedMostafa** [comment]
@loveena27 , for first question u couldn't add additional button for now but maybe we consider that in the new major version we are working on currently, we would discuss about that and if it possible to support we would do...
But for now as a hacky solution, u could achieve that by adding some button from your side and positioning it besides the download button using css and JS and on clicking that button change the provided properties (onBeforeComplete and onComplete) to the plugin.

Second question, unfortunately it is not possible to lock the aspect ratio till now

**Comment by loveena27** [comment]
Thanks a ton, @AhmeeedMostafa for being so patient and replying to my questions time and again.  - I did try to hack and add the button but how I can get the Canvas data on my custom function, is there a way you can tell me how to get it for an external function? 

Also, I noticed something on the crop, when I click on toggleRatio button it keeps shrinking the croparea which doesn't happen on the editor demo on your site, I have the latest copy of the plugin from Github. Attached a GIf to show the issue, also regarding the aspect ratio I have the question clarified in the second image.
![CropQuestion](https://user-images.githubusercontent.com/4441827/121566633-53a2ee00-ca3b-11eb-822f-12d2f73205e2.png)

![cropareaShrink](https://user-images.githubusercontent.com/4441827/121566196-e4c59500-ca3a-11eb-95d2-12120dbb25e3.gif)

**Comment by AhmeeedMostafa** [comment]
@loveena27 please consider checking the new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) it's in BETA now, we have a new implementation of applying crop there, let us know ur feedback!
