### ISSUE TITLE
Rotate text on image at some angle 

### ISSUE THREAD

**Issue by sidjai09** [scaleflex/filerobot-image-editor#111]
![image](https://user-images.githubusercontent.com/46618565/121003872-a23a5900-c7ab-11eb-8e53-f60f5c5348c3.png)

**Comment by sidjai09** [comment]
Hello,

This is a wonderful plugin I need rotate feature for quick image generation.
Please give this feature in this project as soon as possible. 

Thanks in advance

**Comment by AhmeeedMostafa** [comment]
Hello @sidjai09 , we are working on a new major version that would contain this feature and other requested & needed feature, wait for it.

**Comment by sidjai09** [comment]
@AhmeeedMostafa 

Thanks for the quick reply.

can you give me detail on which node version this project runs properly and which branch contains the latest code to contribute to this project?

**Comment by sidjai09** [comment]
I have tried the master branch and v4-dev. 
but didn't get success to run this project.

**Comment by AhmeeedMostafa** [comment]
@sidjai09 , The master has the latest code for the current working version u should be able to run it normally.
The v4-dev contains the current development version of the new release (v4) it is not done yet so u won't be able to run it or it's hard to contribute to it as there is a lot changed time by time.

**Comment by AhmeeedMostafa** [comment]
@sidjai09 The [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) has been released in BETA , you could check it now , it contains your requested feature.
