### ISSUE TITLE
Would it be possible to get the image without downloading?

### ISSUE THREAD

**Issue by dclerici** [scaleflex/filerobot-image-editor#112]
I'm using the react integration. I need a new way to get the image from the editor. 

I don't need to download the file after edition. I only need to get the image in the onComplete event. Is there any way to do this?

I was looking a way to capture the result image in the onComplete event after edition and prevent downloading the file. 

Thanks!

**Comment by AhmeeedMostafa** [comment]
Hey @dclerici , please check this issue #6  u would fine how to do that there

**Comment by dclerici** [comment]
Thank you @AhmeeedMostafa. I didn't find that issue before. That's what i need.
