### ISSUE TITLE
History issue with reduceBeforeEdit in auto mode

### ISSUE THREAD

**Issue by arnofly** [scaleflex/filerobot-image-editor#113]
Hi,

Thanks to share your plugin. It's great!

I have 2 issues and I don't think is due to my use. In my case, the browser send the image to the plugin with my script. I mean that the image is not uploaded to a server and stay on the local machine. Your plugin do the rest ;)

If in the config constant I use the parameter "reduceBeforeEdit" in auto mode, the history is broken. To reproduce the bug, you have to set a value like 500 pixels for "widthLimit" and "heightLimit". With this setting, all the history is broken (reset, undo and redo).

The other issue is the opposite and finally I'll don't open a new issue for that. With the default value (2000) for "widthLimit" and "heightLimit", the history looks work well, but after a lot of tests I have seen that several user actions are not applied on the final image ready to download. With a value like 1200 pixels all actions are applied on the final image, but the history is totally broken... ;)

I use Firefox, but I have the same issues with quick test on Chrome.

**Comment by AhmeeedMostafa** [comment]
Hello @arnofly , thanks for your feedback
as we are working on the new major version and such an issue might take time to check and solve, we would test & make sure there is no such issue on the new major version.... so it's better to wait for the new version as it would contain more features and avoid different issues.

**Comment by AhmeeedMostafa** [comment]
@arnofly you could check the new version [v4](https://github.com/scaleflex/filerobot-image-editor/tree/v4), it shouldn't have such an issue
