### ISSUE TITLE
Force user to respect our ratio

### ISSUE THREAD

**Issue by lmslfm** [scaleflex/filerobot-image-editor#115]
Hi,

Thanks for releasing this amazing Image editor.

But I still have one question. I think it is not possible now as you said in this comment: https://github.com/scaleflex/filerobot-image-editor/issues/110#issuecomment-856176397

In our project, we want to get the picture in the final, just in the one aspect ratio like a square. For example, maybe you see that in many apps when a user wants to upload a profile picture. 

is this is supported by filerbot or not? 

Thanks, Ebrahim

**Comment by lmslfm** [comment]
@AhmeeedMostafa please see this issue!  I think this feature is so important if isn't implemented yet.

**Comment by AhmeeedMostafa** [comment]
Sorry for late reply, Could you please clarify more?
Do u mean to let the user first select (crop) a specific area of the image first then starts to edit it and save it with that new area edited?

**Comment by lmslfm** [comment]
@AhmeeedMostafa Thank you. No problem.

In our project, we using `filerobot-image-editor` to get a user profile image. I want to get the final photo in a specific aspect ratio. I want from `filerobot-image-editor` to force users to respect this aspect ratio. 


In most applications, we must upload photos with a square aspect ratio. For example, look at this screenshot.

![Screenshot 2021-07-19 014420](https://user-images.githubusercontent.com/70434418/126082423-52bff447-91be-49b7-928c-d6ea1c9fb5f3.png)



Could we have this feature in the  `filerobot-image-editor`? 

Thanks

**Comment by AhmeeedMostafa** [comment]
@lmslfm we would consider locked aspect ratio of cropping in the new version

**Comment by lmslfm** [comment]
@AhmeeedMostafa Ahan, Thanks.

Could you say when the new version will release?

And should I Close this issue now?

**Comment by AhmeeedMostafa** [comment]
@lmslfm  no clear ETA yet, and for the issue leave it opened we would close it once we have the new release with that feature
