### ISSUE TITLE
minCropAreaWidth and minCropAreaHeight options are unusable

### ISSUE THREAD

**Issue by vaniyokk** [scaleflex/filerobot-image-editor#116]
minCropAreaWidth and minCropAreaHeight config [options](https://github.com/fengyuanchen/cropperjs#mincropboxwidth) documentation states:

> The minimum size in pixels for crop area's width custom resizing, the user won't be able to resize the crop area width less than that size unless the crop area is resized through some crop preset.

But in fact, these values are passed to `cropperjs` options `minCropBoxWidth` and `minCropBoxHeight` which are relative and not absolute values according to [documentation](https://github.com/fengyuanchen/cropperjs#mincropboxwidth).

In result, this config options behave unpredictable and can't be used to restrict result image size after crop.

e.g setting for original 460x460 image
```
minCropAreaWidth={300}
minCropAreaHeight={300}
```
allows me to crop image to 195x195 on desktop and to 452x452 on mobile.

and setting
```
minCropAreaWidth={150}
minCropAreaHeight={150}
```

allows me to crop image to 98x98 on desktop and to 226x226 on mobile screens

I think this at least need to be mentioned in documentation, and need to be fixed, as crop restriction (in absolute pixel values) is very common feature, and current implementation is nearly useless

**Comment by AhmeeedMostafa** [comment]
@vaniyokk  thanks for noticing about that, we would check about it and make sure both docs and functionality are aligned in the new major version

**Comment by AhmeeedMostafa** [comment]
@vaniyokk please re-check the crop properties in the new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) released in BETA now it would be nice to hear your feedback
