### ISSUE TITLE
Incomplete or corrupt PNG file

### ISSUE THREAD

**Issue by fx1234** [scaleflex/filerobot-image-editor#117]
hi 

we try to transfer the image to our server after editing. around 15% of the images arrive there incorrectly and cannot be further processed

this is the error message from imagemagick: 
convert-im6.q16: Expected 8192 bytes; found 3481 bytes `image.png' @ error/png.c/MagickPNGErrorHandler/1628. [...]

**Comment by AhmeeedMostafa** [comment]
Hey @fx1234 , could you please provide more details about your issue and how do u produce it?

**Comment by fx1234** [comment]
we figured out what caused the error. if a user has a slow internet connection and / or closes the page before the ajax transfer is complete, only part of the png arrives at the server.

if you also have the problem, you should make sure that the user does not leave the site too early.
