### ISSUE TITLE
Â° - Encoding problems HTML - "Â" is displayed instead "&nbsp;"

### ISSUE THREAD

**Issue by dmitrykovalevsky89** [scaleflex/filerobot-image-editor#12]
Encoding problems HTML - "Â" is displayed instead "&nbsp;"

On "rotate" method
Finding Â° on file https://cdn.scaleflex.it/plugins/filerobot-image-editor/3.3.0/filerobot-image-editor.min.js

**Comment by dzmitry-stramavus** [comment]
fixed in **v3.4.0**

**Comment by dmitrykovalevsky89** [comment]
Thanks!
