### ISSUE TITLE
Image Editor Not Working in My Bubble-Based App

### ISSUE THREAD

**Issue by ensabahnoir** [scaleflex/filerobot-image-editor#121]
To whom it may concern:

I am a Bubble.io app creator and I am having issues with the File Robot Image Editor. When I put this plugin into my social network app and finally click on the green Download button to download an edited image, my app completely closes out. What is the issue and how can it be fixed? Please advise. Below is a link of a video that shows what the Image Editor does to my app:

https://drive.google.com/file/d/1N76MSvuQrMt0UBoaRMpwAIpJRe9xzrGV/view?usp=sharing

Best Regards,
Alex Williams

**Comment by AhmeeedMostafa** [comment]
Hello @ensabahnoir ,
Could we know how do u integrate it in your code through that bubble.io app?
