### ISSUE TITLE
crop default is 16:9

### ISSUE THREAD

**Issue by phucnguyenbn** [scaleflex/filerobot-image-editor#123]
Hi,
Please tell me if I want when I click on Crop, the default cropper-crop-box must be 16:9, what code option can I do this, thanks

**Comment by AhmeeedMostafa** [comment]
Hey @phucnguyenbn such a feature is considers in the new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) is released in BETA now it would be nice if you want to check your issue and let us know the feedback,
please check the `crop` object property and let us know your feedback,
thanks!
