### ISSUE TITLE
Preselect default tool

### ISSUE THREAD

**Issue by EthionM** [scaleflex/filerobot-image-editor#124]
Is there a way to have a tool preselected for the user when the editor opens?

**Comment by AhmeeedMostafa** [comment]
@EthionM Yes that kind of feature would be supported

**Comment by AhmeeedMostafa** [comment]
@EthionM Such a feature is implemented in new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) is released in BETA now it would be nice if you want to check your issue and let us know the feedback,
please check `defaultTabId` and `defaultToolId` properties
