### ISSUE TITLE
reduceBeforeEdit mode: manual not working

### ISSUE THREAD

**Issue by cggit** [scaleflex/filerobot-image-editor#130]
`reduceBeforeEdit: {
                            mode: 'manual',
                            widthLimit: 1920,
                            heightLimit: 1920
                        },`

mode: manual, Does not work tested on MacOS or Win10 latest chrome/firefox filerobot-image-editor version 3.12.17

I assume it would preset the resize fields to respect widthLimit or heightLimit allowing a user to quickly resize an image as per the recommended size or keep the original size. In other words the preset width and height are always the images original dimensions.

mode: auto resizes the image as expected.

Am I doing something wrong?

Thank you

**Comment by AhmeeedMostafa** [comment]
@cggit  we are in knowledge that resizing overall isn't working in the right way and we are considering its fix that in the new major version
