### ISSUE TITLE
Remove CDN load of images / fonts for npm release.

### ISSUE THREAD

**Issue by carlos22** [scaleflex/filerobot-image-editor#131]
It is very unfortunate that the npm package also loads images and fonts from the CDN. This makes it impossible to use the tool in non-internet locations. Please add a option to resolve the files locally.

**Comment by carlos22** [comment]
Related to: https://github.com/scaleflex/filerobot-image-editor/issues/84

Files with hard coded external resources (without examples and readme):  
* https://github.com/scaleflex/filerobot-image-editor/blob/0a34e91aad9cdfe9be9c9729e0542eb1b0eb3dda/src/utils/get-icon.js
* https://github.com/scaleflex/filerobot-image-editor/blob/0a34e91aad9cdfe9be9c9729e0542eb1b0eb3dda/examples/js/src/assets/fonts/helvetica-neue.css
* https://github.com/scaleflex/filerobot-image-editor/blob/0a34e91aad9cdfe9be9c9729e0542eb1b0eb3dda/src/assets/fonts/filerobot-font.css

The 'helvetica-neue' is the question if its a free font? I don't think so...

**Comment by AhmeeedMostafa** [comment]
Hey @carlos22 , as a workaround for now u could cache them in the service worker and use them offline with no issues as they are assets so they almost won't be changed.
btw. we are considering that in the new version and all assets would be included and it might be useful to tell us about your usecase

**Comment by carlos22** [comment]
Ok yeah that would also be possible. But my changes do not affect the build, its almost identical - expect it is possible to have the file local if you use the correct webpack config. The default config uses the CDN.

Well we are not allowed to use CDNs and other external resources, and thats something everybody should look more at. What if the CDN goes offline? Etc.

**Comment by AhmeeedMostafa** [comment]
@carlos22 got u, thanks for your sharing seems cool we are considering that in the upcoming version

**Comment by AhmeeedMostafa** [comment]
@carlos22 Such an issue is fixed in the new release,
[V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) is released in BETA now it would be nice if you want to check it and let us know the feedback
