### ISSUE TITLE
Image corruption when executing multiple edits.

### ISSUE THREAD

**Issue by asnyder13** [scaleflex/filerobot-image-editor#133]
Steps to reproduce:

1. Open an image (consistently reproducible on mobile, occasionally visible on desktop Firefox)
2. Rotate left
3. Crop (to a relatively small area, approx. 1/3rd new height, 1/2 new width)
4. Add effect to image (Grungy was used, but the issue can be seen with others)
5. Apply effects and download image, or display base64 data in <img> element

Resulting image:
![pietro-de-grandi-unsplash](https://user-images.githubusercontent.com/6961857/133276166-0f808db6-5a18-495b-bdf2-02f64deb16b5.jpg)

Various levels of corruption will appear depending on the amount cropped.  It is always along the lines of the attached image; multiple lines similar to what used to be the bottom of the cropped area.

The provided image was created using the [demo image editor](https://scaleflex.github.io/filerobot-image-editor/).

**Comment by AhmeeedMostafa** [comment]
@asnyder13 thanks for reporting, it would be fixed in the new versions

**Comment by asnyder13** [comment]
It seems that the bug is only present when `isLowQualityPreview` is set to `true`.  After changing that value, I am unable to reproduce after multiple tries.  Before changing, the issue appears every time.

**Comment by AhmeeedMostafa** [comment]
@asnyder13 ,
new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) is released in BETA now it would be nice if you want to check it and let us know the feedback
