### ISSUE TITLE
Unknown or Invalid JPEG Marker type is Found

### ISSUE THREAD

**Issue by DavidVilallonga** [scaleflex/filerobot-image-editor#136]
Thank you very much for the code.
There is a small issue however, when you save an edited image, you cannot open it with photoshop, it gives you an error: "Unknown or Invalid JPEG Marker type is Found".
I guess the error may be in the const base64ToBlob = (base64) conversion.

Could you have a look.
Thank you
David

**Comment by AhmeeedMostafa** [comment]
Hello @DavidVilallonga we don't have enough time to work on fixing the current version as we are working on a new major version that is using new lib. for doing modifications and new code base, so it's expected to have a solution for such an issue (if it's existed) in the upcoming major version.

**Comment by AhmeeedMostafa** [comment]
Hey @DavidVilallonga ,
new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) is released in BETA now it would be nice if you want to check your issue and let us know the feedback
