### ISSUE TITLE
Some multiple edits are not applied (e.g. resize + crop)

### ISSUE THREAD

**Issue by carlos22** [scaleflex/filerobot-image-editor#139]
If you first crop a image and then rotate it (rotate left), it is not cropped anymore. You can check on you own demo.

**Comment by AhmeeedMostafa** [comment]
Hey @carlos22 , we are aware of such an issue and it would be considered in the new major version
thanks for your report

**Comment by AhmeeedMostafa** [comment]
@carlos22 it's fixed in the new version, rotate will be added soon
