### ISSUE TITLE
How to apply resize instead of downloading the image?

### ISSUE THREAD

**Issue by thapaliya19** [scaleflex/filerobot-image-editor#14]
In the resize method, there is no option to apply the edit. It only shows the option to cancel and download. How can I add the apply method there?
![image](https://user-images.githubusercontent.com/34963065/68733039-91405a80-05fd-11ea-902b-c65c6d44b8f8.png)

**Comment by dzmitry-stramavus** [comment]
hey @thapaliya19,

Resize method goes in the last place. So, after applying all transformations (crop, filters etc.). You can resize and DOWNLOAD => apply resize and download. If you configured Filerobot Service, you will be apply to "SAVE" => apply resize and upload to your server folder.
