### ISSUE TITLE
Image size increase when uploaded to server ( Base64 )

### ISSUE THREAD

**Issue by stoneshaq** [scaleflex/filerobot-image-editor#140]
Hi there, 
Thanks for the great package. Your effort is much appreciated. 
I use your package for my saas and I have a simple problem. 
After editing the image at the front end, I send it to my backend using onComplete method and props.canvas.toDataURL() .. Because it is converted into base64, the size of the file increases by around 50%. 
What is the best way to compress the image size?
Thanks so much for your time

**Comment by AhmeeedMostafa** [comment]
Hey @stoneshaq sorry for late reply,
the only idea IK that might be useful is to dismiss sending base64 and send the image's bytes as the image file should be compressed already
