### ISSUE TITLE
v4: How to upload the data to the server

### ISSUE THREAD

**Issue by carlos22** [scaleflex/filerobot-image-editor#145]
With v4 many issues are gone now thats great. But how can we upload the image efficient to the server (without any cloud). I used the following: 

```
            onBeforeComplete: function (e) {
                e.canvas.toBlob(function (blob) {
                    var form = new FormData();
                    form.append('image', blob, imageName);
                    $.ajax({
                        url: "/mybackend/attachments/33',
                        type: "POST",
                        data: form,
                        processData: false,
                        contentType: false,
                        success: function (response) {
                            console.log('Image Replaced');
                        },
                        error: function (err) {
                            console.log('Upload Error', err.responseJSON);
                        }
                    });
                }, 'image/jpeg', 0.9);
                return false;
            }
```

Now the `onSave` provides the image as base64 encode, sure i can decode it and put it in the form, but thats not very efficient. Is there a better way? Look at how ugly I would need to put the data in the Form: https://stackoverflow.com/a/61321728

**Comment by carlos22** [comment]
A bit nicer is `fetch(dataUri)` which is now supported by all major browsers. But its still very inefficient as we might just get the blob from the canvas in the save method! Fetch Example: https://stackoverflow.com/a/40141094

**Comment by AhmeeedMostafa** [comment]
Hey @carlos22 thanks for your feedback,

Already in the next update of BETA we would provide imageCanvas in the returned parameter too but there is some drawback using it (it doesn't support quality that might be changed by the UI while saving by the default behavior modal) so u will need to apply that quality manually...

- and here you are an example using the XHR  (supports almost all browsers) with base64

```
onSave: (savedImageInfo) => {
  const xhr = new XMLHttpRequest();
  xhr.responseType = 'blob';
  xhr.open('GET', savedImageInfo.imageBase64)
  xhr.onload = () => {
      const responseInBlob =  xhr.response;
      // Send blob to backend as u want
  }
}
```

- Using fetch if u want
```
onSave: (savedImageInfo) => {
fetch(savedImageInfo.imageBase64)
   .then((response) => response.blob())
   .then((imgBlob => {
         // Send blob to backend as u want
   })
}
```

**Comment by carlos22** [comment]
Thanks, didn't know about XHR support for it, only knew fetch (which is now widely supported but not on IE).

**Comment by TukuToi** [comment]
@carlos22 depending where you send the data to, if it is PHP (I am sure other scripting languages have similar constructs), you can do this:
1. In AJAX call send `imageData.imageBase64` in `data` (goes to `$_POST`)
2. In backend (PHP in my case), get $_POST and do something like this:
```
$data = $_POST['imgURL'];
list( $type, $data ) = explode( ';', $data );
list( $enc, $data)      = explode( ',', $data );
$image_size = (int)(strlen(rtrim($data, '=')) * 0.75); // in byte
$data = base64_decode($data);
```

$data now holds the Image. You can put it on your server using `file_put_contents( 'path/to/file', $data )`;

I found this to be both CSP compliant (it does not use `fetch()`) and pretty performant too, since file robot already provides the Base64 string, and PHP is pretty quick in transforming it. I tested this with few k's image sizes, and I am very satisfied.
