### ISSUE TITLE
v4: How to theme

### ISSUE THREAD

**Issue by carlos22** [scaleflex/filerobot-image-editor#146]
Could you provide a proper theme example? The link to the ui package of @scaleflex is not very helpful.

**Comment by AhmeeedMostafa** [comment]
@carlos22  You would need to pass an object looks like the same as mentioned in the property's default value [here](https://github.com/scaleflex/filerobot-image-editor/tree/v4#theme) with the property and values you want to override,
the available properties to override are mentioned in that default theme referred to in the link mentioned of @scaleflex/ui
also this a [link ](https://github.com/scaleflex/ui/blob/master/packages/ui/src/utils/types/palette/color.ts#L1)  for all the available properties of "palette" property that contains colors as almost this is what's needed

another example:
```js
{
   // .....
   theme: {
       palette: {
            'borders-primary': '#ffffff',
            'bg-primary-active': '#cccccc',
            // ......
       }
   }
}
```

**Comment by carlos22** [comment]
Thanks I think I got it. But would be nice to have a complete json with the default values. Its a bit crumbersome to serach for the correct key and then look up the actual default value and so on :)

**Comment by AhmeeedMostafa** [comment]
Yup maybe the team working on @scaleflex/ui would provide such a thing in the future and we would mention it once they're.
thanks for your suggestion
