### ISSUE TITLE
v4: ask before close is not working

### ISSUE THREAD

**Issue by carlos22** [scaleflex/filerobot-image-editor#147]
The question before close is not working in the current beta version. The `avoidChangesNotSavedAlertOnLeave` option suggests there is a alert question? Version: 4.0.0-beta.12

**Comment by AhmeeedMostafa** [comment]
@carlos22 could u provide more info? it's working good and I've just tested it on the demo link mentioned in docs
*for you to notice it works only if there are some changes that are not saved but if latest changes saved then it won't be shown*
![image](https://user-images.githubusercontent.com/22754338/146555974-78aac629-5a4b-42d4-8522-b872dc7a3fd9.png)

**Comment by carlos22** [comment]
Ah yes it seems to work fine if you close the tab/browser, but not if you use the regular [x] to close it. Sorry I misunderstood that. In the close case we can add a question in the `onClose` handler, but AFAIK was this a problem to decide if the user has done some changes or not in v3. I just assumed the question will also be asked when a regular close is done. So long story short, how we know to have unsaved changes in the `onClose` Handler?

**Comment by AhmeeedMostafa** [comment]
@carlos22 good question we could add haveChangesNotSaved parameter for the onClose and in that case back to you as a developer to apply closing, showing some modal from your side...etc.
it might be added in the next BETA released would update this issue after adding

**Comment by AhmeeedMostafa** [comment]
@carlos22 it's added in the new BETA version now (15) let me know your feedback

**Comment by carlos22** [comment]
Thanks a lot. That works great :-)

**Comment by hamza221** [comment]
> [@carlos22](https://github.com/carlos22) good question we could add haveChangesNotSaved parameter for the onClose and in that case back to you as a developer to apply closing, showing some modal from your side...etc. it might be added in the next BETA released would update this issue after adding

It looks like the parameter exists but there's no way to actually disable the default modal
