### ISSUE TITLE
QUESTION: Rotate image with V4

### ISSUE THREAD

**Issue by lookingdown** [scaleflex/filerobot-image-editor#148]
Hi..
Great image editor thanks.. 
One thing I can not figure out is how to rotate and image, lets say the horizon is a bit tilted on a photo an need to be corrected..
How to access rotation funcionality..
(with V4 beta)
Thanks again..

**Comment by AhmeeedMostafa** [comment]
@lookingdown Hey, rotation functionality is missing currently in V4 BETA, but it'll be added very soon wait for it!

**Comment by lookingdown** [comment]
Thats good news.. Do you have any approximate date of arrival : ) . .

**Comment by AhmeeedMostafa** [comment]
It would be the next feature to work on, it's expected to be added before the prod. release so it might be there before end of the month but not guaranteed yet...

**Comment by lookingdown** [comment]
Ok.. Thanks..

Heres pt-br ( or just pt ) if you want to add..

export default { 
  'header.image_editor_title': 'Editor de Imagens Filerobot',
  'header.toggle_fullscreen': 'Alternar para tela inteira',
  'header.close': 'Fechar',
  'header.close_modal': 'Fechar janela',
  'toolbar.download': 'Baixar',
  'toolbar.save': 'Salvar',
  'toolbar.apply': 'Aplicar',
  'toolbar.saveAsNewImage': 'Salvar como nova imagem',
  'toolbar.cancel': 'Cancelar',
  'toolbar.go_back': 'Voltar',
  'toolbar.adjust': 'Ajustar',
  'toolbar.effects': 'Efeitos',
  'toolbar.filters': 'Filtros',
  'toolbar.orientation': 'Orientação',
  'toolbar.crop': 'Recortar',
  'toolbar.resize': 'Redimensionar',
  'toolbar.watermark': 'Marca d'água',
  'toolbar.focus_point': 'Ponto de foco',
  'toolbar.shapes': 'Formas',
  'toolbar.image': 'Imagem',
  'toolbar.text': 'Texto',
  'Adjust.brightness': 'Brightness',
  'ajustar.contrast': 'Contraste',
  'ajustar.exposição': 'Exposição',
  'ajustar.saturação': 'Saturação',
  'idance.rotate_l ':' Girar para a esquerda ',
  'orientação.rotate_r': 'Girar para a direita',
  'idance.flip_h ':' Inverter horizontalmente ',
  'idance.flip_v ':' Inverter verticalmente ',
  'pre_resize.title': 'Gostaria de reduzir a resolução antes de editar a imagem?',
  'pre_resize.keep_original_resolution': 'Manter a resolução original',
  'pre_resize.resize_n_continue': 'Redimensionar e continuar',
  'footer.reset': 'Redefinir',
  'footer.undo': 'Desfazer',
  'footer.redo': 'Refazer',
  'spinner.label': 'Processando ...',
  'warning.too_big_resolution': 'A resolução da imagem é muito grande para a web. Isso pode causar problemas com o desempenho do Image Editor. ',
  'common.x': 'x',
  'common.y': 'y',
  'common.width': 'largura',
  'common.height': 'altura',
  'common.custom': 'personalizado',
  'common.original': 'original',
  'common.square': 'quadrado',
  'common.opacity': 'Opacidade',
  'common.apply_watermark': 'Aplicar marca d'água',
  'common.url': 'URL',
  'common.upload': 'Carregar',
  'common.gallery': 'Galeria',
  'common.text': 'Texto',
};

**Comment by AhmeeedMostafa** [comment]
It seems those translations are for the old version, not v4.
we would appreciate adding for the latest version we could consider on our translations' backend in V4 as we made translations handled from the integration side.

**Comment by AhmeeedMostafa** [comment]
@lookingdown The feature is applied in the new BETA version `v4.0.0-beta.20`, let us know if there is any related issue
