### ISSUE TITLE
VanillaJS ~ Module requires relative reference / Requested module does not provide an export named 'default'

### ISSUE THREAD

**Issue by webdevandeverythingelse** [scaleflex/filerobot-image-editor#149]
Trying to test the new Beta via a quick VanillaJS implementation (code at bottom) - however I'm having issues with the browser and the importing of the modules. 

When I follow the exact way done in the ReadMe of the project, I get: "Uncaught SyntaxError: Cannot use import statement outside a module". I tried adding the type='module' attribute to my inline script, which gets to the next error: "Uncaught TypeError: Failed to resolve module specifier "filerobot-image-editor". Relative references must start with either "/", "./", or "../". "

I then tried modifying the 1st line of the inline script, so the "Import FilebotImageEditor..." line ended with the fully-qualified URL used in the external script's src attribute - but I then get this issue: "Uncaught SyntaxError: The requested module 'https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/4.0.0-beta/filerobot-image-editor.min.js' does not provide an export named 'default' "

I'm not expert with the ES6 module paradigm so it might be something stupid I'm missing in my configuration. Thanks for your help!

Code:

`<script src="https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/4.0.0-beta/filerobot-image-editor.min.js"></script>`

`<script type="module">
import FilerobotImageEditor, { TABS, TOOLS } from 'https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/4.0.0-beta/filerobot-image-editor.min.js';
//import FilerobotImageEditor, { TABS, TOOLS } from 'filerobot-image-editor';

const config = {
  img: 'https://scaleflex.airstore.io/demo/stephen-walker-unsplash.jpg',
  annotationsCommon: {
    fill: '#ff0000'
  },
  Text: { text: 'Filerobot...' },
  tabs: [TABS.ADJUST, TABS.ANNOTATE, TABS.WATERMARK], // or ['Adjust', 'Annotate', 'Watermark']
  defaultTabId: TABS.ANNOTATE, // or 'Annotate'
  defaultToolId: TOOLS.TEXT, // or 'Text'
};

// Assuming we have a div with id="editor_container"
const filerobotImageEditor = new FilerobotImageEditor(
  document.querySelector('#editor_container'),
  config
);

filerobotImageEditor.render({
  onClose: (closingReason) => {
    console.log('Closing reason', closingReason);
    filerobotImageEdtior.terminate();
  }
});
</script>

<div id="editor_container" />`

**Comment by AhmeeedMostafa** [comment]
@webdevandeverythingelse that import example is for VanillaJS version that is imported from NPM not CDN

as you are using it from CDN then u have to use `window.FilerobotImageEditor` instead of import
Please check the following note (it's already mentioned in the docs below VanillaJS example):

> Important Note: if you are importing the library from CDN then you could access it using window.FilerobotImageEditor and access both TABS & TOOLS from window.FilerobotImageEditor.TABS & window.FilerobotImageEditor.TOOLS.

**Comment by webdevandeverythingelse** [comment]
Shame on me! Of course, you are 100% correct. You can close this ticket.

NOTE: I did actually have to still add a line of code with a blank method for the "onSave" method for it to fully work (it complained that method was required): `onSave: () => {}`

NOTE 2: The documentation should probably include explicit mention of the JS attribute needed for the CDN script to work: `type="module"`

Here's my full working example going the CDN method for anyone in the future who finds this:

`<script src="https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/4.0.0-beta/filerobot-image-editor.min.js"></script>

<script type="module">
const config = {
  img: 'https://scaleflex.airstore.io/demo/stephen-walker-unsplash.jpg',
  annotationsCommon: {
    fill: '#ff0000'
  },
  Text: { text: 'Filerobot...' },
  tabs: [window.FilerobotImageEditor.TABS.ADJUST, window.FilerobotImageEditor.TABS.ANNOTATE, window.FilerobotImageEditor.TABS.WATERMARK], // or ['Adjust', 'Annotate', 'Watermark']
  defaultTabId: window.FilerobotImageEditor.TABS.ANNOTATE, // or 'Annotate'
  defaultToolId: window.FilerobotImageEditor.TOOLS.TEXT, // or 'Text'
};

// Assuming we have a div with id="editor_container"
const filerobotImageEditor = new FilerobotImageEditor(
  document.querySelector('#editor_container'),
  config
);

filerobotImageEditor.render({
  onClose: (closingReason) => {
    console.log('Closing reason', closingReason);
    filerobotImageEdtior.terminate();
  },
  onSave: () => {}
});
</script>

<div id="editor_container" />`

**Comment by AhmeeedMostafa** [comment]
For note1 that's right it's required as it has no default functionality from our side it's left for you to utilize the output from your side

For note2 it is not needed to add type="module" as the CDN version is not an es6 module

**Comment by webdevandeverythingelse** [comment]
For Note 2: Yes you are correct, I was able to remove that - however I was getting an error after removing the type=module attribute: `filerobot-image-editor.min.js:8 Uncaught Error: `container` (argument 0) is required to initialize the image editor plugin.`

To fix the issue, the initialization script was put below the container div element (with id="editor_container" on it) and everything worked as expected.

**Comment by AhmeeedMostafa** [comment]
Yes you should add your logic after loading the HTML element to be able to find it in the document,
glad that you solved your issue!
