### ISSUE TITLE
finishButtonLabel fails to change button label

### ISSUE THREAD

**Issue by pantpoorti** [scaleflex/filerobot-image-editor#150]
Hi,

I am looking into this library to include in my React project. So far it looks great!
I wanted to change the label of the "Download" button to "Update".
I found the finishButtonLabel property while going through the documentation.
But the button still appears as "Download".

I am using it like below,
 `<FilerobotImageEditor
        src={lastImage.current || 'https://picsum.photos/2000'}
        finishButtonLabel="Update"
        onClose={() => { setShowImageEditor(false) }}
        onBeforeComplete={(props:any) => { 
            lastImage.current = (props.canvas.toDataURL())
            return false
        }}
        show={showImageEditor} />`

Am I using it incorrectly?

**Comment by AhmeeedMostafa** [comment]
Hey @pantpoorti ,
You should provide it inside config property
`config={{ finishButtonLabel: 'update' }}`

Also I advice you to switch to V4 (it still in BETA but very soon it'll be in prod.) as it has more features, customizations & fixed some bugs in latest v3 release

**Comment by pantpoorti** [comment]
Hello!

Thanks for the response. I have include V4 in the project. Will test it out!
The config doesn't seem to work.
Still showing 'Download' label.

This is a react application. I saw the config setup in the VanillaJS example.

My code now looks like this,
`<FilerobotImageEditor
                src={lastImage.current || 'https://picsum.photos/20000'}
                config={{ finishButtonLabel: 'Update' }}
                onClose={() => { setShowImageEditor(false) }}
                onBeforeComplete={(props:any) => { 
                    lastImage.current = (props.canvas.toDataURL())
                    return false
                }}
                show={showImageEditor} />`

Your help is much appreciated!

**Comment by AhmeeedMostafa** [comment]
Could you please make an example on codesandbox or some other platform and share it?
It should work fine if you made it `config={{ finishButtonLabel: 'Update' }}`
![image](https://user-images.githubusercontent.com/22754338/148347866-21605f36-a7e7-4811-9a37-3ece2577ecdf.png)

**Comment by pantpoorti** [comment]
Sure, I added the change to one of the samples. 
Here is a [link](https://codesandbox.io/s/brave-sammet-dqdr8).

Another issue I am facing is in integrating V4.
My react version is 16.10.2 and styled-components version is 5.1.0, so that should meet the requirements.
But, I am getting this error,

> ./node_modules/react-filerobot-image-editor/lib/components/common/Slider/Slider.styled.js
Module not found: Can't resolve '@scaleflex/ui/core/continuous-slider' in '..\ReactApp\node_modules\react-filerobot-image-editor\lib\components\common\Slider'

Any ideas?

**Comment by AhmeeedMostafa** [comment]
the issue for finishButtonLabel doesn't work cause u're using an old version, that propery is supported starting from +v3.12.15,

for V4 issue could u tell me which BETA version are u using?

**Comment by pantpoorti** [comment]
Using version =>
![image](https://user-images.githubusercontent.com/32049869/148366284-e85ea206-f349-42db-ac72-19c4cb304f41.png)

**Comment by AhmeeedMostafa** [comment]
We should close this issue, so could u open a new issue with that issue and mention some helpful details to check?
It would be nice also to provide version & dependencies properties mentioned in node_modules/react-filerobot-image-editor
In that new issue as it might hel

**Comment by AhmeeedMostafa** [comment]
Closed for answering, for the other issue of V4 please install the latest NPM version and if u still have that issue please open another issue/thread
