### ISSUE TITLE
Orientation range issue in mobile 

### ISSUE THREAD

**Issue by danielkeva** [scaleflex/filerobot-image-editor#152]
Hi, first of all, I want to say thank you for your hard work on this incredible library!

I'm having an issue with the Orientation tool on mobile view.
Seems like the range's Svg doesn't take the full width of the input
is there a way to hide only the range within the Orientation tool?
I need the rotate feature so I can't just erase it from the config.tools array...

![image](https://user-images.githubusercontent.com/60192971/150153047-c5c1eb77-7ffc-4d8e-8d5a-6587da429596.png)

**Comment by AhmeeedMostafa** [comment]
Hey Daniel,  you could achieve that through CSS using display property

btw. please note we are not supporting v3 anymore it's better to start checking v4

**Comment by danielkeva** [comment]
> Hey Daniel, you could achieve that through CSS using display property
> 
> btw. please note we are not supporting v3 anymore it's better to start checking v4

Wish I could use CSS but there are no selectors or className that I can use.
I will look into the v4

**Comment by AhmeeedMostafa** [comment]
you could use this selector (image-editor-range) 
in this way: .`image-editor-range + svg` u caught the svg range
