### ISSUE TITLE
How to Build Beta Version via NPM Console?

### ISSUE THREAD

**Issue by webdevandeverythingelse** [scaleflex/filerobot-image-editor#153]
Not an NPM expert but I have a general grasp of the idea - however I'm clearly missing something, as I can't get it to generate the final output (the VanillaJS script.) Usually I just use the CDN link, but since there isn't a Beta version hosted on the CDN, I need to figure out how to compile the final script.

Is this the correct CMD command to build the script? `npm run build:lib`

I'm running that command in this directory: `\filerobot-image-editor-4\packages\filerobot-image-editor`

This is the error I am stuck on:

`SyntaxError: src/index.js: Unexpected token (10:14)
   8 |
   9 | class FilerobotImageEditor {
> 10 |   static TABS = TABS;
     |               ^
  11 |   static TOOLS = TOOLS;
  12 |   #render;
  13 |   #unmount;
npm ERR! code ELIFECYCLE
npm ERR! errno 1`

Sorry, I know this is probably stupid and trivial, but been giving me trouble for the past hour. I'll update here if I get it to work.

**Comment by AhmeeedMostafa** [comment]
@webdevandeverythingelse there is already a CDN link for Vanilla JS version
https://github.com/scaleflex/filerobot-image-editor/tree/v4#cdn

and for building CDN bundle u should use `build:dist` which stands for (build distribution which is basically called on JS bundles)

**Comment by webdevandeverythingelse** [comment]
Is that link manually updated on the CDN? It doesn't seem to be in sync with the repo (currently: v4.0.0-beta.27) - right now the link goes to a script with this on the third line: v4.0.0-beta.25

Link: https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/4.0.0-beta/filerobot-image-editor.min.js

PS. Is there anyway you could host an unminified version of the VanillaJS script on the CDN? Basically same URL without the ".min" before the file ending: https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/4.0.0-beta/filerobot-image-editor.js

**Comment by AhmeeedMostafa** [comment]
@webdevandeverythingelse yes as we are in BETA it's manually sync, it'll be automated once going to prod. and the CDN will be updated with latest version EOD, 
may I know what's the idea behind having it without .min?

**Comment by jjxtra** [comment]
using `build:dist` produces `Missing script: build:dist`
