### ISSUE TITLE
CSS Issues causing Filerobot React Component to break application

### ISSUE THREAD

**Issue by JessenDGibbs** [scaleflex/filerobot-image-editor#154]
I am trying to integrate the Filerobot React component into my React app, but when I load the page with the component in it I am returned with a node_module error indicating that the ImageEditrWrapper.js file is causing global CSS issues. I will add a screenshot of the exact error shortly, but in the meantime, if there are any possible solutions please share.

**Comment by AhmeeedMostafa** [comment]
@JessenDGibbs Please provide more info to be able to help you, also it's better to check the V4 which is in BETA

**Comment by JessenDGibbs** [comment]
![error](https://user-images.githubusercontent.com/67168121/151810895-8da97beb-f6d5-40e3-bfee-47cffefeecdd.png)
![node_error](https://user-images.githubusercontent.com/67168121/151811001-fe4bb331-f98c-4a27-b0f8-2938c73e754a.png)


Here are screen shots of the issues we are having. I will checkout v4 in the meantime

Thank you.

**Comment by AhmeeedMostafa** [comment]
This is a kind of restriction from Nextjs as they don't allow such global imports from node_modules packages as v3 does, so you should use v4 as it doesn't have such global imports.
for the 2nd error shown (CanvasRenderingContext2D is not defined) this is cause the editor for client side not server side so either to prevent rendering the editor on the server side of Nextjs or to simulate the browser's features used in the editor as CanvasRenderingContext2D

**Comment by kirti18patel** [comment]
I am also facing same error. I am now using v4, but I am getting `SyntaxError: Cannot use import statement outside a module`. Please give me ways to resolve it.

**Comment by AhmeeedMostafa** [comment]
@kirti18patel Such an issue is related to your project as we don't use `MUI` in the plugin

**Comment by kirti18patel** [comment]
Just after installation and import package, I am getting `SyntaxError: Cannot use import statement outside a module` indicating origin of error as `/node_modules/react-filerobot-image-editor/lib/index.js`. I am using v4 branch. Please share possible solution.

**Comment by AhmeeedMostafa** [comment]
@kirti18patel could you please post how you are importing the package? it would be nice to give some useful information (code or create some codesandbox demo)

**Comment by kirti18patel** [comment]
`   "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-filerobot-image-editor": "^4.0.0-beta.28",
    "styled-components": "^5.3.3",`
    
`import FilerobotImageEditor, { TABS, TOOLS } from 'react-filerobot-image-editor';`

After installing above packages, when I import, it is throwing error `SyntaxError: Cannot use import statement outside a module`

**Comment by AhmeeedMostafa** [comment]
@kirti18patel seems like your project doesn't support ES6 modules, please re-check your project's configurations,
also try to add `"type": "module"` in plugin's (`node_modules/react-filerobot-image-editor/package.json`) and check if it solved the issue let me know to consider it in the future updates though I don't think so it's the reason,

For NextJS it should be compatible  but as NextJS is SSR and the plugin for frontend side you should avoid rendering it on the Server side or if you faced some undefined prototypes you should simulate them on the server side.

**Comment by ProgaPanda** [comment]
Hey @kirti18patel , can you share how did you solve the `SyntaxError: Cannot use import statement outside a module` as I've been struggling with the same error using nextjs

**Comment by kirti18patel** [comment]
hey @ProgaPanda , I was not able to solve this error. Even after following the steps mentioned it was still throwing error. So I moved to one of the paid service, which is working perfectly for me now.

**Comment by ProgaPanda** [comment]
@AhmeeedMostafa Hey man, can you help with this, it seems like the library isn't compatible with next js, even with react versions less than 18. 
Next js is a big market and I'm willing to help if you cannot reproduce it.
