### ISSUE TITLE
Change image size inside editor

### ISSUE THREAD

**Issue by lashakaraulashvili** [scaleflex/filerobot-image-editor#155]
Hello, how to change image size inside editor? its too small.
![Screenshot from 2022-01-29 20-21-01](https://user-images.githubusercontent.com/83213478/151668777-20ef700d-2f97-45a4-9924-0db2c54f9c00.png)

**Comment by AhmeeedMostafa** [comment]
@lashakaraulashvili you need to give the plugin's wrapper some height and the plugin's height is set with 100% so it will respect the parent's height

**Comment by lashakaraulashvili** [comment]
@AhmeeedMostafa  thank you.

**Comment by lashakaraulashvili** [comment]
Is there anyway to make live preview? how can i get change event?

**Comment by AhmeeedMostafa** [comment]
@lashakaraulashvili could u please mention your use case and what do u mean by live preview exactly?

**Comment by lashakaraulashvili** [comment]
When user cropping, show cropped preview
![crop](https://user-images.githubusercontent.com/83213478/151700727-83789ff0-ff1e-4b35-a474-6221195312c0.png)

**Comment by AhmeeedMostafa** [comment]
@lashakaraulashvili it might be considered in the future as additional feature yes it would be helpful
