### ISSUE TITLE
Transparent background for shape selection

### ISSUE THREAD

**Issue by akashp6603** [scaleflex/filerobot-image-editor#156]
Hi, we want only border for shapes like (Rectangle, Polygon and Ellipse). not filled color.(transparent background)

![image](https://user-images.githubusercontent.com/80953726/151769100-5f84166a-0f76-42ae-a212-203a1fa8cfce.png)

#156

**Comment by akashp6603** [comment]
> Hi, we want only border for shapes like (Rectangle, Polygon and Ellipse). not filled color.(transparent background)
> 
> ![image](https://user-images.githubusercontent.com/80953726/151769100-5f84166a-0f76-42ae-a212-203a1fa8cfce.png)
> 
> #156

**Comment by zhouhuiquan** [comment]
we want seperate fill color too.
