### ISSUE TITLE
TRANSPARENT BACKGROUND WITH SHAPE SELCTION ON IMAGE 

### ISSUE THREAD

**Issue by akashp6603** [scaleflex/filerobot-image-editor#157]
Hi,

I want Only Border But Not filled color in Shape Selection Like ,

1. Rectangle
2. Polygon
3. Ellipse

with Transparent Background and I have installed Yarn Packages but still Can't run the Project.

![image](https://user-images.githubusercontent.com/80953726/151774973-79bf8e52-7c54-4f10-8655-6940f73f1bf6.png)

**Comment by AhmeeedMostafa** [comment]
For transparent background, will be added in the upcoming updates u'll be able choose a transparent color from the color palette instead of filled color.

for the issue with running the project u should open the root folder of the project and run (yarn) then run (yarn dev)

**Comment by akashp6603** [comment]
Thankyou.

You are right sir but we want only transparent shapes with border size and  without any kind filled color.

**Comment by shaneeshpatel1** [comment]
@AhmeeedMostafa : Thank you for the answer.

Can we know when you will release the feature for transparent background for the shape, Its amazing tool. we are missing this only.

Thanks!

**Comment by AhmeeedMostafa** [comment]
@shaneeshpatel1 it's expected to be this week

**Comment by shaneeshpatel1** [comment]
@AhmeeedMostafa : Thank you for the quick answer. We required the shapes with border only in your tool.

**Comment by AhmeeedMostafa** [comment]
@akashp6603 @shaneeshpatel1 transparency has been added in color picker in the BETA release u could check it

**Comment by akashp6603** [comment]
@AhmeeedMostafa Thankyou for your cooperation. I will check & let you know.

**Comment by akashp6603** [comment]
@AhmeeedMostafa In which file you have changed ?

**Comment by shaneeshpatel1** [comment]
@AhmeeedMostafa  Thank you for the quick implementation.

**Comment by shaneeshpatel1** [comment]
@AhmeeedMostafa : There is two issue in editor.
1. Text Writing on Safari Browser in iPad and iPhone. When we're writing text, we can not write in editor in Safari browser.
2. We can not apply CSS. We have to know, how to apply CSS because all the CSS color come to js and not getting.

Waiting for your reply.

**Comment by AhmeeedMostafa** [comment]
@shaneeshpatel1
1. could you please open a new issue and add more information ex. Safar browser version, exact producing steps,/it always happens or sometimes?
2. You could apply colors through theme property as mentioned in the docs, for adding other CSS it is not supported yet but in the future we'll add static class names for the elements to be able to override CSS from your side

**Comment by shaneeshpatel1** [comment]
HI @AhmeeedMostafa 

Thanks for the quick answer. As below we have mentioned exact producing steps. It always happnes.

We have checked Safari Browser in iPad and iPhone.
Below is the Version of iPad
IPAD 8th Generation & IPAD Version - 15.2
**Safari Version - 15.2 - Try to write the Text -** 
**Steps**
1. Open the URL in Safari Browser : https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/v4_beta-demo/index.html?vh=fc3dd2&func=proxy
2.  Click on Draw Option
3. Click on Text to write text on Picture.
4. Try to change the text but not write anything or change the text.

For ,Chrome Version - 97.0.4692.84 - Not Load the Editor Properly 

Waiting for your reply.

Shaneesh Patel

**Comment by AhmeeedMostafa** [comment]
@shaneeshpatel1 having a new issue for the bug/question is better for tracking so please consider that next time, could u please try it again on the latest beta release and check if the issue still there?
