### ISSUE TITLE
beginCropArea - is it working in v3?

### ISSUE THREAD

**Issue by working-name** [scaleflex/filerobot-image-editor#158]
Hi there,

Read a ticket about v4 implementing default crop other than 16:9 but not sure if that's really about the selection part or simply the values.

I passed a number value to `beginCropArea` and it seems it doesn't change the default selection when clicking the crop button.

https://codesandbox.io/s/trusting-pond-dypcm

Am I doing it wrong or am I misunderstanding the setting altogether?

**Comment by AhmeeedMostafa** [comment]
@working-name I didn't understand your question about v4,
for `beginCropArea` it's working fine on your demo, its value ranges between 0 to 1 , 1 means the whole image's size so u need to choose lower value if u need to notice the difference

**Comment by working-name** [comment]
Got it, so it has nothing to do with `cropPresets`. My bad. Thanks!
