### ISSUE TITLE
Integration with webpack

### ISSUE THREAD

**Issue by guillaumecardon** [scaleflex/filerobot-image-editor#159]
Hello,

I want to use Filerobot Image in a Symfony project, using Webpack config.
I used yarn to get library `yarn add filerobot-image-editor` : Installation OK ( filerobot-image-editor@3.12.17 )

In a "testFileRobot.js", i have this : 
```
import FilerobotImageEditor, { TABS, TOOLS } from 'filerobot-image-editor';
const config = {
    img: 'https://scaleflex.airstore.io/demo/stephen-walker-unsplash.jpg',
    annotationsCommon: {
        fill: '#ff0000'
    },
    Text: { text: 'Filerobot...' },
    tabs: [TABS.ADJUST, TABS.ANNOTATE, TABS.WATERMARK], // or ['Adjust', 'Annotate', 'Watermark']
    defaultTabId: TABS.ANNOTATE, // or 'Annotate'
    defaultToolId: TOOLS.TEXT, // or 'Text'
};
// Assuming we have a div with id="editor_container"
const filerobotImageEditor = new FilerobotImageEditor(
    document.querySelector('#editor_container'),
    config
);
```
In a HTML page, just this : `<div id="editor_container"></div>`

I have following error : 
```Uncaught TypeError: filerobot_image_editor__WEBPACK_IMPORTED_MODULE_0__.TABS is undefined```

Ok, so i try the same code, without "TABS" (using 'Adjust','Annotate','Watermark', as commented)

I have following error : 
```TypeError: _this$props is undefined```

I don't understand...

Could you help me ?
Thanks

**Comment by AhmeeedMostafa** [comment]
@guillaumecardon you have installed the v3 editor but using the documentation of v4
You should yarn add filerobot-image-editor@beta to install latest beta release as it is the v4 currently as it is not in prod. yet (soon it'll)

**Comment by guillaumecardon** [comment]
Shame on me... You're right, thanks :)
