### ISSUE TITLE
Auto cropping border

### ISSUE THREAD

**Issue by beautyfree** [scaleflex/filerobot-image-editor#16]
Cropping size selection with automatic expansion of the area to the edges of the image

It would be very useful functionality, because constantly expanding the border is very routine

**Comment by beautyfree** [comment]
Property `autoCropArea` in cropperjs

**Comment by dzmitry-stramavus** [comment]
hey @beautyfree ,

Agreed. I'll add the param in next release.

**Comment by AhmeeedMostafa** [comment]
Closing this issue as it has been added with v3.9.3
