### ISSUE TITLE
How to Create Multiple Templates (positioned images & textboxes) via loadableDesignState?

### ISSUE THREAD

**Issue by webdevandeverythingelse** [scaleflex/filerobot-image-editor#160]
Basically, I want to make an "editor" type of app which uses preloaded background images paired with multiple positioned textboxes relative to the background image.

So far, the default template (background image and textboxes) works great - however when I implemented a dropdown to attempt to dynamically change the template, I ran into trouble with the textboxes. The background image updates as expected, however the pushed in changes to override the "annotations" object's properties seem to be ignored - all the same textboxes remain with their same values.

Is it not possible to load in delete or edit "annotations" properties via the loadableDesignState object after the first load?

------------------------------------------------------------------------------------------------
On the dropdown change event, I called this to render the new config object that contains the new background image and the new array of textboxes that match the new background image:
`filerobotImageEditor.render(config2);`

`const config2 = { img: "/some/img/url.png", "annotations": {
        "StreetSuffix": {
            "fill": "#FFFFFF",
            "stroke": "#FFFFFF",
            "strokeWidth": 0,
            "shadowOffsetX": 0,
            "shadowOffsetY": 0,
            "shadowBlur": 0,
            "shadowColor": "#000000",
            "shadowOpacity": 1,
            "opacity": 1,
            "text": "", // Why can't I pass a blank string here and blank out this textbox value set by a previously loaded config?
            "fontFamily": "Arial",
            "fontSize": 60,
            "letterSpacing": 0,
            "lineHeight": 1,
            "align": "center",
            "fontStyle": "normal",
            "name": "Text",
            "id": "Street-Suffix",
            "x": 728.1459872629271,
            "y": 173.37242655193268,
            "width": 90.53377283232143,
            "height": 48.99683092669981,
            "rotation": 0,
            "scaleX": 1,
            "scaleY": 1
        }, }`

**Comment by AhmeeedMostafa** [comment]
@webdevandeverythingelse re-rendering the whole design state is not supported currently only changing the image is supported... we could support it in the future no problems if u need some workaround currently u could remove and reinit the plugin again with the new design state

**Comment by AhmeeedMostafa** [comment]
@webdevandeverythingelse re-rendering the whole design state is applied in the new version check it and let us know if there is any issue
