### ISSUE TITLE
BUG: Rotate after crop doesn't work (and multiple other combinations don't work)

### ISSUE THREAD

**Issue by periman2** [scaleflex/filerobot-image-editor#162]
Whenever I rotate an image after croping it, the downloaded result is not cropped. Same thing happen with the filters. If I add filter and do a rotate + crop, the filter doesn't apply on downloaded image. This bug can be reproduced in every browser on the example that you have in your website and in codesandbox. Generally speaking I've found that the editor selectively adds the edits I'm making to the final result, even thought the preview is being updated perfectly always.

**Comment by AhmeeedMostafa** [comment]
Hello @periman2 currently we are not able to check such issues on v3, as we are focusing v4 maintaining as it'll go to prod. very soon so it's better to start checking v4 or if u think there might be a quick solution for such issue your PR is very welcomed for v3... v4 is more mature than v3 even if it's in BETA release

**Comment by periman2** [comment]
@AhmeeedMostafa Thanks for the quick reply. I had no idea there was a v4 actually. We'll check this one out.
