### ISSUE TITLE
Sanity

### ISSUE THREAD

**Issue by juliusoh** [scaleflex/filerobot-image-editor#164]
Hello
Can I use any method or config to upload to sanity io?
Thanks

**Comment by AhmeeedMostafa** [comment]
Could you please clarify your question as it is not really clear?

**Comment by juliusoh** [comment]
I want to use the "save" method instead of "download" method. How can I use save method to save to my local state in my react component ? It seems like save only works when config is set to config and config contains some key and container ? Is there a way to save to my local state instead or maybe save to sanity io cms ?

**Comment by AhmeeedMostafa** [comment]
If you are talking about v3, it is not possible to have the state of the design in v3
For v4 it's possible to have the state through onSave callback and after that you could pass it to whatever place u want

**Comment by juliusoh** [comment]
Is v4 the beta version ?
I'm not sure why I cannot have a v4 version running Whats the main difference in basic implementation of v4 ?

V3 is straightforward

**Comment by AhmeeedMostafa** [comment]
yes, but it'll go in prod. very soon 
you could check the v4 docs from v4 branch and see the differences
