### ISSUE TITLE
How to resize editor?

### ISSUE THREAD

**Issue by juliusoh** [scaleflex/filerobot-image-editor#167]
Hello is it possible to resize editor? Default size is too small to edit

**Comment by AhmeeedMostafa** [comment]
@juliusoh The plugin respects the container/wrapper HTML element through CSS by having both width & height set 100% so you could change the width/height of the plugin through adding/changing width/height of the wrapper HTML element.

**Comment by juliusoh** [comment]
i did but its still at 1125 x 803 px?

**Comment by tiendd-tmh** [comment]
@juliusoh 

You can try the following if using react:
```
{isImgEditorShown && (
  <div style={{ width: 900, height: 500 }}>
    <FilerobotImageEditor
```

**Comment by AhmeeedMostafa** [comment]
@juliusoh please note that the dimensiosn shown in the topbar are the final image dimensions that'll be saved, not the current dimensions of the previewed canvas, if u followed @tiendd-tmh it'll resize the previewed canvas to 900px width and 500px height but still the topbar's shown dimensions will be the final dimensions

**Comment by juliusoh** [comment]
so i must make the div element bigger?

**Comment by AhmeeedMostafa** [comment]
@juliusoh it depends on your case, if u need the editor to be bigger then u should assign some big dimensions for the container div if u need it smaller then u should assign small dimensions but in both cases the container div dimensions is not related to the topbar dimensions which are the final image dimensions
