### ISSUE TITLE
'FilerobotImageEditor' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by tiendd-tmh** [scaleflex/filerobot-image-editor#168]
I am using `react-filerobot-image-editor` with `typescript` an error occurred. 
How can I fix it?

<img width="680" alt="Screen Shot 2022-03-24 at 08 37 57" src="https://user-images.githubusercontent.com/60589972/159824678-94b37e74-a3b4-4d07-ba03-b451f3847ea4.png">

**Comment by AhmeeedMostafa** [comment]
@tiendd-tmh thanks for reporting, it is going to be considered in the upcoming patch release

**Comment by AhmeeedMostafa** [comment]
@tiendd-tmh please check the new version v4.1.0 should contain a new update for the types

**Comment by tiendd-tmh** [comment]
@AhmeeedMostafa 
It worked. Thank you very much
