### ISSUE TITLE
Round crop

### ISSUE THREAD

**Issue by dmitrykovalevsky89** [scaleflex/filerobot-image-editor#17]
Please, add "Round crop"  to Crop
http://joxi.ru/Vm677POi4Q9102

**Comment by dzmitry-stramavus** [comment]
hey @dmitrykovalevsky89 ,

yep, it's on our roadmap.

**Comment by dzmitry-stramavus** [comment]
hey @dmitrykovalevsky89 ,

it's done in **3.9.2**
![demo-round-crop](https://user-images.githubusercontent.com/10708539/84587115-ba87ca00-ae1c-11ea-8362-f26b24d50e7f.jpg)

**Comment by dmitrykovalevsky89** [comment]
Hi @dzmitry-stramavus !
This is great news!
Thank you!

**Comment by miri-sharf** [comment]
Hey, I would like to know how to configure round crop too.
I want to add some custom ratios, so I won't have the defaults.
Can you help me @dzmitry-stramavus?
