### ISSUE TITLE
How to get blob from onSave()?

### ISSUE THREAD

**Issue by juliusoh** [scaleflex/filerobot-image-editor#170]
![image](https://user-images.githubusercontent.com/63981576/160472643-66aa229c-4d83-44a8-b39c-fadf20f4c1ef.png)

How can I get blob from onSave()? editedImageObject only offers base 64?
And when I convert base64 to blob , it gives me error when setting to React State

**Comment by AhmeeedMostafa** [comment]
u could use `imageCanvas` property it contains the final image canvas so u could apply canvas's method `toBlob` on that property, to know more about toBlob here u are its [docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob)
