### ISSUE TITLE
Error creating crop preset with react-filerobot-image-editor

### ISSUE THREAD

**Issue by tiendd-tmh** [scaleflex/filerobot-image-editor#171]
![Screen Shot 2022-03-29 at 10 07 22](https://user-images.githubusercontent.com/60589972/160525697-eb028f43-14e4-470c-b84a-63a795de4c5a.png)

I got an error when using `presetsItems` in the `Crop` property. In the file `react-filerobot-image-editor/lib/index.d.ts` there is no `presetsItems` in `Crop` (picture below).
![Screen Shot 2022-03-29 at 10 07 33](https://user-images.githubusercontent.com/60589972/160525722-82fa3bf8-6ad3-48a0-a750-b9f077eede7a.png)

How to fix this?

It seems that `toPrecisedFloat` is also unusable. It is not imported from anywhere.

I look forward to an early reply from you. Thank you very much!

**Comment by AhmeeedMostafa** [comment]
@tiendd-tmh please check the new patch version (v4.1.1) it should contain the fix

**Comment by tiendd-tmh** [comment]
@AhmeeedMostafa 
> please check the new patch version (v4.1.1) it should contain the fix

It worked. Thank you very much.

But I want to ask how to use `toPrecisedFloat`? Where is it imported from?
![Screen Shot 2022-03-29 at 16 39 18](https://user-images.githubusercontent.com/60589972/160582614-e130298a-ff6f-43cd-9d28-729c877b400a.png)

**Comment by AhmeeedMostafa** [comment]
`toPrecisedFloat` is a utility function imported internally from 'react-filerobot-imge-editor/lib/utils/toPrecisedFloat' but u don't have to use it, u could either pass the ratio directly or make ur own rounding function as `toPrecisedFloat` that parses the float ratio to fixed number with some precision for avoiding long floating numbers results from ratio

**Comment by tiendd-tmh** [comment]
@AhmeeedMostafa 
I understand. Thank you very much
