### ISSUE TITLE
onSave optional two?

### ISSUE THREAD

**Issue by juliusoh** [scaleflex/filerobot-image-editor#173]
How to use onSave option 2 in react?

**Comment by AhmeeedMostafa** [comment]
I didn't get your question, could u clarify more what do u mean by onSave option 2?
if u meant about the additional save options menu shown besides save button then u mean this (https://github.com/scaleflex/filerobot-image-editor#moresaveoptions)

**Comment by AhmeeedMostafa** [comment]
> in your demo theres two save optional button , 

I have mentioned to the property that will do such operation in my past comment, please recheck it
