### ISSUE TITLE
How to force preset and personalize saving?

### ISSUE THREAD

**Issue by colortips** [scaleflex/filerobot-image-editor#174]
Hi!
I make cropper features for profile pictures.
Is it possible to force the output image (250x250) and png ?
If I'm able to do that, can I skip the pop-up after before saving? and just trigger onSave with the first save button?

**Comment by AhmeeedMostafa** [comment]
Hey, yes all of that is possible
- for making crop area 250x250 only u should provide `minHeight, maxHeight, minWidth, maxWidth` props to [`Crop`](https://github.com/scaleflex/filerobot-image-editor#crop) object with the same value `250` in that case min and max will be `250`

- for forcing the output image to be PNG u should provide the needed extension (png) to [`defaultSavedImageType`](https://github.com/scaleflex/filerobot-image-editor#defaultsavedimagetype) property

- for skipping the default saving modal u should provide [`onBeforeSave`](https://github.com/scaleflex/filerobot-image-editor#onbeforesave) callback function and make it return `false`  to be like `() => false` in that case the default behavior (saving modal) won't triggered and saving will triggered directly with the default & available provided saving options
