### ISSUE TITLE
Can I add an image to the default source, by configuration or otherwise.

### ISSUE THREAD

**Issue by Visoar** [scaleflex/filerobot-image-editor#176]
Can I add an image(maybe as annotate image or watermark image) to the canvas on initialization or afterward through config or some other way.

**Comment by AhmeeedMostafa** [comment]
U could do that through  [`loadableDesignState`](https://github.com/scaleflex/filerobot-image-editor#loadabledesignstate-experimental)

**Comment by Visoar** [comment]
Thank you for your reply. Is there a more detailed document or demo for this method?

**Comment by AhmeeedMostafa** [comment]
Currently, properties details are not available, but it's available through (TS)
also It's the same object u receive from `onSave` callback,  so u could add ur needed watermark and then save and console log the onSave's 2nd argument and check the available properties,

**Comment by Visoar** [comment]
Thanks for the reply. So if I am trying to load an image by default in the edit state and allow the user to resize it or modify it. It looks like this has to be achieved by modifying the source code, is that right.

**Comment by AhmeeedMostafa** [comment]
Not exactly,

here u are more descriptive/exact way u should provide the following object to editor's configurations (we might improve the docs a bit in the future by providing the available properties for that object in the README),

The following object creates a watermark with filerobot's logo img, (Note: the position of the watermark is fixed through x,y we'll improve this in the future to be relative to the original's image, u could receive the  prepared object such as in the example by doing it in the UI and console.log the 2nd argument of onSave function)
![image](https://user-images.githubusercontent.com/22754338/162714091-3befdd5f-6ca3-48b5-bc01-12907371b16a.png)

```js
{
  // ...otherConfigurations
  loadableDesignState: {
    annotations: {
      watermark: {
        stroke: '#000000',
        strokeWidth: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOpacity: 1,
        opacity: 1,
        height: 121.12629375000002,
        width: 115.62055312500001,
        padding: 1,
        image:
          'https://assets.scaleflex.com/Marketing/Logos/Filerobot+Logos/Logo+Vertical/FILEROBOT+LOGO+VERTICAL.png?vh=05c4c3',
        x: 176.6395,
        y: 245.049375,
        id: 'watermark',
        name: 'Image',
      },
    },
  }
}
```

As mentioned, To know all the available properties of [`loadableDesignState`](https://github.com/scaleflex/filerobot-image-editor#loadabledesignstate-experimental) property u should do console.log for the 2nd argument (image's design state) passed in [`onSave`](https://github.com/scaleflex/filerobot-image-editor#onsave) callback , ex.
![Screenshot 2022-04-11 115146](https://user-images.githubusercontent.com/22754338/162714466-0f94e53d-383c-424b-b0c6-1a29ba433e15.png)
 
 
 Hope this was useful

**Comment by Visoar** [comment]
I tried this amazing way and it can meet my needs. thanks.

**Comment by Nisthar** [comment]
@AhmeeedMostafa How do you make the newly added image editable? i can load the image using `loadableDesignState` but it doesn't seems to be editable
