### ISSUE TITLE
Can't save some photo

### ISSUE THREAD

**Issue by Chinh3112** [scaleflex/filerobot-image-editor#179]
I can't save some photo. I also try do it in your website but I also can't save it. 
Please help me. 
https://drive.google.com/file/d/16rGv1kJYo1qu-LJSbH2BsfozK1JX5xEQ/view?usp=sharing
This is my photo I used.

**Comment by AhmeeedMostafa** [comment]
@Chinh3112 what is the issue? everything is working fine, please provide some issue description and production steps and better to provide some video/codesandbox for the issue
