### ISSUE TITLE
Watermark is not applied to the result, when not downloading image.

### ISSUE THREAD

**Issue by ffhakanguenduez** [scaleflex/filerobot-image-editor#18]
After applying a watermark, I fetch the edited image blob from the onComplete prop. Every other change is applied within this blob, but the watermark is missing. Any ideas?

**Comment by dzmitry-stramavus** [comment]
hey @ffhakanguenduez ,

we will check it during the week.

**Comment by dzmitry-stramavus** [comment]
Hey @ffhakanguenduez,

fixed in **v3.4.2**
