### ISSUE TITLE
Save modal text field uneditable when used in modal

### ISSUE THREAD

**Issue by gokulkhatiwada** [scaleflex/filerobot-image-editor#180]
The resize and filename text field are not editable in save modal when editor is in modal.
V 4.1.1 VanillaJS

**Comment by AhmeeedMostafa** [comment]
@gokulkhatiwada could u create & provide some codesandbox that contains your bug to be able to re-produce and check it?

**Comment by gokulkhatiwada** [comment]
I have just copied the config from documentation, sorry I am not good at javascript. 
[Here it is](https://codesandbox.io/s/filerorbot-image-editor-p6cehw?file=/src/index.js:2750-2760)

**Comment by AhmeeedMostafa** [comment]
@gokulkhatiwada thanks, we are checking that and will let u know with the updates in this issue.

**Comment by amrelbialy** [comment]
Hey @gokulkhatiwada, after checking the issue is caused by bootstrap, here the link for the discussion https://github.com/sweetalert2/sweetalert2/issues/374. There is multiple solutions this one worked with me https://github.com/sweetalert2/sweetalert2/issues/374#issuecomment-1008437361

**Comment by gokulkhatiwada** [comment]
@amrelbialy Thank you for the answer

**Comment by jablok1** [comment]
thank you!  I was having the same problem.

**Comment by amolkapadi** [comment]
Removing tabindex="-1" from Modal
