### ISSUE TITLE
Using ellipse with number on Crop ratio property

### ISSUE THREAD

**Issue by eryx16** [scaleflex/filerobot-image-editor#181]
Hi,

I'm trying to create a crop tool that has an oval shape, is it possible to use the ellipse value on Crop's ratio property but still have a number? It's possible to create either a square or rectangle using that property but not sure if that can be combined with ellipse.

Also I can see that the possible values for ratio is either original, ellipse, custom, number.
What values can we use as **custom** for ratio?

Cheers

**Comment by AhmeeedMostafa** [comment]
It is not possible yet to provide both (numbered ratio with ellipse crop type) we might enhance that in the future, 
custom means squared crop area that doesn't relate to a specific ratio (ratio-free crop)

**Comment by eryx16** [comment]
I see, got that. Thanks for the reply.
