### ISSUE TITLE
How to change library styles(css)?

### ISSUE THREAD

**Issue by FilipFomin** [scaleflex/filerobot-image-editor#184]
How can I change styles without recompile lib from source?

**Comment by AhmeeedMostafa** [comment]
If I got youu could provide [`theme's `](https://github.com/scaleflex/filerobot-image-editor#theme) object property or u could use CSS class names

**Comment by FilipFomin** [comment]
Thx, but if with CSS class names.  Where i need to put/write them? And Can i do this without recompile from src? (pliz if this real can you show one example, eny element)

**Comment by AhmeeedMostafa** [comment]
u should put them as normal css styles u have, in your styles files by declaring the styles for the class names
to know the class names for each block/element you could use to inspect element in dev tools and know the classes (u'll find 2 classes 1 dynamic and another static u should use that static one that's prefixed with `FIE_`)
ex.
```js
<html>
  <head>
    <style>
        .FIE_topbar {
           background: rgba(0, 0, 0, 0.15); // changes the background of top bar background
        }
     </style>
  </head>
  <body>
       // Image editor initialization code
  </body>
</html>
```

**Comment by FilipFomin** [comment]
Thx
