### ISSUE TITLE
How to adjust or lock zoom?

### ISSUE THREAD

**Issue by FilipFomin** [scaleflex/filerobot-image-editor#185]
Can I change zoom step size(default 12%) or just block him in all tabs? (react)

**Comment by AhmeeedMostafa** [comment]
I didn't get your question well,
But the default zoom depends on the loaded image dimensions (not fixed default zoom) 
Zoom step from mouse/touch is relative to the wheeling/pitching delta from the top (+/-) buttons are applied with percentage
So no static zoom step and not customizable currently

You could disable the buttons through css or even hide them through css classes

**Comment by FilipFomin** [comment]
Thx, but how disable mouse(scroll)/touch zooming and moving img?

**Comment by AhmeeedMostafa** [comment]
in this version not possible, but it'll be supported through prop in the upcoming versions

**Comment by FilipFomin** [comment]
Thx for great answers and lib^^
