### ISSUE TITLE
how to hide the resolution warning

### ISSUE THREAD

**Issue by jai-sataiva** [scaleflex/filerobot-image-editor#188]
![screencapture-localhost-8000-user-Hey-rendering-2022-04-25-12_17_50](https://user-images.githubusercontent.com/55969709/165035178-2ab11a71-1596-46b3-8ec5-2300e2636e37.png)

hi ,i want to hide that resolution warning

**Comment by AhmeeedMostafa** [comment]
provide a falsy value to [`config.reduceBeforeEdit`]((https://github.com/scaleflex/filerobot-image-editor/tree/v3.12.17#reducebeforeedit-object) property
and I advise you to start checking version 4

**Comment by jai-sataiva** [comment]
thank you for your time ,whenever we use version 4 on class component , it shows error like "cannot call a class as a function" so only we use version 3.12.17

**Comment by jai-sataiva** [comment]
when I start using version 4 it show error like "SecurityError
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.", can you provide me version 4 code sandbox example in react

**Comment by AhmeeedMostafa** [comment]
This is not an editor's issue, but related to disable setting in your browser's settings
check this [doc](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document/#:~:text=and%20Reporting%20Guidelines%20%3E-,Uncaught%20SecurityError%3A%20Failed%20to%20read%20the%20'localStorage'%20property%20from,is%20set%20in%20Content%20Settings.)

**Comment by jai-sataiva** [comment]
![screencapture-codesandbox-io-s-optimistic-archimedes-eb0wim-2022-04-27-10_07_07](https://user-images.githubusercontent.com/55969709/165442675-5097c617-e70c-4d52-a727-b7d50042b53d.png)

i give the image in source but image is not shown in ui

**Comment by AhmeeedMostafa** [comment]
please provide this saved codesandbox to check @jai-sataiva

**Comment by jai-sataiva** [comment]
https://codesandbox.io/s/pensive-sound-x2h5m0?file=/src/App.js

this code taken from https://scaleflex.github.io/filerobot-image-editor/

**Comment by jai-sataiva** [comment]
![screencapture-codesandbox-io-s-pensive-sound-x2h5m0-2022-04-29-16_37_54](https://user-images.githubusercontent.com/55969709/165933372-070d8bbc-6d71-4ccb-80ed-1722a1257e40.png)
the image is undefined in editor

**Comment by AhmeeedMostafa** [comment]
@jai-sataiva that's cause u are using react 18 which is not yet supported from the editor as it's recently released
