### ISSUE TITLE
Error in loading the image with the provided url

### ISSUE THREAD

**Issue by tiendd-tmh** [scaleflex/filerobot-image-editor#189]
I'm having problems displaying images in the editor. When I use:
```html
<img src="https://storage.googleapis.com/xxxxxxxxxx" /> // working
```

But when i use:
```html
<FilerobotImageEditor
    source={"https://storage.googleapis.com/xxxxxxxxxx"} // not working
``` 

It doesn't show the image and shows error:
```
Error in loading the image with the provided url: https://storage.googleapis.com/xxxxxxxxxx
```

What causes it to fail? Please let me know. Thank you so much!

**Comment by AhmeeedMostafa** [comment]
Please provide more info to check about that,
the only expected error that you might have is CORS related error
if your server doesn't support CORS then loading your image from the plugin's side might fail , you could check the  request in browser's network tab in dev tools and check the reason behind the request failing (expected to be CORS)

**Comment by tiendd-tmh** [comment]
@AhmeeedMostafa

> Please provide more info to check about that,
the only expected error that you might have is CORS related error
if your server doesn't support CORS then loading your image from the plugin's side might fail , you could check the request in browser's network tab in dev tools and check the reason behind the request failing (expected to be CORS)

That's a CORS error, thank you. I fixed the error

**Comment by mike-obas** [comment]
Hi,

I'm having the same issue when loading images from google cloud, as well as when trying to write an image to firebase/google cloud storage.

Your help will be greatly appreciated.

**Comment by tiendd-tmh** [comment]
@mike-obas 

If you are using images that load from google cloud. Please use this way to configure cors: https://cloud.google.com/storage/docs/configuring-cors#gsutil

**Comment by mike-obas** [comment]
Hi @tiendd-tmh, thanks very much for your help.

I have used the very configuration and it has fixed it.
