### ISSUE TITLE
Processing overlay doesn't go away

### ISSUE THREAD

**Issue by ZachWhitener** [scaleflex/filerobot-image-editor#19]
While viewing the [codesandbox demo](https://codesandbox.io/s/k3q9vrk707), the "Processing" loading overlay never goes away. This is with the unmodified codesandbox demo, but I'm seeing the same thing in my local version.

<img width="537" alt="Processing overlay" src="https://user-images.githubusercontent.com/12675134/69506206-8e960d00-0efb-11ea-82b1-215cc9660175.png">

**Comment by dzmitry-stramavus** [comment]
hey @ZachWhitener,

updated demo to v3.4.1. I didn't reproduced the bug in the last version
