### ISSUE TITLE
How to listen to click on save

### ISSUE THREAD

**Issue by TukuToi** [scaleflex/filerobot-image-editor#191]
I want to add a spinner or else feedback to the editor which, when we click save, starts spinning and when the AJAX process of uploading the image (I implemented this with jQuery AJAX and PHP) is done, stops spinning.

So logically I assumed, that if you would do this:
`$("#my_spinner").toggleClass('d-none');`
on `onBeforeSave`, it would show my spinner when I click that save button. 
However, It triggered the spinner only much after I clicked save.

So I tried on `onSave`, which still did trigger the spinner much after I click save.

I then went the "dirty" way and did this
```
$( '.FIE_topbar-save-button' ).on('click', function() {
  console.log('clicked');
  $("#my_spinner").toggleClass('d-none');
});
```

And still the spinner, and console log, trigger way after I click save.

I do remove that spinner on AJAX `complete` (also tried on `done()`) and the result is, the spinner shows maybe for 0.1 seconds.

- why does `.on('click',` not trigger immediately when I click on save? It seems there is some form of delay which is unnatural
- IMO triggering the spinner on `onBeforeSave` would be the perfect thing to do, but again, it seems `onBeforeSave ` is much delayed.

What would be the suggested way to show a spinner _precisely the moment when the user clicks "save"_?

Thank you for any hints.

Again, this tool is ... it blows my mind. it is really really cool. Good work.

**Comment by TukuToi** [comment]
Debugging this further, it seems a conflict with Bootstrap.
This:
`$("#my_spinner").attr('class', '');`
removes all classes from that element, unless `d-none`
Yet - that is not the case when we do the same outside the editor's instance...

**Comment by TukuToi** [comment]
Safari. It is always safari

I just noticed, in Chrome you guys already add a spinner!!
So there is no conflict with events or bootstrap, but with safari, because I cannot see the native spinner of file robot in safari either, neither the grey overlay, which is clearly visible in chrome

The browser is updated, latest OS too.

**Comment by AhmeeedMostafa** [comment]
The saving handler is called inside setTimeout for making sure we are showing our loading spinner to the user first and then start saving (for considering low-end devices that might take some time processing the final image better to show loading spinner as better UX) so maybe the delay you are talking about is coming from this side,
anyways we already have our own loading spinner shown so u might start applying your own spinner/loader in `onSave` and it'll be shown directly after finishing the saving process from the editor side and then u should hide it once ur XHR is done.

Otherwise (BEST SOLUTION), we are already supporting possibility to keep our loading spinner shown till you finish some async operation (ex. uploading the file to your server) and then after finishing it'll be hidden (this will be available from our next version that'll be released this week) and will be possible by returning a Promise from your provided [`onSave`](https://github.com/scaleflex/filerobot-image-editor#onsave) callback function

**Comment by TukuToi** [comment]
Yes I have seen that you have your own spinner.
I started adding my own because, in safari, the spinner did not show!

So until I switched to Chrome, I thought there was none.

Of course I am going to use your native one. But, I think on safari it does not work.
I've added a video of the behaviour:
https://user-images.githubusercontent.com/11800236/165116815-fab0dff3-66d7-4480-8c70-5e666962cf70.mov

On chrome, it works just perfect.

Thanks folks!

**Comment by AhmeeedMostafa** [comment]
@TukuToi For safari's issue, could u provide lower `savingPixelRatio` try `3` or `4` I think it would work, the issue might be the amount of memory specified for safari's browser get exceeded with high savingPixelRatio

**Comment by TukuToi** [comment]
That did resolve the issue.

However I had to close the current safari tab and open a new one.

This is odd. While for now I am OK with the solution, I would prefer not to hardcode the pixelRatio. The image is clearly less crisp when using `3`.

Any chance that this can be adjusted in the tool? Or is this some limitation of Safari itself?
I am ok with telling users "if you use safari you won't see a spinner", if that is a "fault" of safari.

Thanks as well for your very speedy interactions. I am truly amazed.

**Comment by AhmeeedMostafa** [comment]
in the upcoming release, the default value will be lowered a bit for avoiding such issue (but still it's some browsers limitations),
Maybe u could look for some workaround/calculations to do from ur integration's side and provide its result as pixelRatio to the editor if u don't want to make it static...

any ways I don't advise you to keep it high (8) as it's in current version as it might cause some issues in firefox browser too
so better to keep it lower


Finally, Per I know it's browser's limitations for memory size no plans for improving this yet, but maybe in the future we would consider improving it if possible

**Comment by TukuToi** [comment]
@AhmeeedMostafa please list this somewhere to fix, I believe this is to be adjusted in the app, not in safari browser, see also https://developer.apple.com/forums/thread/687866
Lowering the default value is not the solution, I just replicated the issue again this time with a value of 3, it just took much longer to happen.

The images edited are not big, below 1k px square actually
Quality is set to 3.

Thank you.

**Comment by TukuToi** [comment]
BTW the solution would probably be to resize the canvas (file robot creates _many_ of those) after usage:
```
$(canvas).each(function(){
    var width = this.width;
    var height = this.height;
    var cont = this.getContext('2d');
    cont && cont.clearRect(0, 0, 1, 1);
});
```

I am not sure how we as users could access all the canvas that FileRobot creates, to do above operation, I think it should be incorporated into the tool, since a single save operation creates about 8 new canvas. And safari keeps them, forever (until session end)
