### ISSUE TITLE
FileRobot or FileRobot Media Asset Widget?

### ISSUE THREAD

**Issue by TukuToi** [scaleflex/filerobot-image-editor#193]
Hi - I keep getting astonished.
I thought "this is a cool image editor". But duh, a _file manager_? 😱 

I spent some hours yesterday integrating FileRobot into my custom File Edit Screens. Then I saw https://www.npmjs.com/package/@filerobot/readme, and I saw that that tool already comes with FileRobot _integrated_!

So now I have a question.
Say I want a full fledged _media_ asset manager (should be capable to upload all types of files basically, and edit those that make sense)
Until now, I have a custom upload and storage system but I edit images with FileRobot.

If I am going to use FileRobot Media Asset Widget, can I just drop the integration for FileRobot itself I made, and simply use FileRobot Media Asset Widget?

I have these 2 screens:
- list of all media. Here the user can see what media they have, click on an "edit" button and a "delete" button. Ideally, of course, here the user also would be able to add media to their library
- when clicking on "edit" they get to a single edit screen of that media item. That is where I integrated FileRobot.

Now - assume I ditch my "media management screen" and use FileRobot Media Asset Widget. Do I _only_ need that Script and can then _manage_ the media in the media management screen with it, and _edit_ the single media still using the same library. Or would I have to integrate both, FileRobot Media Asset Widget and FileRobot?

(I know I can edit in the FileRobot Media Asset Widget directly, but the user might still want to edit the _single_ media in a _single screen_)
Hope that makes sense.

I guess in simple words, I am asking "Is FileRobot Media Asset Widget the full complete thing, while FileRobot itself is only the editor"?

**Comment by TukuToi** [comment]
Uhmmmm, ok so seems the FileRobot Media Asset Widget requires a key which I can only obtain with a paid account?

I guess I got excited too soon haha.
(I am creating a tool that will be used by broad user base, so I cannot put "subscription only" in it, unfortunately)

**Comment by AhmeeedMostafa** [comment]
Well, Filerobot has several DAM products whether integrated together or not,
if you want to know more about Filerobot you could check this: [Scaleflex's Filerobot](https://www.scaleflex.com/en/dam-filerobot)

**Comment by TukuToi** [comment]
Thanks, found that too.
Can you confirm that for the Media Asset Widget we do need a paid license?
See, I am working on a project that will be open source and free for anyone to download and use.
The project includes media management, so I cannot ship it with a paid license :)

Thus just trying to figure out if we can use FileRobot Media Asset Widget _for free_ in a project that potentially will be used by many users, or not.

Thanks!
