### ISSUE TITLE
Possible to initial zoom set 100% and set canvas size dynamically to image size?

### ISSUE THREAD

**Issue by TukuToi** [scaleflex/filerobot-image-editor#194]
Hi, I was skimming through the doc and could not find anything to set these options:

1.  Set initial Zoom % value to 100 instead of 60.
2. Set the canvas size to  a min-width and min-height (as it is natively) but let the height grow, if the image is taller than the canvas.

Does the file robot have options for that?

**Comment by AhmeeedMostafa** [comment]
For 1. no option for setting zoom value yet, (btw. zooming % is relative to your image's dimensions, so 100% doesn't mean the whole image will fit the editor but means the original image's dimensions will be shown in editor so in that case u won't be able to see the whole image in the editor's container (if the original image dimensions are bigger than editor's dimensions) so in your case if 60% was the initial zoom percentage then, 60% is the fitting percentage (shows your whole image in the editor regardless how big its dimensions are)

For 2. You could do that through CSS by assigning your image's height to the canvas or another solution (not sure if it will fit your case or not but u could try) is by using this property [`observePluginContainerSize`](https://github.com/scaleflex/filerobot-image-editor#observeplugincontainersize) or maybe u should mix both of them to achieve what u want

**Comment by TukuToi** [comment]
OK, fair enough.

I have used the CSS to set the editor's container to a certain fixed height for now, works well enough.

Thanks!

**Comment by jwbrown** [comment]
Can you elaborate on how you use CSS to set the editors container size?  I'm mainly a python guy and have not got a clue how to do this....   Thanks in advance
