### ISSUE TITLE
Is there a way that a user can select stroke width and stroke color for the pen?

### ISSUE THREAD

**Issue by OFMaurice** [scaleflex/filerobot-image-editor#198]
I have seen that i can change stroke width and stroke color for the pen via the annotationsCommon during the initialization of the editor. In the UI i don't see any way to change this properties like for e.g. the text (text size, text color).

Do i have to implement custom menu buttons by myself for this? If yes, how can i change the annotationsCommon on the fly after i have instanciated  the FileRobotImageEditor?

**Comment by AhmeeedMostafa** [comment]
There is already an option for that in the UI, the stroke option/icon/panel is responsible about that please recheck.

**Comment by OFMaurice** [comment]
Can you give me an example on how to configure it? Or a link to the part of the documentation where it is explained?

**Comment by OFMaurice** [comment]
It was a bug in my integration. The stroke context menu did not pop up in my UI so i didn't saw the possibility to change the color and the stroke width.
