### ISSUE TITLE
Question: Can we access the operations in the onComplete callback?

### ISSUE THREAD

**Issue by ceetrav** [scaleflex/filerobot-image-editor#20]
Is it possible to access an array of all operations performed on the image within the `onComplete` callback?

**Comment by dzmitry-stramavus** [comment]
hey @ceetrav ,

can u tell us the use case? thx

**Comment by ceetrav** [comment]
To pass the image operations onto other methods, and image manipulation services that support transformations(cloudinary).

**Comment by AhmeeedMostafa** [comment]
@ceetrav this is available now in onSave callback in the v4 that is released in BETA you could check it from [here](https://github.com/scaleflex/filerobot-image-editor/tree/v4)
