### ISSUE TITLE
Error: overriding css

### ISSUE THREAD

**Issue by tiendd-tmh** [scaleflex/filerobot-image-editor#201]
I'm having a css problem
The library css code has overwritten my project. Example:
![Screen Shot 2022-05-13 at 11 11 51](https://user-images.githubusercontent.com/60589972/168210275-03c66621-7ae7-4be4-83d2-a3ddb2c7e746.png)

This problem will cause a lot of repair in my source code. I think there should be a class that covers the css you create
```css
.filerobot-image-editor :not(button) > svg:not([color]) { ... }
```

Is this ok or not? Let me know your opinion. Thank you very much!

**Comment by amrelbialy** [comment]
Hey @tiendd-tmh , yes it is ok and we will fix it in next release

**Comment by AhmeeedMostafa** [comment]
Behaviour is implemented and released for a while.
