### ISSUE TITLE
Unable to download image on Save.

### ISSUE THREAD

**Issue by hafizusman2** [scaleflex/filerobot-image-editor#205]
I am trying to download the image after editing. Unable to do so. Kindly guide. When I click on Save Button, it asks for image name and format, when I click, on download, nothing happens.

**Comment by amrelbialy** [comment]
Hey @hafizusman2, Can you please show a demo?

**Comment by hafizusman2** [comment]
Hi @amrelbialy thank you for responding. 
[https://avac-seller-v2.vercel.app/productlistingeditor](url)
You can check try by adding image on above link. Here is the code that for above deployed link.
`{isImgEditorShown && (
              <FilerobotImageEditorr
                source={URL.createObjectURL(src)}
                theme={theme}
                onSave={(editedImageObject, designState) => {
                  console.log("saved", editedImageObject, designState);
                  closeImgEditor();

                  setImageSrc(null);
                  setErrorFileType(null);
                  setFileName(null);
                }}
                onClose={closeImgEditor}
                annotationsCommon={{
                  fill: "#ff0000",
                }}
                Text={{ text: "Filerobot..." }}
                Crop={{
                  presetsItems: [
                    {
                      titleKey: "classicTv",
                      descriptionKey: "4:3",
                      ratio: 4 / 3,
                      // icon: CropClassicTv, // optional, CropClassicTv is a React Function component. Possible (React Function component, string or HTML Element)
                    },
                    {
                      titleKey: "cinemascope",
                      descriptionKey: "21:9",
                      ratio: 21 / 9,
                      // icon: CropCinemaScope, // optional, CropCinemaScope is a React Function component.  Possible (React Function component, string or HTML Element)
                    },
                  ],
                  presetsFolders: [
                    {
                      titleKey: "socialMedia", // will be translated into Social Media as backend contains this translation key
                      // icon: Social, // optional, Social is a React Function component. Possible (React Function component, string or HTML Element)
                      groups: [
                        {
                          titleKey: "facebook",
                          items: [
                            {
                              titleKey: "profile",
                              width: 180,
                              height: 180,
                              descriptionKey: "fbProfileSize",
                            },
                            {
                              titleKey: "coverPhoto",
                              width: 820,
                              height: 312,
                              descriptionKey: "fbCoverPhotoSize",
                            },
                          ],
                        },
                      ],
                    },
                  ],
                }}
                defaultSavedImageName={fileName}
                tabsIds={[
                  TABS.ADJUST,
                  TABS.ANNOTATE,
                  TABS.WATERMARK,
                  TABS.FILTERS,
                  TABS.FINETUNE,
                  TABS.RESIZE,
                ]} // or {['Adjust', 'Annotate', 'Watermark']}
                // defaultTabId={TABS.ANNOTATE} // or 'Annotate'
                // defaultToolId={TOOLS.TEXT} // or 'Text'
              />
            )}`
I have also attached images. Kindly view them. Kindly also guide how can I download image in webp format. Thanks            
<img width="917" alt="image" src="https://user-images.githubusercontent.com/48489762/170180479-0f482888-a099-4194-b59b-c908345d9535.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/48489762/170180677-c447810a-879c-4914-84cd-3357f2b0dd41.png">

When I press save nothing happers.

**Comment by AhmeeedMostafa** [comment]
@hafizusman2 Nothing happens because you don't do any operations inside `onSave` callback method you are providing in your code,
if u need to download the image then you should do your download operation inside onSave property you are providing to the plugin.
please read the description of [`onSave`](https://github.com/scaleflex/filerobot-image-editor#onsave) property well

**Comment by hafizusman2** [comment]
@AhmeeedMostafa  Thank You for your help. I have managed to download png, jpeg and jpg format successfully. But I am unable to download webp image, nor able to hide. Kindly help me by fixing this issue. Not able to find webp downloader, if not possible then I want to hide webp option.

**Comment by AhmeeedMostafa** [comment]
Here you are this code will download any format
```js
let tmpLink = document.createElement('a');
tmpLink.href = 'IMAGE BASE 64 HERE'
tmpLink.download = 'FILE NAME HERE.webp'
tmpLink.style = 'position: absolute; z-index: -111; visibility: none;';
document.body.appendChild(tmpLink);
tmpLink.click();
document.body.removeChild(tmpLink);
```

**Comment by hafizusman2** [comment]
@AhmeeedMostafa  Thank You so much. It worked.
