### ISSUE TITLE
How to hide draw tools partial?

### ISSUE THREAD

**Issue by QuantumTerrorByte** [scaleflex/filerobot-image-editor#206]
Hello. How can I hide some draw or adjust options/buttons without remove all category? (remove only add text but not add img)

**Comment by amrelbialy** [comment]
Hey @QuantumTerrorByte, unfortunately we don't support hiding specific options

**Comment by vtc-soni** [comment]
Hello @amrelbialy , can I please request a prop to hide tools?

You can introduce a new prop `toolsIds` similar to `tabsIds`. This will give the developer more options to make it flexible based on their requirement.
