### ISSUE TITLE
Can we disable the call to the external API used to translate i18n.ultrafast.io ?

### ISSUE THREAD

**Issue by K20** [scaleflex/filerobot-image-editor#207]
Hello

When file-robot-image-editor.js is loaded, there's a call to an external API (https://github.com/scaleflex/filerobot-image-editor/blob/324569d816d8cd5883371f4e136bca8690183c6a/packages/react-filerobot-image-editor/src/utils/translator.js)

As we work in some secure websites, the fact that an external call is made to translate some text is not appropriate.
Can we disable it easily ?

Best regards

**Comment by amrelbialy** [comment]
Hey @K20, unfortunately we can't disable it because it is responsible for handling all translations. can you please explain more why it causing an issue with some secure websites?

**Comment by amrelbialy** [comment]
Hey @K20, for now you can't disable it but we can add an option in next release

**Comment by K20** [comment]
Hello, while wanting to make a pull request, we found out that there was a setting to disable the backend translations (https://github.com/scaleflex/filerobot-image-editor#user-content-contents) : 

**useBackendTranslations :** 

> A backend service that hosts the translations of the plugin to be able to change the translations without making a new build once the translations changed, and gives the chance to support more languages too, if true the service would be used and the next [language](https://github.com/scaleflex/filerobot-image-editor#language) property used in determining which language to show, false means avoid using this service in that case default [translations](https://github.com/scaleflex/filerobot-image-editor#translations) and provided translations property will be used.

**Comment by K20** [comment]
Also how can we provide you translations ? The defaultTranslation file does not handle other languages.

**Comment by amrelbialy** [comment]
You can provide translations by using https://github.com/scaleflex/filerobot-image-editor#translations, and you should provide translations related to the default language used. ex, if language is french you should provide french translations
