### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by glutaminefree** [scaleflex/filerobot-image-editor#208]
Environment:
 * Fedora 35 x68_64
 * Node 16.14.0
 * npm 8.4.1
 
 I run
 
 `npm install --save filerobot-image-editor --verbose`
 
 and after some output i see endless lines:
 
 
![изображение](https://user-images.githubusercontent.com/2122419/170667930-f69d34e4-35ff-4e42-81d6-d37ccc4e9edf.png)

 and it nevere stops.

**Comment by malu-uiclap** [comment]
I'm having the same problem, both with a Macbook M1 and a ubuntu 22.04 x64.

**Comment by jaykrz** [comment]
I ran into this too. I was able to get around the problem by downgrading npm.

**Comment by amrelbialy** [comment]
Fixed on new release (v4.2.1) please check and let us know
