### ISSUE TITLE
How to add text field by calling API?

### ISSUE THREAD

**Issue by lz1998** [scaleflex/filerobot-image-editor#210]
I want to add some custom buttons. 

When the button is clicked, a text field of `{"text":"hello", "position":{"x":100,"y":100},"rotate":45,"size":"12"}` will be add to the image.

**Comment by AhmeeedMostafa** [comment]
you could provide that through [`loadableDesignState`](https://github.com/scaleflex/filerobot-image-editor#loadabledesignstate-experimental) check how its object looks like (by checking it from `onSave` callback method) and provide your text inside annotations object -- if u have faced some improper behavior please report it as it is experimental feature --
