### ISSUE TITLE
Fill

### ISSUE THREAD

**Issue by KenRandall** [scaleflex/filerobot-image-editor#213]
Is there any way to select fill an area with a different color?

**Comment by AhmeeedMostafa** [comment]
Sorry could you please re-phrase your question and provide some example more provide more details as I didn't get u well!

**Comment by KenRandall** [comment]
The equivalent of fill with color in Windows Paint.

**Comment by AhmeeedMostafa** [comment]
It is not possible, let us know your use case and if it'll be useful to add in the editor we might consider it.

**Comment by zhouhuiquan** [comment]
I think what he is saying is that the fill color of the text and the fill color of the rectangular frame can be set to be different, so that text marks and rectangular marks can be better realized
We want too
