### ISSUE TITLE
[BUG]the watermark offset x and y is not correct

### ISSUE THREAD

**Issue by geosmart** [scaleflex/filerobot-image-editor#215]
in the file robot editor
* user can change the watermark width/height by resize.
* user can change the original image width/height by zoom in or out.
* so how to calculate  the watermark x,y ?

I measure the watermark's  x  with a screenshoot tool，
but the value is not equal the `designState.annotations.watermark.x` in the file robot editor.

## left value is not right
![3](https://user-images.githubusercontent.com/3156608/172047241-b07cfd11-a5e9-4f81-886f-70f633f816b0.jpg)

## top value is not right
![bug3](https://user-images.githubusercontent.com/3156608/172048167-d95a2737-c5ac-4396-8481-5fc2b9311644.jpg)

I was so confused ，I do a lot test and juest can't calculate the right left and top value of the watermark.

and sometimes I found  the x and y is out of box, x is greater than image width , y is greater than image height
![watermark](https://user-images.githubusercontent.com/3156608/172033283-b3a3a722-2a9c-4d30-b510-a6c47bfb234e.jpg)

**Comment by geosmart** [comment]
@ahmeeedkhallaf  file robot editor is a great tool ,  someone  need your help

**Comment by AhmeeedMostafa** [comment]
@geosmart screenshot tool won't calculate the accurate x,y positions cause we are doing some calculations depending on the original image, zooming ratio and watermark scaling
is there a reason behind calculating the x,y by ur self?

**Comment by geosmart** [comment]
I need save the source image's watermark A(400*400)’s  x,y and zoom scale .

when I change to use  another watermark B(400*800) ，render it  to the watermark A's location with same size

**Comment by AhmeeedMostafa** [comment]
@geosmart this is possible only through the output object u receive on saving or on trying to get the image data through [`getCurrentImgDataFnRef`](https://github.com/scaleflex/filerobot-image-editor#getcurrentimgdatafnref) prop but it might not be that accurate yet as there should be some improvements for such functionality
