### ISSUE TITLE
Not working with image 50x50

### ISSUE THREAD

**Issue by tiendd-tmh** [scaleflex/filerobot-image-editor#220]
When I use the image with the size 50x50, it seems that the gallery has an error
Please check this out. Thank you!

![Screen Shot 2022-06-09 at 09 56 00](https://user-images.githubusercontent.com/60589972/172754510-a689b26b-fe03-44a1-b0bf-b8725fb620d7.png)

**Comment by amrelbialy** [comment]
Thanks for reporting

**Comment by acealbastoni** [comment]
why is the resulting values are not correct???? 
     console.log(designState.adjustments.crop.x);
     console.log(designState.adjustments.crop.y);

**Comment by AhmeeedMostafa** [comment]
The issue is fixed in version 4.3.8, please re-check it and let us know if all is good.
