### ISSUE TITLE
How to edit/override the Editor's CSS

### ISSUE THREAD

**Issue by vsaini-speedum** [scaleflex/filerobot-image-editor#222]
Hey, 

I am looking for some help on how I can edit CSS for the image editor, for example: Hide button or components (hide reset operations buttons or image pixel size ), increase button size/ button text size ... something along these line.

Thank you

**Comment by amrelbialy** [comment]
Hey @vsaini-speedum, here a link to the same issue https://github.com/scaleflex/filerobot-image-editor/issues/184
