### ISSUE TITLE
Cors Error logging while using CDN version

### ISSUE THREAD

**Issue by mike-obas** [scaleflex/filerobot-image-editor#225]
Hi,

Your product is super amazing, but the CDN version keeps logging CORS error. I would have used the REACT version, but it does not yet support REACT 18.

Thanks in anticipation for your help.

**Comment by mike-obas** [comment]
The error occurs when I try to load image from firebase storage or when I try to write an image into firebase storage.

**Comment by amrelbialy** [comment]
Hey @mike-obas, can you please create a codesandbox to be able to check this issue

**Comment by mike-obas** [comment]
Hi @amrelbialy, thanks alot for reaching out. 

I have been able to solve the issue from the solution posted here: https://stackoverflow.com/questions/71193348/firebase-storage-access-to-fetch-at-has-been-blocked-by-cors-policy-no-ac

Thanks once again for making and publishing such an amazing library.
