### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by damiano216** [scaleflex/filerobot-image-editor#228]
Hi,
I am trying to add the react module on my nextjs project by importing it as suggested on the GitHub readme:
import FilerobotImageEditor, {
  TABS,
  TOOLS,
} from "react-filerobot-image-editor";

But at build time I get the error: 
**SyntaxError: Cannot use import statement outside a module.**

I added  "type": "module" to my package.json as suggested online but it did not solve the issue.
Does someone know how to get over this? 🤔

**Comment by ProgaPanda** [comment]
The library doesn't seem to support nextjs.. I tried a lot of workarounds and it still doesn't work. 
I hope someone from the team helps.

**Comment by amrelbialy** [comment]
@damiano216  Can you please create a sandbox to able to see the issue, and also what version of next.js you are using?

**Comment by choudhary-ankit** [comment]
@damiano216 import dynamic in next.js project, its work for me.
e.g: const FilerobotImageEditor = dynamic(() => import('react-filerobot-image-editor'), {ssr: false});

**Comment by choudhary-ankit** [comment]
same issue occurs during build, any solution

**Comment by ProgaPanda** [comment]
> same issue occurs during build, any solution
> 
> 

Can you share a codesandbox with a basic nextjs project importing the lib. For the maintainers to check the issue..

**Comment by usamamashkoor** [comment]
@damiano216 Thanks, I have implemented your solution, The editor works correctly in the `npm run dev` server but when I run `npm run build` and then run `npm start` then the editor loads and after loading the editor height keeps getting increased the height is getting increased on this element `konvajs-content` 

Can you please let me know, If it is working for you, and how did you integrate it into Next.js?
