### ISSUE TITLE
How to remove save modal?

### ISSUE THREAD

**Issue by juliusoh** [scaleflex/filerobot-image-editor#230]
Hello after user clicks save
I want to remove the modal

 I already did by

```
      <FilerobotImageEditor
        source={imageData}
        onSave={(editedImageObject, designState) =>
          console.log("saved", editedImageObject, designState)
        }
        onBeforeSave={false as any}
```

but this modal still shows up

![image](https://user-images.githubusercontent.com/63981576/178188446-5bf66f1c-52a6-4cea-8021-b406104e3f2e.png)

**Comment by amrelbialy** [comment]
Hey @juliusoh, you should fire onBeforeSave as a function 
onBeforeSave={()=>false}

**Comment by juliusoh** [comment]
@amrelbialy This only disables the save button functionality, is there a way to hide this "save" button?

**Comment by MerijnCanvas** [comment]
@juliusoh You can just hide it with CSS 
`.FIE_topbar-save-button {
    display: none;
}`
