### ISSUE TITLE
Remove options from annotation

### ISSUE THREAD

**Issue by rferreira98** [scaleflex/filerobot-image-editor#232]
Is it possible to remove options from annotations tool? For example just have the image option.

**Comment by dimascrocco** [comment]
A quick and dirty :B way to obtain this behavior, you could do something like this using CSS magic:

`
.FIE_blur-tool-button {
 display: none !important;
}

.FIE_warmth-tool-button {
 display: none !important;
}

.FIE_hue-option-wrapper {
 display: none !important;
}
`

**Comment by amrelbialy** [comment]
Hey @rferreira98, for now it isn't possible
