### ISSUE TITLE
getCurrentImgDataFnRef for TypeScript

### ISSUE THREAD

**Issue by juliusoh** [scaleflex/filerobot-image-editor#236]
I want to get latest image data state without clicking save button

```
`  const editedImage =
    useRef<
      (
        imageFileInfo?: object,
        pixelRatio?: boolean,
        keepLoadingSpinnerShown?: boolean,
      ) => { imageData: object; designState: object; hideLoadingSpinner: (...args: any[]) => any }
    >();

  const { current: saveFunction } = editedImage;
  const handleEditedImage = async () => {
    if (!saveFunction) return;
    const result = await saveFunction();
    console.log("saveFunction", result);
    setFinalImageData(result.imageData);
  };`
```
When I call handleEditedImage() from another component, it doesnt trigger until couple times... what am I doing wrong?

**Comment by amrelbialy** [comment]
Hey @juliusoh, Can you please show an example in sandbox to be able to help

**Comment by juliusoh** [comment]
``@amrelbialy 

Right now I am getting the most recent stage of image that is currently being edited without user clicking save button by

this object in editor 
`getCurrentImgDataFnRef={editedImage}`

And then accessing current object from useRef, is this the correct implementation?

`  const editedImage =
    useRef<
      (
        imageFileInfo?: object,
        pixelRatio?: boolean,
        keepLoadingSpinnerShown?: boolean,
      ) => { imageData: object; designState: object; hideLoadingSpinner: (...args: any[]) => any }
    >();

  const { current: saveFunction } = editedImage;
  const handleEditedImage = async () => {
    console.log("Before save function", saveFunction);
    if (!saveFunction) return;
    const result = await saveFunction();
    console.log("saveFunction", result);
    // setFinalImageData(result.imageData);
    retu`
