### ISSUE TITLE
CDN Cors errors

### ISSUE THREAD

**Issue by dmitrykovalevsky89** [scaleflex/filerobot-image-editor#24]
Hi!
You have a great product. Thanks!

But we have problem after switching to cdn.
Server has Access-Control-Allow-Origin: *

Safari browser:
Unable to get image data from canvas because the canvas has been tainted by cross-origin data.
SecurityError: The operation is insecure.

How do you solve this problem with your cdn?

**Comment by dzmitry-stramavus** [comment]
hey @dmitrykovalevsky89 ,

should be fixed in **3.6.1**

**Comment by dzmitry-stramavus** [comment]
@dmitrykovalevsky89 , tell me if it works well now for you

**Comment by dmitrykovalevsky89** [comment]
@dzmitry-stramavus Very good! It works! Thanks!
