### ISSUE TITLE
Saving Image?

### ISSUE THREAD

**Issue by charleslcso** [scaleflex/filerobot-image-editor#243]
The Save image function doesn't seem to work. No image is being saved.

No error in console too.

![Screenshot 2022-08-03 at 7 18 27 PM](https://user-images.githubusercontent.com/520537/182595561-15190a54-2cd2-471e-8d06-a34b278aa3a5.JPG)

What could I be missing please?

**Comment by 500Foods** [comment]
Don't know why they haven't put this in the example code yet, but you can try updating the onSave function in the config parameters to include actually saving the image by doing something like this.

    onSave: (editedImageObject, designState) => { 
      console.log('saved', editedImageObject, designState) 
      var tmpLink = document.createElement('a'); 
      tmpLink.href = editedImageObject.imageBase64; 
      tmpLink.download = editedImageObject.fullName; 
      tmpLink.style = 'position: absolute; z-index: -111; visibility: none;'; 
      document.body.appendChild(tmpLink); 
      tmpLink.click(); 
      document.body.removeChild(tmpLink); 
      tmpLink = null; 
    }
