### ISSUE TITLE
how create custom button to add image 

### ISSUE THREAD

**Issue by AlDiAlisel** [scaleflex/filerobot-image-editor#247]
Hi, I have created a sidebar with some images and I want to click to add this image in the editor, how can I do it,
I have read the document and i try but unsuccessful

**Comment by AlDiAlisel** [comment]
I solved in this way, if someone have a better way share please. 
newImmage is an image clicked on left sidebar 

    useEffect(()=>{
      if(newImage) {
        let date = Date.now()
        let upgrade = anno;
        upgrade.annotations[`Image-${date}`] = { 
        id: `Image-${date}`,       
        stroke: '#000000',
        strokeWidth: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOpacity: 1,
        opacity: 1,
        height: 121.12629375000002,
        width: 115.62055312500001,
        padding: 1,
        image:newImage,
        x: 82,
        y: 9,
        name: 'Image',
      }
        closeImgEditor()
        setAnno(upgrade)
        setTimeout(() => {
          setIsImgEditorShown(true);
        }, 150);
      }
    },[newImage])

**Comment by SaraZoarob** [comment]
hi @AlDiAlisel unfortunately we don't support uploading images, if you question is not about that please clarify more
