### ISSUE TITLE
Issues with firebase image url

### ISSUE THREAD

**Issue by FaranMustafa** [scaleflex/filerobot-image-editor#248]
when passing firebase image url sometimes image doesn't load and when it get loaded gives error on adjust tab
<img width="500" alt="Screenshot 2022-08-11 at 10 23 23 PM" src="https://user-images.githubusercontent.com/51854189/184195186-3e2d6e90-1eef-426b-879a-0286f8f394bd.png">

**Comment by SaraZoarob** [comment]
hello @FaranMustafa, can you please attach the image's url, show codesandbox or demo?
