### ISSUE TITLE
How to enable number input in save image window

### ISSUE THREAD

**Issue by havasjeancarlostrabajo** [scaleflex/filerobot-image-editor#249]
A cordial greeting. I would like to allow the user to modify the height or width in the save window, but it does not allow me since the number type inputs are blocked

![image](https://user-images.githubusercontent.com/96260366/184256474-370c3010-91b2-4393-94d4-b09b37224641.png)

**Comment by SaraZoarob** [comment]
hi @havasjeancarlostrabajo, this is added now in current release, please check

**Comment by havasjeancarlostrabajo** [comment]
> 

Kind regards, I just updated the library.

but even the fields are locked, which does not allow manually adding the width and height, when you click save


![image](https://user-images.githubusercontent.com/96260366/200053521-a031e370-6ffd-4f0b-b5a3-ecaee3cd24af.png)


![image](https://user-images.githubusercontent.com/96260366/200053578-e1b8a1d4-3f39-48c0-bd9c-872d82bc4f3d.png)

**Comment by AhmeeedMostafa** [comment]
@havasjeancarlostrabajo it works fine, u could try it on our demo page if u still face such an issue please add codesandbox produces the issue
Please note that in ur screenshot the original image size is different than the size in the inputs which means they are already changed
