### ISSUE TITLE
Change image on real time - "resize"

### ISSUE THREAD

**Issue by dmitrykovalevsky89** [scaleflex/filerobot-image-editor#25]
If I resized the image, then I will see the result only after saving
http://joxi.ru/MAjll4yIj79BMm

The image should change with resizing in the settings window
http://joxi.ru/gmvgg40CqNaK72

It will be very cool!

**Comment by dzmitry-stramavus** [comment]
hey @dmitrykovalevsky89 , thx for checking it out. Resize is something we cannot really see. For example if an image is 4000px and we resize to 2000px but our browser window is 800px => we will not see the difference anyway. We could add something like real time preview for resize and show zoom info, but I don't think it's important for now.

**Comment by dmitrykovalevsky89** [comment]
@dzmitry-stramavus Thanks
