### ISSUE TITLE
Rename Image  

### ISSUE THREAD

**Issue by FaranMustafa** [scaleflex/filerobot-image-editor#250]
<img width="340" alt="Screenshot 2022-08-15 at 9 50 14 PM" src="https://user-images.githubusercontent.com/51854189/184679121-00034234-041a-4630-b7e1-2dd600af3af2.png">
Not able to rename the Image after editing in the save prompt

**Comment by SaraZoarob** [comment]
hello @FaranMustafa, this is fixed in current release, please check
