### ISSUE TITLE
Filters list do not preserve image ratio

### ISSUE THREAD

**Issue by skjnldsv** [scaleflex/filerobot-image-editor#253]
![image](https://user-images.githubusercontent.com/14975046/185113430-93fa700a-1a53-4f12-bd74-0f5e901c27ba.png)

It seems the canva size is capped https://github.com/scaleflex/filerobot-image-editor/blob/e1fb6f0b467f0fafffaae56f471cb03a9b5eb580/packages/react-filerobot-image-editor/src/components/tools/Filters/FilterItem.jsx#L13-L14
Maybe it will be worth using a square canvas and containing the image  within?

Or use the current image ratio. Might be a bit more tricky if the user edit the image size/crops the image

## Context
Using latest `filerobot-image-editor version@^4.3.1`

**Comment by AhmeeedMostafa** [comment]
The upcoming release is considered a new behavior

**Comment by AhmeeedMostafa** [comment]
The issue is improved in version 4.3.8, please re-check it and let us know if all is good.

**Comment by skjnldsv** [comment]
@AhmeeedMostafa where is the commit that fixes this?

I am still experiencing the same issue
![image](https://user-images.githubusercontent.com/14975046/222915460-6de3648e-8834-499e-92b9-b4c850bbcbfe.png)

**Comment by AhmeeedMostafa** [comment]
@skjnldsv  the issue is fixed, here u are a screenshot for a vertical image from the current demo page, please make sure that u are using the latest version (the new behavior is we are covering the filter item with the image keeping its ratio)
![image](https://user-images.githubusercontent.com/22754338/223458114-5f6e8e12-d46f-47d7-b133-d771e80f9cf4.png)

**Comment by skjnldsv** [comment]
@AhmeeedMostafa 
https://github.com/scaleflex/filerobot-image-editor/blob/bf2b7bbb4f90c23bcdf323ee54e9b7f24c865f8b/packages/filerobot-image-editor/package.json#L37

**Comment by skjnldsv** [comment]
@AhmeeedMostafa maybe creating pull requests instead of pushing to master would allow other contributors like us to review and catch those mistakes? :)
We'd be happy to help in the future! :+1:

**Comment by skjnldsv** [comment]
Btw, on another note, can you explain the reasoning behind choosing a rendering ratio of 60x45 ?
Since you took the cropping approach, using a square would be more fitting from a UX perspective imho :)

See:
| Google Photos | OneDrive |
|:---------:|:------:|
|![image](https://user-images.githubusercontent.com/14975046/223470061-05771048-4cba-48bc-9ef0-c09474630928.png)|![image](https://user-images.githubusercontent.com/14975046/223469908-89868a78-c86c-4570-8792-f4c08d4f6f42.png)|

**Comment by AhmeeedMostafa** [comment]
@skjnldsv it is peer dependency not dependency, u should update it in ur project locally by installing the proper version for `react-filerobot-image-editor` the version u installed will be used, and for sure we welcome any PR that will be proper to merge.

for the filter size, It's a perspective from our UX team, but my POV it has more benefits than making it 45x45 as at least it will be useful for landscape to show the whole image if it's landscape and it is not good to increase the height more than that .

**Comment by skjnldsv** [comment]
> @skjnldsv it is peer dependency not dependency, u should update it in ur project locally by installing the proper version for `react-filerobot-image-editor` the version u installed will be used, and for sure we welcome any PR that will be proper to merge.

Yes, but peer dependencies still show which version is being used for a specific package.
With [npm 7 and above](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies), you don't have to install peer dependencies. Npm will automatically do that and rely on the package peerDep to know which version to install.

Currently, if you only install `filerobot-image-editor`, npm will not fetch `react-filerobot-image-editor@4.3.8`, but `4.3.7`
While the `^` is used and should imply that the patch version can change, npm will not see it like that.

I still think this should be addressed and fixed on release :)

1. https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

**Comment by skjnldsv** [comment]
Closing as the cropping is working now! Thanks again for the hard work @AhmeeedMostafa ! :tada:

**Comment by AhmeeedMostafa** [comment]
> > @skjnldsv it is peer dependency not dependency, u should update it in ur project locally by installing the proper version for `react-filerobot-image-editor` the version u installed will be used, and for sure we welcome any PR that will be proper to merge.
> 
> Yes, but peer dependencies still show which version is being used for a specific package. With [npm 7 and above](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies), you don't have to install peer dependencies. Npm will automatically do that and rely on the package peerDep to know which version to install.
> 
> Currently, if you only install `filerobot-image-editor`, npm will not fetch `react-filerobot-image-editor@4.3.8`, but `4.3.7` While the `^` is used and should imply that the patch version can change, npm does not seem to see it like that. ([nor does dependabot](https://github.com/nextcloud/viewer/pull/1547/files))
> 
> I still think this should be addressed and fixed on release :)

I'm aware that the new version of npm is doing that, but we are already mentioning  in the docs the developer should install the `react-filerobot-image-editor` by himself,  so if he did that by himself he will install the proper version, the peerDependency for defining the minimum required version to have functionalities work fine, last but not least I agree with the point of (^) that npm should care for it if it's going to install the peer dependency automatically.

so finally I see the peer dependency should be as it's currently & I don't think it's a bug , it's just about developer's implementation & notices. and let's see maybe we would have better idea/consideration for that in the future.

**Comment by skjnldsv** [comment]
Thank you for taking the time to clarify Ahmed :)
