### ISSUE TITLE
[Question] Ability to remove some functionality

### ISSUE THREAD

**Issue by LaplacesCat** [scaleflex/filerobot-image-editor#256]
Hi,
Is there a way we could remove the "Show Original image" button,
![image](https://user-images.githubusercontent.com/60594105/186675616-428cea7c-277c-41ab-afd4-31f7d6a52722.png)
or any of the tools (such as Pen, Line and Arrow)?
![image](https://user-images.githubusercontent.com/60594105/186675734-bb648a28-9fa8-4826-890b-44ca9b2edc91.png)

Would there also be a way to limit the number of times someone can upload an image?

**Comment by emmachuche** [comment]
i have same question

**Comment by luvenan** [comment]
Yes, is this possible?

**Comment by SaraZoarob** [comment]
hi @LaplacesCat, @emmachuche and @luvenan, unfortunately we don't support this

**Comment by AhmeeedMostafa** [comment]
@all, No specific props for removing that button/tool yet, but u could remove it or any of the tools' buttons using CSS classes as a workaround solution
