### ISSUE TITLE
Auto watermark resize

### ISSUE THREAD

**Issue by hammerhog** [scaleflex/filerobot-image-editor#258]
I need the watermark to be a consistent and set size instead of having the user size it. So if they pick a specific resize for an image the watermark resizes accordingly and can't be changed. I'd like its opacity to be at 50% too. Can anyone please help me? I've been trying to figure out a way for over a week. :-)

**Comment by SaraZoarob** [comment]
hi @hammerhog Unfortunately we don't support this currently
