### ISSUE TITLE
Grey line on the top, bottom left or right side after image cropping

### ISSUE THREAD

**Issue by yloskat** [scaleflex/filerobot-image-editor#260]
Steps to reproduce:
1. Load image with white background
2. Crop image
3. Save image

Expected result: there are no borders or extra lines
Actual result: grey line appears on the top, bottom, left or right side of the image. Example: https://ibb.co/RpQsRZN

Environment:
Vivaldi 5.3.2679.68 (also reproduces in Chrome 105)
Windows 10
Display scale: 150%

**Comment by SaraZoarob** [comment]
hi @yloskat we will check and get back to you

**Comment by AhmeeedMostafa** [comment]
@yloskat it is not reproducible please provide a codesandbox with the code that produces the issue

**Comment by sumshare** [comment]
![Image](https://github.com/user-attachments/assets/dcd04445-d0dc-45d9-820c-db1a6382e3ac)  There are transparent lines on the right side and bottom in png
