### ISSUE TITLE
Memory leak while editing 4k pictures 

### ISSUE THREAD

**Issue by eledim** [scaleflex/filerobot-image-editor#262]
consume 400MB memory when every picture opened，it may result in chrome label thread crash.

env:win11 chrome/edge

**Comment by SaraZoarob** [comment]
hello @eledim, can you please add code example like with codesandbox and attach the image's url

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
