### ISSUE TITLE
If this plugin is not freely available for commercial use, why have you labeled it as MIT licensed 

### ISSUE THREAD

**Issue by ashok-damani** [scaleflex/filerobot-image-editor#264]
If this plugin is not freely available for commercial use, why have you labeled it as MIT licensed. Please clarify whether I can use it in my commercial web application for free?

Thanks,
Ashok

**Comment by SaraZoarob** [comment]
hello @ashok-damani, this plugin is free to use and you can use it
on the other hand, if you want to use our Filerobot Media Asset on your website, you'll need to subscribe to the service
you can check the demo for Filerobot [from here](https://scaleflex.cloudimg.io/v7/plugins/filerobot-widget/demo/index.html?vh=d6c246&func=proxy)

**Comment by amrelbialy** [comment]
Hey @ashok-damani , for now it is still under MIT License. But we are planning soon to change it and to have new license

**Comment by luvenan** [comment]
Sorry, where does it say it is not freely available for commercial use?

**Comment by brianteeman** [comment]
Until 10 days ago the licence read as follows (you can confirm in the commit log)

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
to use the Software without restriction for **personal purposes only.** If you intend to use, copy, modify, distribute, sell, or lease any part of our Software for commercial or corporate purposes, 
you are required to contact the Scaleflex Sales team (sales@scaleflex.com) to settle the payment of a yearly licensing subscription of **five thousand euros.**
If you are proven to be in violation of this condition, you agree to pay a **ten thousand euro penalty charge** in addition to the yearly licensing subscription.

**Comment by amrelbialy** [comment]
We reverted this commit as it was a mistake. We are still discussing what will happen with the license and will inform here as soon as we decide.

**Comment by brianteeman** [comment]
The code released under the current MIT licence can always be used. It cannot be retroactively changed
