### ISSUE TITLE
Bug with nodes changing color on selection

### ISSUE THREAD

**Issue by QuantumTerrorByte** [scaleflex/filerobot-image-editor#271]
Hello, help me please.
Nodes, when selected, change their color to the one in the tools (5-10% probability).
If you create several same-type, multi-colored figures and select them one by one, bug preproducing even more often (10-20% probability).
I suppose this is due to the start of creating a node from the global event listener for creating nodes (it triggers before the node is selected and forwards the event further, which catches the node).
How can I fix this issue?(any advise)

**Comment by AhmeeedMostafa** [comment]
Sorry but the issue is re-producible from our side, please create a codesandbox that enables the issue production or provide a video showcases the issue

**Comment by QuantumTerrorByte** [comment]
[https://fex.net/s/cbrvoab](url)
Sorry for the quality. But the error should be visible. Well, at the end, the problem with debouncers is also visible.
P.S. If the editor's work is a little slower, the problem will appear much more often.

**Comment by QuantumTerrorByte** [comment]
This issue can be fixed by increase debounce time for tempAnnoUpd.
![image](https://user-images.githubusercontent.com/79018130/199880066-ae34fb6a-3d68-4200-b467-a535073bdd46.png).
And another one issue: 
https://fex.net/s/xax6czk
Can be fixed by increase debounce time for dispatching SELECT_ANNOTATION.
![image](https://user-images.githubusercontent.com/79018130/199883010-4b9904b9-79ef-429a-be65-7559517b0b23.png).
