### ISSUE TITLE
Is there a way to add multiple watermarks?

### ISSUE THREAD

**Issue by adyzz1** [scaleflex/filerobot-image-editor#272]
Is there a way to add multiple watermarks?
I'd like to print out several watermarks that I entered in advance without uploading.
If possible, it would be very good to use as an icon or emoticon insertion function.

**Comment by AhmeeedMostafa** [comment]
The use-case you are talking about isn't a watermark so we don't have a useful use-case to enable possibility to add multiple watermarks, in the future we might consider a tool for adding emojis
