### ISSUE TITLE
Q: How to set theme's `zIndex` values?

### ISSUE THREAD

**Issue by jacksleight** [scaleflex/filerobot-image-editor#278]
I'm sure I'm just doing something wrong here, but I'm trying to integrate the editor into an application that uses some very high z-index values, and need to override the editor's values so the modals/popovers etc. appear on top. However when I set them they don't seem to change. This is my config:

```js
const config = {
    source: this.source,
    theme: {
        zIndex: {
            mobileStepper: 11000,
            speedDial: 11050,
            appBar: 11100,
            drawer: 11200,
            modal: 11300,
            snackbar: 11400,
            tooltip: 11500
        },
    },
};
this.editor = new window.FilerobotImageEditor(this.container, config);
```

When I inspect the elements the default z-indexes are still being used. I'm using the CDN version if that makes any difference.

**Comment by AhmeeedMostafa** [comment]
Hey @jacksleight, the zIndex is related to the internal components of the design library sfx/ui but we are not using all the components from their so by changing them it might give u the results u want and might not.
It's better to use class name of the element that u want to assign it a different `z-index`.

- or a better suggestion should give it a try which might work (not sure) u could create 2 child wrapper divs both of them have `position: relative` with 2 `z-index` values, the wrapper with fewer `z-index` should contain the editor and the 2nd wrapper with higher `z-index` should contain your (appear on top elements).

the idea behind that solution is to create a different stacking context.

let me know if it works with u.

**Comment by jacksleight** [comment]
Hi @AhmeeedMostafa, thank you for the suggestions!

> u could create 2 child wrapper divs both of them have position: relative with 2 z-index values, the wrapper with fewer z-index should contain the editor and the 2nd wrapper with higher z-index should contain your (appear on top elements).

I can fix the index of the main editor by placing it in a container div and setting a `z-index` on that as suggested. The problem I’m having is that the modals (eg. save dialog) and popovers (eg. crop preset menu) aren't added to that element, they're always appended to the `body`. I can’t see a way to get them to be appended to another element where I could control the `z-index`.

> It's better to use class name of the element that u want to assign it a different z-index.

This mostly works 👍 . I’ve added the CSS below to target those elements and they now appear correctly, I do still have an issue with popovers inside popovers (eg. colour palette) but hopefully I can figure something out.

```css
.SfxModal-Wrapper {
    z-index: 20001 !important;
}
.SfxPopper-wrapper {
    z-index: 20002 !important;
}
```

**Comment by amrelbialy** [comment]
Hey @jacksleight, About updating zIndex through @sfx/ui theme. We don't support this yet but we can consider it in the future
