### ISSUE TITLE
Images src with query parameters not always loaded

### ISSUE THREAD

**Issue by DCrusher** [scaleflex/filerobot-image-editor#28]
When you try to set a link to a picture that has query parameters, the editor cannot load it.

For example "https://ru.gravatar.com/userimage/52160824/b8521a4b87f8dae053ed378ee6ed5b76.jpg?size=200"

And it seems that problem is that the editor adds a timestamp to the end of the URL: 
https://ru.gravatar.com/userimage/52160824/b8521a4b87f8dae053ed378ee6ed5b76.jpg?size=200?1579009880820

Library version 3.6.3

**Comment by dzmitry-stramavus** [comment]
hey @DCrusher ,

**fixed in 3.6.6**
