### ISSUE TITLE
Stroke colour picker also change fill colour

### ISSUE THREAD

**Issue by XplicitKiD** [scaleflex/filerobot-image-editor#285]
There is a bug found on Draw Section while using the demo, the stroke color picker also changes the color of the fill color,

step to produce : 
1- choose different colors for the stroke and fill
2 - draw any shape,
3- click outside of the canvas / change the draw tool 
it changes the color of the fill

**Comment by terrychua93** [comment]
![image-editor](https://user-images.githubusercontent.com/71627870/208396990-02af62e5-1de8-4125-9235-27cc7e9e698e.png)

this from component/common/colorInput/index.jsx

Just hide that code should work

**Comment by AhmeeedMostafa** [comment]
Thanks for noticing we would check this in the future and consider it if it's a real bug.

**Comment by AhmeeedMostafa** [comment]
The issue is improved in version 4.3.8, please re-check it and let us know if all is good.

**Comment by XplicitKiD** [comment]
Thanks for the update. the issue has been fixed
