### ISSUE TITLE
How can I overwrite download button?

### ISSUE THREAD

**Issue by daustany** [scaleflex/filerobot-image-editor#29]
I need get the Base64 string of the image instead of download the physical file,
how can access to returned value of rendered image ?

**Comment by dzmitry-stramavus** [comment]
hey @daustany ,

check this https://github.com/scaleflex/filerobot-image-editor/issues/6

and to get base64 from canvas you can use the following method

```canvas.toDataURL(type, encoderOptions);```

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
