### ISSUE TITLE
Reverting pen many times creates error

### ISSUE THREAD

**Issue by HimonRana** [scaleflex/filerobot-image-editor#294]
This happens when reverting(back button) pen a few times.

![image](https://user-images.githubusercontent.com/31616276/211282995-603ba047-8943-415a-bbb2-2a95a5bdb2b4.png)

**Comment by AhmeeedMostafa** [comment]
Could u clarify more?
Do u mean it happens on drawing multiple shapes using a pen and then clicking undo multiple times?

**Comment by HimonRana** [comment]
After using the pen multiple times and then try to revert all one at a time creates the error,

**Comment by AhmeeedMostafa** [comment]
@HimonRana We'll check it and make sure if such a behaviour happens or not, if it is we will consider its fix in the upcoming releases once we have enough time...
thanks for reporting!

**Comment by AhmeeedMostafa** [comment]
@HimonRana after deeply checking the issue is not re-producible, please provide a codesandbox with your code that produces that error
