### ISSUE TITLE
white background stock image

### ISSUE THREAD

**Issue by karkir0003** [scaleflex/filerobot-image-editor#296]
I want to modify the "source" element in the FIleRobot React js component to use a standard white "stock image" so that people who upload their own image can make the edits they want without having to edit on top of the base "source image". Can you please help resolve this issue or put out a quick fix? My development team would be eternally grateful :)

**Comment by Dashrekker** [comment]
![image](https://user-images.githubusercontent.com/47958374/213959647-5bedbc5f-19d8-485e-ab3c-bba4dc6569d1.png)
![image](https://user-images.githubusercontent.com/47958374/213959692-485bc0ff-46cd-4d48-a820-0850f2811507.png)
attempting to load an image locally or from a url have both raised errors

**Comment by karkir0003** [comment]
@dzmitry-stramavus

**Comment by karkir0003** [comment]
@ahmeeedkhallaf

**Comment by Dashrekker** [comment]
![image](https://user-images.githubusercontent.com/47958374/213961036-7aa36625-f68b-47c1-a082-5abcb2f78c56.png)
I also ran into this white screen of death issue where I can't upload or change anything. I used this url: https://cdn-icons-png.flaticon.com/512/126/126477.png. The weird thing is that it worked at first until I refreshed the page.

**Comment by AhmeeedMostafa** [comment]
Could u please clarify what do u mean exactly by some example as it is not that clear for me ?
@karkir0003

**Comment by AhmeeedMostafa** [comment]
@Dashrekker we already have a current open issue for that but we still have no time yet to check and fix it, we will check and consider it once we have time
#276

**Comment by karkir0003** [comment]
The example @Dashrekker gave is what I was referring to

**Comment by AhmeeedMostafa** [comment]
@karkir0003 so u mean to have a white image and user does his modifications over it? Ex. For drawing annotations maybe?

**Comment by karkir0003** [comment]
yes

**Comment by AhmeeedMostafa** [comment]
Okay then u need to provide the `source` prop for a white image and it'll do the trick

**Comment by karkir0003** [comment]
can you provide example code where this fix is implemented with a working white background image?

**Comment by karkir0003** [comment]
could you then provide me an example of a white image that will work? @AhmeeedMostafa

**Comment by AhmeeedMostafa** [comment]
@karkir0003 [React Example](https://github.com/scaleflex/filerobot-image-editor#react-example)

Replace the source with ur white image
