### ISSUE TITLE
How get object json and restore it?

### ISSUE THREAD

**Issue by aloisogomes** [scaleflex/filerobot-image-editor#30]
There are any way to get current object properties? Like images, filters, positions, etc... For future usage, think about restore it from a database for continous adjusts.

So, is possible get them all?

**Comment by dzmitry-stramavus** [comment]
hey @aloisogomes , it's not possible for now, but we are going to add it in next releases.

**Comment by rajeshpanda** [comment]
any updates on this?

**Comment by azakero** [comment]
any updates on this? (2)

**Comment by imdkbj** [comment]
Hey! Is this method exposed as seems many small version has been released since then. Pls update.

**Comment by AhmeeedMostafa** [comment]
@aloisogomes @rajeshpanda @azakero @imdkbj This is become available in the new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) which released in BETA now, under property `loadableDesignState` but it the property is experimental so we would love to hear your feedback through opening proper issues to improve it!
