### ISSUE TITLE
Remove selection when using tools.

### ISSUE THREAD

**Issue by HimonRana** [scaleflex/filerobot-image-editor#304]
Is there any way you can remove the selection when using any tool e.g. after using pen you get a blue dotted selection which you can move it or adjust size with. My use case is when drawing/writing someting fast if you "lift" the pen it goes to selection mode but i want to keep drawing. It should be made possible to remove the selection on any tool.

And if i need to remove what i've drawn i can use the revert/undo buttons.

![image](https://user-images.githubusercontent.com/31616276/220341645-61dbee66-10ca-4e92-8cba-030345c3baf7.png)

**Comment by AhmeeedMostafa** [comment]
we would have a look into this and if such behavior's enhancement is better than current we will consider it
