### ISSUE TITLE
Undo and reset button trigger validation on page

### ISSUE THREAD

**Issue by sunilyadav778111** [scaleflex/filerobot-image-editor#305]
Undo and reset button trigger validation on page

**Comment by AhmeeedMostafa** [comment]
sorry, ur issue is not clear could u clarify it more with some video/codesandbox/screenshot and how to exactly produce it?

**Comment by Zedash** [comment]
I've had the same behavior, if we add the plugin to a form and we don't check that the submitted button is the one we want to use to send our form, then our form is sent if we click on one of the plugin's submit buttons.

So it's important to check the origin of the "submit" event to avoid unwanted form submission.

I hope I've made myself clear.
