### ISSUE TITLE
Image quality deteriorates when resolution is changed (retina)

### ISSUE THREAD

**Issue by dmitrykovalevsky89** [scaleflex/filerobot-image-editor#31]
Download image 1000x1000px
http://joxi.ru/52aYY7aUEnGGl2

Replace resolution with 300x300px
http://joxi.ru/823ppPaF9O66KA

As a result, the image becomes “soapy”. This is clearly visible on the retina screen.
On your example:
1820x1215 - https://scaleflex.cloudimg.io/v7/https://scaleflex.airstore.io/demo/stephen-walker-unsplash.jpg?w=1820&h=1215
500x333 - https://scaleflex.cloudimg.io/v7/https://scaleflex.airstore.io/demo/stephen-walker-unsplash.jpg?w=500&h=333.79120879120876

**Comment by dzmitry-stramavus** [comment]
hey @dmitrykovalevsky89 , but it's how it should be

for example:

we have div with 500x500 px, and we have image inside 500x500 px. If I see it on retina screen it will look "soapy" as it should be x2 => 1000x1000 px. That's what you see with 1000x1000px and 300x300px in your examples. if you put the same image in div which is twice less for 300x300 px image you have 150x150 px div it'll look the same when you check image 1000x1000 px in 500x500px div. Let me know if I'm wrong :)

**Comment by dmitrykovalevsky89** [comment]
Hey Dzmitry!
But I have doubts. When resizing, you may have quality <1

For a more correct spelling of the question, I used an image not large (not @2x), so that it would be displayed completely in the rector block (not narrowed)
Is it possible to make this parameter quality so that we can regulate it ourselves?

**Comment by dzmitry-stramavus** [comment]
we don't compress or apply other manipulation. So, the quality should be the same. I checked images, and I don't see any artifacts. Pls, provide a good example to see the difference. Thx

**Comment by dmitrykovalevsky89** [comment]
This image 1000x1000px
https://firebirdsql.org/file/about/firebird-logo-1000.png
Download it and resize to 400pixels
on retin
and see how it becomes not clear
Thanks

**Comment by dmitrykovalevsky89** [comment]
Hi, Dmitry!
This image https://dropmefiles.com/Jvkrc
Origin size 504  x  476 - http://joxi.ru/Rmzkk40CYlJqJ2
After edit to 130 x 122 - http://joxi.ru/EA4vvPRFo9GLzm
The quality is greatly lost (very noticeable in the inscription BARASH)
What you think about it?
Maybe there will be some opportunity to indicate that this is a retina (retina: true)?

**Comment by dzmitry-stramavus** [comment]
hi @dmitrykovalevsky89 ,

yes, I saw that there is some noticeable quality loss. I'll check it, but not sure how to fix it yet.

>>> And element with id="preview-img-box" - width / 2
great idea!

**Comment by AhmeeedMostafa** [comment]
@dmitrykovalevsky89 please consider checking the new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) released in BETA now, if u still face same problem you could re-open the issue and we'd love to hear your feedback!
