### ISSUE TITLE
Features Request and Pull Request

### ISSUE THREAD

**Issue by juanRabaa** [scaleflex/filerobot-image-editor#315]
I had to develop the following features for a project. If you are intersted at all, I can clean in up and make a PR

- Stickers (images URLs passed through prop).
- Photo overlay as a guide that doesn't get saved in the final image (image URL passed through prop).
- Hide save button.

Another one that I didn't do but would like to see made is an API for creation of new tools (in the source code), and custom tools (passed as prop to the component). From what I saw in the source code, it's not that easy to add a new tool.

**Comment by AhmeeedMostafa** [comment]
We are welcome to your contribution for sure, once u finish and clean it up please make a PR to check it as it needs to follow our current code base and the design should be aligned too.

For supporting custom tools, it's in the plan but it is a bit hard for the current architecture to consider it, so it will get considered in the new major version as it might include architecture change

**Comment by adammesa** [comment]
Would love to see this!

**Comment by juanRabaa** [comment]
@AhmeeedMostafa 
> For photo overlay guide (not sure exactly what u mean by this feature and the usecase of it) , is it a background behind the picture being edited?

Yes exactly. Maybe it is something way to specific of my project and not needed in the library. In this project, the user had to choose a design that would be projected on top of a car, and would draw or add stickers to it. We needed to add the car outline (top and side view) on top of the design choosed to let the user know where they should draw or put the stickers, because not all of the designs ends up in the car. This outline wouldn't not be shown in the final result once saved.

![Background Overlay](https://user-images.githubusercontent.com/28640722/228010614-e8a3729c-4b05-45b2-9b9a-7be221d32604.jpg)
