### ISSUE TITLE
Text/arrows outside the image

### ISSUE THREAD

**Issue by dimcsEfisco** [scaleflex/filerobot-image-editor#318]
Is there the ability to add text or draw arrows outside the image?
<img width="689" alt="Screenshot at Mar 24 15-51-54" src="https://user-images.githubusercontent.com/62011964/227539900-a42e4f4f-9a5b-4c84-a7aa-0a59a553b43d.png">

**Comment by AhmeeedMostafa** [comment]
Nope, it is not possible

**Comment by dimcsEfisco** [comment]
> Nope, it is not possible

ok, thanks
