### ISSUE TITLE
[nextjs] Throws css imported by dependancy error

### ISSUE THREAD

**Issue by gondar00** [scaleflex/filerobot-image-editor#32]
When i try to use the file upload plugin with next i receive the following error in the dev console

> Possible Ways to Fix It
Reach out to the maintainer and ask for them to publish a compiled version of their dependency.

https://github.com/zeit/next.js/blob/master/errors/css-npm.md

It's caused by line https://github.com/scaleflex/filerobot-image-editor/blob/master/projects/react/ImageEditorWrapper.js#L7

What is the most optimal fix for the above??

**Comment by vaniyokk** [comment]
Same question!

**Comment by mrgrotts** [comment]
Looks like the package isn't using [webpack v4's file-loader](https://webpack.js.org/loaders/file-loader/).

**Comment by magicspon** [comment]
Any movement on this?

**Comment by mrgrotts** [comment]
I tried getting this to work with a forked repo but the problem might be more complicated than simply the import. 

I removed the problematic CSS import from ImageEditorWrapper.js, rebuilt the editor and instead imported the CSS file in _app.js directly as NPM describes, but this leads to new problems.

For one, this library uses a styled-components plugin called `quickbaseoss/babel-plugin-styled-components-css-namespace` that namespaces classes for the editor. This broke my own styled-components configuration and Next - I had to remove my own plugins and stick with the standard .babelrc configuration recommended by styled-components for Next. 

From there, the issue I have not yet resolved is with the icons. If I am understanding the code correctly, it boils down to the following screenshot: 

![filerobot-next-fork-bug](https://user-images.githubusercontent.com/23294567/112741233-6aac6680-8f49-11eb-8371-c4ce563b5842.png)

My Chrome DevTools has my cursor highlighting the entire row of icons in the Toolbar. I focused on 2 icons to illustrate what's going on, but this obviously applies to all of them. 

I've annotated the classnames assigned to each icon as well as the ::before pseudo element responsible for rendering it, and circled the relevant styling. The icon styles are overwriting each other a new type of icon gets renderered.

For additional reference, here are the relevant styled-components component and helpers:

[/src/styledComponents/Toolbar.ui.js:](https://github.com/scaleflex/filerobot-image-editor/blob/master/src/styledComponents/Toolbar.ui.js)
```
const ToolIcon = styled.div`
  height: 40px;
  font-size: 40px;
  
  ${props => getIconStyles(props)};
  ${props => getIconByName(props.name)};
`;
```

[/src/styledComponents/styleUtils.js:](https://github.com/scaleflex/filerobot-image-editor/blob/master/src/styledComponents/styleUtils.js)
```
function getIconStyles(props) {
  return `
    font-family: 'filerobot-image-editor-font' !important;
    color: ${props.muted ? props.theme.colors.textMute : props.theme.colors.text};
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;

    /* Better Font Rendering =========== */
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;

    &:hover {
      color: ${props.muted ? props.theme.colors.textMute : props.theme.colors.text};
    }
  `;
}

function getIconByName(name) {
  let char = '';

  switch (name) {
    case 'watermark':
      char = '\\e918';
      break;
    case 'reset':
      char = '\\e912';
      break;
    case 'flip-v':
      char = '\\e916';
      break;
    case 'flip-h':
      char = '\\e914';
      break;
    case 'cross':
      char = '\\e90c';
      break;
    case 'effects':
      char = '\\e900';
      break;
    case 'filters':
      char = '\\e904';
      break;
    case 'adjust':
      char = '\\e90a';
      break;
    case 'crop':
      char = '\\e901';
      break;
    case 'resize':
      char = '\\e907';
      break;
    case 'rotate':
      char = '\\e90b';
      break;
    case 'previous':
      char = '\\e905';
      break;
    case 'next':
      char = '\\e906';
      break;
    case 'ratio':
      char = '\\e90e';
      break;
    case 'no-ratio':
      char = '\\e90f';
      break;
    case 'left-rotate':
      char = '\\e902';
      break;
    case 'right-rotate':
      char = '\\e908';
      break;
    case 'focus_point':
      char = '\\e919';
      break;
    case 'shapes':
      char = '\\e91b';
      break;
    case 'image':
      char = '\\e91a';
      break;
    case 'text':
      char = 'T';
      break;
    case 'full-screen':
      char = '\\e91c';
      break;
    default:
      return;
  }

  return `
    &:before {
      content: '${char}'
    }
  `;
}
```

Hope this research helps and crossing my fingers that this can be resolved.

**Comment by mrgrotts** [comment]
I was able to get this working by forking the repo, removing the imported CSS file from ImageEditorWrapper.js, rebuilding and publishing a private version for myself, and then importing the CSS file in `_app.js` as follows:

`import "MY_FORKED_FILEROBOT_PACKAGE/dist/assets/fonts/filerobot-font.css"'

This should work for create-react-app as well, or any webpack configuration that enables file imports.

**Comment by odegraciajr** [comment]
> I was able to get this working by forking the repo, removing the imported CSS file from ImageEditorWrapper.js, rebuilding and publishing a private version for myself, and then importing the CSS file in `_app.js` as follows:
> 
> `import 'FORKED/dist/assets/fonts/filerobot-font.css'`
> 
> This should work for create-react-app as well, or any webpack configuration that enables file imports.

How did you build the fork? is `npm run build-new`? I'm having an issue on building the package i'm always getting `CanvasRenderingContext2D is not defined` error

**Comment by mrgrotts** [comment]
@odegraciajr, I actually found [an even better solution](https://github.com/vercel/next.js/issues/12079) :)

Using the webpack configuration below - which is from the bottom of this thread - allows you to use filerobot directly with NextJS. One note, if you use styled-components in your app, you will get warnings about different versions unless you use the version that they are also using.

```
const removeIssuerApp = issuer => !issuer || !issuer.length ? [] : issuer.filter(i => i.substr(-7) !== '_app.js')

module.exports = {
  webpack (config, options) {
    config.module.rules = config.module.rules.map(
      rule => !rule.oneOf ? rule : ({
        ...rule,
        oneOf: rule.oneOf.map(oneOf => {
          if (!(oneOf.test && oneOf.issuer && (oneOf.test.toString() === '/(?<!\\.module)\\.(scss|sass)$/' || oneOf.test.toString() === '/(?<!\\.module)\\.css$/'))) {
            return oneOf
          }
          const
            and = removeIssuerApp(oneOf.issuer.and),
            or = removeIssuerApp(oneOf.issuer.or),
            not = oneOf.issuer.not || []
          return {
            ...oneOf,
            issuer: !and.length && !or.length && !not.length ? undefined : Object.assign({}, !and.length ? null : {and}, !or.length ? null : {or}, !not.length ? null : {not},)
          }
        })
      })
    )
    return config
  }
}
```
