### ISSUE TITLE
How can I modify the button styles and icons as well as the layout of the photo editor...?

### ISSUE THREAD

**Issue by devmuhammadasad** [scaleflex/filerobot-image-editor#320]
I am trying to customize the styles and icons of buttons in my project. Can anyone provide guidance on how to achieve this? Additionally, I am also interested in changing the layout of the editor to match the one in the screenshot. Any tips or resources would be greatly appreciated.

**Comment by AhmeeedMostafa** [comment]
for icon not possible, u could only change/override the styles of the button through using the static css class (u could inspect element any of the buttons and check the static classname available and use it)
or provide `theme` object that will care for ur provided colors.
