### ISSUE TITLE
openai generated images are not loaded into the editor because of cors

### ISSUE THREAD

**Issue by lee-1980** [scaleflex/filerobot-image-editor#321]
I generated the images using openai rest API and got image urls.
Then I run the following
filerobotImageEditor.render({ source: imageSrc }); // here imageSRC is the url which openai provided through API response.
the example of link: 

https://oaidalleapiprodscus.blob.core.windows.net/private/org-xqSQYoy9kZhqeGVec8T6bnWc/user-WJmbxvywHB1nICuacJEZypA9/img-hmDW8JBCBxgbq5ETSb0M0ISx.png?st=2023-03-27T22%3A04%3A54Z&se=2023-03-28T00%3A04%3A54Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-03-27T20%3A33%3A48Z&ske=2023-03-28T20%3A33%3A48Z&sks=b&skv=2021-08-06&sig=FIXtpVIg0cwyaOCVwaWWZS6TGPdkVR7F9GKGwOVzGks%3D

I can see this image in my browser. Image link is valid for 2 hours once it is generated.

But image editor can't load the image because of cors.

Any idea to resolve this cors issue by image editor configuration or customization?

**Comment by DongJu-Na** [comment]
Did you close the issue because the problem was solved? I'm curious how you solved it.
