### ISSUE TITLE
Unhandled Runtime Error: TypeError: Cannot read properties of undefined (reading 'setAttrs')

### ISSUE THREAD

**Issue by olehgowombat** [scaleflex/filerobot-image-editor#322]
This issue happens when user tries to save/close (basically any unmount of Image Editor component) with active text change area (text was typed, but not applied)
![image](https://user-images.githubusercontent.com/96909859/228747128-7885550c-238a-414a-a8e9-8ce076173d1e.png)

I've also tried react example from here -> https://scaleflex.github.io/filerobot-image-editor/ and it causes the same page crash.

**Comment by AhmeeedMostafa** [comment]
Could u please provide exactly the production steps as it is not clear from what u have mentioned

**Comment by olehgowombat** [comment]
[386bfd7d-6a20-467a-bf61-86317674b751.webm](https://user-images.githubusercontent.com/96909859/229082196-f4603f73-2f65-41fd-8a0b-f3a96a515927.webm)
The same happens for my project, when I try to save/close with the same steps as on the video above.
@AhmeeedMostafa

**Comment by olehgowombat** [comment]
Any updates when this one will be released?

**Comment by AhmeeedMostafa** [comment]
@olehgowombat no data is determined yet, but it is considered in the next release stay tuned.
