### ISSUE TITLE
I want to change Tab Labels and change the button style and position

### ISSUE THREAD

**Issue by lee-1980** [scaleflex/filerobot-image-editor#325]
I want to customize some labels and CSS in this library. Is it possible to edit them inside the min.js which is built already?

Can we change ‘Adjust’ Tab Label to ‘Adjust Size’
Can we change 'Resize' Tab Label to ‘manual resize’ 

I want to move bar (custom/rotate/flip x/flip y) at bottom to top of images - can’t see it on standard display settings

![image](https://user-images.githubusercontent.com/63563638/229564274-ae69e171-5b0f-4f73-8b24-655dde6f89ec.png)

Thank you. this image tool is really great.

**Comment by AhmeeedMostafa** [comment]
u could use this property [`translations`](https://github.com/scaleflex/filerobot-image-editor#translations) for changing the labels, for the styling u could use the static css class names (u could find them by inspecting the HTML element)
but for moving the bar to the top isn't possible.

**Comment by lee-1980** [comment]
Thanks for your quick response. Will you consider this bar position option in the configuration setting in the further version?
Maybe in theme property
barPostion: Top | Bottom | Left | right

If I change the source code myself and compile it using webpack again, what should I do?
Sorry I am NodeJS beginner and I am new to CLI to use Webpack and other package libraries
Can you give me any hints to use this source code to build the minimized JS?

**Comment by AhmeeedMostafa** [comment]
for the bar position we don't have any intent about adding such configuration yet,

for building the plugin after doing ur changes run `yarn build:js-bundle` and `dist` folder will be generated contains the minimized js version

**Comment by lee-1980** [comment]
Thank you so much Really appreciate your help.
