### ISSUE TITLE
Zooming in/out in Adjust tab.

### ISSUE THREAD

**Issue by lee-1980** [scaleflex/filerobot-image-editor#327]
I am trying to implement Zooming in/out inside Adjust tab, rather than zooming in Resize tab separately.
Can it be done?

Currently cropping size(height or width) can't be bigger than the image size(width/height).
for example: in case of landscape cropping, Cropper width can't be bigger than image width.

Is it possible to make the crop size flexible and enable zoom in the adjustment tab without being limited by the image size?
Is it possible to fill the area outside the image inside the crop tool with blank pixels if the crop size is larger than the image size?

**Comment by AhmeeedMostafa** [comment]
It's possible for sure if u have investigated the project and implemented it, but it will take a lot of time from u, cause there are a lot of cases depending on each other in editor's architecture as the editor provides live preview/render for most of the changes

But applying it from our side is not a focus and an important usecase for the objective of the editor currently
