### ISSUE TITLE
Can I resize modal mode to full-screen mode ?

### ISSUE THREAD

**Issue by thanhhoa214** [scaleflex/filerobot-image-editor#33]
Hello there, I really want to use all features of package. It's great. But in another way, fixing the editor's size it not suitable in my situation. I do not only read all document but also brooding your codes line by line.

Any ideal to fix it, make it more flexible. Hope to be helped 👍👍 Many thanks ❤

**Comment by dzmitry-stramavus** [comment]
hey @thanhhoa214 , it's a good feature request. We will add it to our next release

**Comment by thanhhoa214** [comment]
hope to see it soon!

**Comment by thanhhoa214** [comment]
# Toolbar Bug when you "Apply" 
- **Target**: Effects or all Toolbar items. 
- **Description**: Effects apply on image but Toolbar state did not update. So the next time if you want to reset only that effect seemly impossible.
- **Attached**: I reproduce it in ZIP file.


Check it & hope Team fix it
It's great to hear some good news whenever releases new upgrade!

**Comment by dzmitry-stramavus** [comment]
hey @thanhhoa214 ,

it's available form **3.9.0**

![image](https://user-images.githubusercontent.com/10708539/84506992-71bafe80-acc0-11ea-9982-3c82fd1a4262.png)
