### ISSUE TITLE
how to change font size?

### ISSUE THREAD

**Issue by AElgamal5** [scaleflex/filerobot-image-editor#332]

**Comment by AhmeeedMostafa** [comment]
@AElgamal5 which font size exactly??

**Comment by AElgamal5** [comment]
increasing sizes of all fonts if possible

**Comment by AhmeeedMostafa** [comment]
it is possible to change through css (u should use the static css class) screenshot as a prove!
![image](https://user-images.githubusercontent.com/22754338/232323373-322e1512-c0b1-4870-9cdc-dd3c76002172.png)

**Comment by thijs-qv** [comment]
This works when decreasing the fontSize, but when increasing it eventually the text gets cut off. Is there any easy way to make the buttons and ui elements a bit bigger? Or will I have to manually adjust all the values?
