### ISSUE TITLE
Zooming image via mousewheel -> image not centered

### ISSUE THREAD

**Issue by OFMaurice** [scaleflex/filerobot-image-editor#337]
If i zoom the image on the demo page via mousewheel the image is not always centered correctly

-> Zooming via "+/-" buttons works well

![image](https://user-images.githubusercontent.com/39367315/234885515-105a485f-4528-4215-babd-b08b3044757c.png)

**Comment by AhmeeedMostafa** [comment]
mouse wheel works depending on the position of ur cursor, so it is not required to always have it centered it depends on the ur cursor's position (it will get centered only if the preview image fits or smaller than the container)
