### ISSUE TITLE
Can you point me please to a branch that implements the experimental "Export current design state"?

### ISSUE THREAD

**Issue by pushqin** [scaleflex/filerobot-image-editor#339]

**Comment by AhmeeedMostafa** [comment]
Do u mean an example  implementation or the functionality code implementation itself?

**Comment by pushqin** [comment]
If you have example of usage it will be great, that way i can get to the source code as well. If you don't have then just the location of the implementation in the source code.

**Comment by AhmeeedMostafa** [comment]
this would be useful for u [`useTransformedImgData.js hook`](https://github.com/scaleflex/filerobot-image-editor/blob/master/packages/react-filerobot-image-editor/src/hooks/useTransformedImgData.js)
