### ISSUE TITLE
Specified theme typography is been overridden on certain ui elements

### ISSUE THREAD

**Issue by ymor** [scaleflex/filerobot-image-editor#340]
Codesandbox: 
https://codesandbox.io/s/frosty-grothendieck-4n8non?file=/src/index.js

I chose a ridiculous font to make the issue more obvious.  But some controls are re-applying roboto as the font family i.e  Save button, Font dropdown, Add Image.

**Comment by AhmeeedMostafa** [comment]
@ymor thanks for reporting we'll report the issue for the UI team to fix it, thanks!

**Comment by johnsutor** [comment]
Any update on this/ways I can contribute?

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
