### ISSUE TITLE
How to hide Save button and access image when using as a component inside Blazor?

### ISSUE THREAD

**Issue by davorkomusanac** [scaleflex/filerobot-image-editor#342]
Hi, I like your library, I only have a small problem.

So I am trying to implement the image editor inside my Blazor application, so I am using the npm version 4.3.7. 
My problem is that basically I want to allow the user to rotate his image and for it to be automatically saved without the user needing to press the button. 

I have a different button on the whole page which handles saving all the changes, so I don't want to make the user press save twice to achieve the same process.

I have checked the documentation and found the "getCurrentImgDataFnRef" property, but I am honestly not really sure how to use it? I don't see an example for it's use case? 

Also, how would I be able to actually hide the save button? I see that inside the DeveloperTools the save button has some CSS which I could perhaps use to hide it, but I am not sure how can I access it programatically inside my code since it is part of the library?

Thank you.

**Comment by AhmeeedMostafa** [comment]
- for hiding the button u could use css for now
- to be able to save the rotation without clicking save button, u should use the function assigned for the ref provided to this property `getCurrentImgDataFnRef` whenever u want to get the latest/current image data ... so if u want to get the image data once the user click ur save button (not the editor's one) then call that function once the user press ur button (but in that case u shouldn't close the editor before having the image data from the function)

**Comment by davorkomusanac** [comment]
Great, thank you, managed to do it.
