### ISSUE TITLE
Save/restore image editor settings

### ISSUE THREAD

**Issue by mykyta-bakirov** [scaleflex/filerobot-image-editor#343]
I'm wondering how can I save/restore user preferences in filerobot image editor? Let’s say a user has changed a color or stroke width in editor and draw couple figures, after that he closes the application. On the next app startup he wants to have his last color and stroke width set by default. In the documentation I did not find any event or callback about changes in the editor, the only thing I see is onModify which is triggered when the user applies some changes to the picture. But what about the editor settings change event?

**Comment by AhmeeedMostafa** [comment]
Well, it is not a big focus in the aim of the product currently,
as a workaround u could achieve this by having the latest shape's color, stroke...etc. (whatver options u need to save) once the user is saving the image, and keep them in the user's local storage... then on initializing the editor , provide the user's configurations that are saved in local storage to the editor through the annotations common options or if u need for some specific annotation.

**Comment by artemkamyshenkov** [comment]
> Well, it is not a big focus in the aim of the product currently, as a workaround u could achieve this by having the latest shape's color, stroke...etc. (whatver options u need to save) once the user is saving the image, and keep them in the user's local storage... then on initializing the editor , provide the user's configurations that are saved in local storage to the editor through the annotations common options or if u need for some specific annotation.

Hi! If I have shape data, can I somehow add a shape automatically when loading the editor?

const shape = {
  cornerRadius: 0,
  fill: '#00000000',
  height: 96.03492617404363,
  id: 'Rect-893182412429',
  name: 'Rect',
  opacity: 1,
  shadowBlur: 0,
  shadowColor: '#000000',
  shadowOffsetX: 0,
  shadowOffsetY: 0,
  shadowOpacity: 1,
  stroke: '#000000',
  strokeWidth: 3,
  width: 82.02983277366229,
  x: 131.88833804856435,
  y: 81.94531837267907,
};
