### ISSUE TITLE
Resizing is not taken into account when using getCurrentImgDataFnRef

### ISSUE THREAD

**Issue by jducro** [scaleflex/filerobot-image-editor#344]
As our ui requires a different save button, we are using :
```
editorInstance().imageData.imageBase64;
```
With editorInstance being the ref provided by `getCurrentImgDataFnRef`.

However after a resize the imageData is not affected at all by the resize.

Is that a bug or do we missing some configuration to get the resized image from that ref?

Thanks a lot.

**Comment by AhmeeedMostafa** [comment]
could u please explain more ur steps as they are not pretty clear for me?
u should call the function that has been assigned in ur provided ref whenever u need the current image data.
the returned image data from that function are the same data provided on clicking save normally.

**Comment by jducro** [comment]
Current image data is working for everything except the resizing. `imageBase64` seems unaffected by the resizing.

**Comment by jducro** [comment]
Here's a sandbox of what I'm facing: 
https://codesandbox.io/s/cool-sunset-zshw6l?file=/src/App.tsx 
If you do a resize and press the save button I added, the original size is showing. `imageData` from that ref is unaffected by resizing.

**Comment by AhmeeedMostafa** [comment]
@jducro clear now, seems a bug... fixed and will be considered in the upcoming release.

**Comment by jducro** [comment]
Thanks @AhmeeedMostafa ! Do you have an ETA on the next release?

**Comment by AhmeeedMostafa** [comment]
It is released @jducro
