### ISSUE TITLE
define preset of specific colors instead of a color picker 

### ISSUE THREAD

**Issue by rainabozhi** [scaleflex/filerobot-image-editor#348]
Dear scaleflex team, 

first of all thank you for the amazing image editor. 

We have a requirement stating that a user picks only 5 to 6 predefined colors for text, line and object drawing to ensure that every time the used editing colors are the same. 

Is there a way to configure this instead of the default hex color picker? 

best regards

**Comment by AhmeeedMostafa** [comment]
@rainabozhi not possible currently but seems a good enhancement to consider in the long term features yes

**Comment by coolibry** [comment]
hello,
i got the same request and see filerobot image editor allready store on local storage pinned color,
code is small to add or merge color value :
`	//set color picker custom
	const static_pinnedColors = ["#ff0000", "#00ff00", "#7a221f", "#2e6b2e", "#000", "#fff"];
	var FIE_pinnedColors = window.localStorage.FIE_pinnedColors;
	if (FIE_pinnedColors){
		FIE_pinnedColors = JSON.parse(FIE_pinnedColors);//convert to array
		FIE_pinnedColors = FIE_pinnedColors.concat(static_pinnedColors);//merge array
		FIE_pinnedColors = [...new Set(FIE_pinnedColors)];//remove duplicate entry
	}
	else{
		FIE_pinnedColors = static_pinnedColors;
	}

	//store to local storage
	window.localStorage.setItem('FIE_pinnedColors', JSON.stringify(FIE_pinnedColors));` 
add this before init filerobot image editor.
and the result  :
![image](https://github.com/scaleflex/filerobot-image-editor/assets/15387629/89889080-af10-4280-bacf-38abe019628f)

**Comment by rainabozhi** [comment]
Thanks for answering- that is basically what we did in the end.
