### ISSUE TITLE
How to discard changes / reset imageDesignState on new image selection? 

### ISSUE THREAD

**Issue by rainabozhi** [scaleflex/filerobot-image-editor#357]
Hey, 

I've said it once, but still- first of all thank you for the amazing editor and the typescript support. 

Now, we have some custom requirements and I could not find any documentation on how to do this. 
The user wants to be able to switch between preview list items (image thumbnails selection ) without persisting the image modifications. Hence, we want to be able to revert all user changes.  As of now, designState resets only on editor closing or with the undo button change by change- I need some similar functionality but revering all unsaved changes at once. 

I found the getCurrentImgDataFnRef - but it seems readOnly to me? 

best regards, 
Reni

**Comment by AhmeeedMostafa** [comment]
Hey @rainabozhi thanks for noticing, we are considering this in our next updates as it would be a better behavior yes.

The behavior to consider:
- changing the image while the editor is opened
- first we should alert the user that his changes are going to be lost if not saved (the alert should be connected/configured through this same property [`avoidChangesNotSavedAlertOnLeave`](https://github.com/scaleflex/filerobot-image-editor#avoidchangesnotsavedalertonleave) maybe same alert or an alert with diff. design (TBC)
- If user has decided to change then we are resetting all the state/changes and starting with the new image
- if decided to save then do nothing and keep the editor as it is to give him the chance to save the image first.

**Comment by AKhachoyan2003** [comment]
@AhmeeedMostafa Hello. I would like to know if this feature will be added in the near future?

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
