### ISSUE TITLE
Default image name being affected by the showCanvasOnly prop

### ISSUE THREAD

**Issue by alonsosjavacoffee** [scaleflex/filerobot-image-editor#358]
I'm currently toggling the editor's tools through the prop `showCanvasOnly` but I've encountered that changing the state of showCanvasOnly from true to false or vice versa affects that I've set the prop `defaultSavedImageName` to a specific value as a string  and when I click save, a notification pops up saying that the image name is required even though I defined that value through the `defaultSavedImageName` prop

**Comment by NermeenMoustafa** [comment]
Hey @alonsosjavacoffee, it works fine from my side, can you please provide a codesandbox produces that issue

**Comment by AhmeeedMostafa** [comment]
no response and issue not producible
