### ISSUE TITLE
Feature improvement: Add text and upload watermark in a single image edit 

### ISSUE THREAD

**Issue by Lazarova88** [scaleflex/filerobot-image-editor#364]
When water mark is uploaded and as second layer would like to add text is not possible in a single image edit. 

Would be great if watermark and text can be added in a single edit

**Comment by AhmeeedMostafa** [comment]
As it is watermark, we provide the possibility to add only 1 watermark as more proper usecase, if u need to add multiple annotations then u should draw/annotations tab.
