### ISSUE TITLE
Can't draw an ellipse inside polygon or rectangle

### ISSUE THREAD

**Issue by mkktvl** [scaleflex/filerobot-image-editor#366]
Noticed issue when i drew a rectangle and then tried to draw an ellipse inside that.

This can be reproduced in the demo shown in https://scaleflex.github.io/filerobot-image-editor/

1. First draw a rectangle (or polygon)
2. Select ellipse tool and start drawing inside the rectangle 
3. When you stop dragging (release mouse btn) the ellipse disappears and rectangle tool is selected

**Comment by NermeenMoustafa** [comment]
@mkktvl checking

**Comment by AhmeeedMostafa** [comment]
Fixed in latest version v4.5.2
