### ISSUE TITLE
Open image in "crop" mode by default,

### ISSUE THREAD

**Issue by rsakhi** [scaleflex/filerobot-image-editor#37]
Hello There, 
Filerobot Image Editor is great tool with all custom config option.
but I want to open image in "crop" mode by default, is there any configuration option to do this ??

**Comment by dzmitry-stramavus** [comment]
hey @rsakhi ,

it's exactly what I'm working on right now. It will be done in new release

**Comment by dzmitry-stramavus** [comment]
hey @rsakhi ,

done in **3.7.0**

codesandbox: https://codesandbox.io/s/cranky-haslett-w16fx

in config you need just indicate only one tool

```tools: ['crop']```
