### ISSUE TITLE
canvas is empty when opened with the same pic twice

### ISSUE THREAD

**Issue by Mohamedsobhy292** [scaleflex/filerobot-image-editor#370]
I have a problem when passing the editor an image element and not a link and saves if it's opened again it opens empty , I'm using react 16 and not v18, it seems ith works with version 4.5.1, but version 4.5.1 when used with react 17 or 16 it always opens empty canvas

link:
https://codesandbox.io/s/filerobot-image-editor-8dx6nz?file=/src/cropper.js

am I doing something wrong here?

**Comment by NermeenMoustafa** [comment]
@Mohamedsobhy292 checking

**Comment by NermeenMoustafa** [comment]
Hello Mohamed, the problem is the used react-konva version, v17.0.0-0 & v17.0.1-0 don't work but v17.0.1-1 and the higher versions work fine, we will update the doc to be more clear, thank you
