### ISSUE TITLE
I want non-stop drawing.

### ISSUE THREAD

**Issue by legion7298** [scaleflex/filerobot-image-editor#371]
First of all, I would like to thank you for making such a wonderful work:D
I want non-stop drwaing. But every time I click off the mouse
The line becomes objectified.
Press the draw button and draw continuously
I want it to be a guest when I finally press the save button.
How can I do that? Is there any way?

**Comment by AhmeeedMostafa** [comment]
Hey @legion7298 it is not a proper behavior to have, as in that case on entering/leaving the pointer there will be draw over the image that most probably won't be needed, so we must have an identifier to trigger the draw (which is the press).
