### ISSUE TITLE
Restrict selected part

### ISSUE THREAD

**Issue by webdeveloper510** [scaleflex/filerobot-image-editor#372]
We're trying to restrict the user's ability to select areas outside the image while using the "Draw" option in the Filerobot Image Editor. 
https://codesandbox.io/s/filerobot-image-editor-forked-1sektu?file=/src/App.js:31-51
Here we want to restrict frame only on image, it should not move outside the image.

**Comment by AhmeeedMostafa** [comment]
@webdeveloper510 ur request is a bit not clear, could u explain more what do u mean ?

**Comment by webdeveloper510** [comment]
I am working on a react project which uses the filerobot-image-editor to
edit the images. In the project, I want to add a few functionalities like
restricting the user to edit a certain frame of image i.e. providing the
user only some proportion of the image to edit, and out of that area user
should not be able to edit

**Comment by AhmeeedMostafa** [comment]
Closed as it is duplicated #373
