### ISSUE TITLE
Edit again

### ISSUE THREAD

**Issue by hoseinfo** [scaleflex/filerobot-image-editor#374]
Hi, thanks for providing this lib

I put an image and text in editor, how can I save them to my server to open then again with editor and able to change text and edit them again?

thanks

**Comment by AhmeeedMostafa** [comment]
Hey @hoseinfo u should use both the following,
1- [`onSave`](https://github.com/scaleflex/filerobot-image-editor#onsave) 2nd argument passed to the callback is the design state of the current edited image so u should save that in ur server.
2- and to load & open the image in the same state and be able to edit it again, provide that saved state on server to the following property of the plugin [`loadableDesignState`](https://github.com/scaleflex/filerobot-image-editor#loadabledesignstate-experimental) -- it might has some issues that we would fix in the future.
