### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by ozgevsight** [scaleflex/filerobot-image-editor#375]
I am currently getting cors from google storage url.
<img width="1440" alt="Screen Shot 2023-09-05 at 08 29 03" src="https://github.com/scaleflex/filerobot-image-editor/assets/103925030/289acdae-91b0-48cc-b992-1b2ac051d5c6">

**Comment by AhmeeedMostafa** [comment]
please check this issue #317 would fix ur issue, and closing this one as it is duplicated.
