### ISSUE TITLE
Need methods onClose() / onOpen() to js version

### ISSUE THREAD

**Issue by dmitrykovalevsky89** [scaleflex/filerobot-image-editor#38]
Hi!
Thank you to fixing this good editor!

We need to methods onClose() / onOpen() to js version (onOpen missing in the react too)
Perhaps you will update the documentation.

Thanks!
You making great product!

**Comment by dzmitry-stramavus** [comment]
hey @dmitrykovalevsky89 ,

thx for contributing! Sure, I'll add them in next releases

**Comment by stephan-fischer** [comment]
@dzmitry-stramavus  if you integrate the callback functions, can you please add a parameter, which is containing the image-editor div object as reference? id="filerobot-image-editor"

Thank you very much!

**Comment by ahmeeedkhallaf** [comment]
Hey @stephan-fischer ,
May I ask what's your use case for such request or in what are you going to utilize/use this parameter?

**Comment by dzmitry-stramavus** [comment]
hey @dmitrykovalevsky89 

onClose() / onOpen()  is available from **3.9.1**

https://github.com/scaleflex/filerobot-image-editor/blob/master/README.md#filerobotimageeditorconfig--callbacks--function
