### ISSUE TITLE
Maximum call stack size exceeded on updateState

### ISSUE THREAD

**Issue by metinkun** [scaleflex/filerobot-image-editor#380]
when i updating design with  updateStateFnRef?.current?.(prevDesign) i am getting Maximum call stack size exceeded error. i logged prevState and it look normal.  here is my error 
<img width="603" alt="image" src="https://github.com/scaleflex/filerobot-image-editor/assets/34644243/ed4ed551-ceba-43d9-bfa3-b363e02443de">

**Comment by AhmeeedMostafa** [comment]
Hey @metinkun we will check it and let u know with the updates

**Comment by YashpalModi** [comment]
Possible You Are Using Code Of Editor More Than 1 time Or Recursively

**Comment by AhmeeedMostafa** [comment]
Checked and the issue isn't producible and the fn. works fine, seems like it is some issue from your side, if u still have the same issue please add a demo that has the producible issues.
