### ISSUE TITLE
Clicking On Effects & Filters Button In Editor But Without Selecting Any Effect/Filter Option,I Click On Apply Button Directly Then Not Get Image Of Canvas In My Image Tag In HTML .How Can I Get That in js code ? Plz Provide Suitable Solution...

### ISSUE THREAD

**Issue by YashpalModi** [scaleflex/filerobot-image-editor#381]
On Clicking Effects & Filters Button In Editor ,Without Selecting Any Effect/Filter Option I Click On Apply Button Directly Then Not Get Image Of Canvas In My Image Tag In HTML .How Can I Get That in js code ? Plz Provide Suitable Solution...
================================================================================================

![Screenshot from 2023-09-11 15-16-42](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/41f6c502-1756-441c-823c-83879bd1a331)
![Screenshot from 2023-09-11 15-20-27](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/6516bb47-77b6-4693-b560-9d1db421ea69)
![Screenshot from 2023-09-11 15-20-45](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/e1249d9d-96ff-4781-b4e6-6c67a5a59c27)
![Screenshot from 2023-09-11 15-20-50](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/7fc2c289-b170-4005-b2a1-48f1494c9e48)
================================================================================================
Issue I m facing is I Click On Effects & Filters Button In Editor & Without Select Any Effect/Filter Option ,I Click On Apply Button  Directly Then Not Get Image Of Canvas In My Image Tag In HTML .How Can I Get That in js code ? Plz Provide Suitable Solution...
Thanks In Advance,
Yash.

**Comment by AhmeeedMostafa** [comment]
@YashpalModi ur question is not clear for me, I see the title is something and the description is another thing,

If u meant how to get the image after saving, u get the image and its state (the properties applied to it) through the [`onSave`](https://github.com/scaleflex/filerobot-image-editor#onsave) function

**Comment by YashpalModi** [comment]
Issue I m facing is I Click On Effects & Filters Button In Editor & Without Select Any Effect/Filter Option Click On Apply Button Then Not Get Image Of Canvas In My Image Tag In HTML .How Can I Get That in js code ? Plz Provide Suitable Solution...

**Comment by AhmeeedMostafa** [comment]
@YashpalModi  you should use [`onSave`](https://github.com/scaleflex/filerobot-image-editor#onsave) property, and provide a callback function to it that will receive in the image's data then u should provide either the base64 to ur img tag or convert the canvas to url and provide it to ur img tag.
