### ISSUE TITLE
 Clicking On Effects & Filters Button In Editor But Without Select Any Effect/Filter Option Click On Apply Button Directly Then Not Getting Image Of Canvas In My Image Tag In HTML .How Can I Get That in js code ? Plz Provide Suitable Solution

### ISSUE THREAD

**Issue by YashpalModi** [scaleflex/filerobot-image-editor#382]
Issue I m facing is I Click On Effects & Filters Button In Editor & Without Select Any Effect/Filter Option Click On Apply Button Then Not Get Image Of Canvas In My Image Tag In HTML .How Can I Get That in js code ? Plz Provide Suitable Solution
![Screenshot from 2023-09-11 15-16-42](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/27416998-2441-4cb6-ab90-db9633d00d84)
![Screenshot from 2023-09-11 15-20-27](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/21118898-a80c-43ac-bcc3-ecf5fd08e09c)
![Screenshot from 2023-09-11 15-20-45](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/a80ac534-47c0-4a5d-b0f2-8aad4c95b6dd)
![Screenshot from 2023-09-11 15-20-50](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/21e45984-db97-4172-a093-544df8136eba)

**Comment by AhmeeedMostafa** [comment]
Duplicate issue, closed
