### ISSUE TITLE
How To Check If User Has Clicked Filter Button But Not Selected Any Filter Option And Click On Apply Button Directly In Filerobot-Image-Editor In Js Code?

### ISSUE THREAD

**Issue by YashpalModi** [scaleflex/filerobot-image-editor#383]
how to check if user has clicked filter button but not selected any filter option and click on apply button directly in filerobot image editor in js code ?

![Screenshot from 2023-09-13 09-42-18](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/04c0bed3-ed49-4608-93ae-445ebfdab099)

**Comment by AhmeeedMostafa** [comment]
duplicated issue, closed
