### ISSUE TITLE
How To get Image Of Canvas If I Clicks Filter Button but not selected any filter option and click on apply button directly in js?

### ISSUE THREAD

**Issue by YashpalModi** [scaleflex/filerobot-image-editor#384]
I m using Filerobot image editor first time,my question is  how to check if user has clicked filter button but not selected any filter option and click on apply button directly in filerobot-image-editor in js,then how to get image of canvas in that case.Please Provide Me Suitable Solution.
![Screenshot from 2023-09-13 09-42-18](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/44f8e0fa-05a0-47e8-8594-5fd66210a478)

**Comment by AhmeeedMostafa** [comment]
Duplicated issue
