### ISSUE TITLE
How To Set Default Filter & Default Effect Option Selected In Filerobot Image Editor Config In JS

### ISSUE THREAD

**Issue by YashpalModi** [scaleflex/filerobot-image-editor#385]
Hey there,I am using Filerobot-Image-Editor For First Time ,Now My Question Is:How To Set Default Filter & Default Effect Option Selected  In Filerobot Image Editor Config In JS?Please Provide Me Solution Suitable.
![Screenshot from 2023-09-13 09-42-18](https://github.com/scaleflex/filerobot-image-editor/assets/107664185/2510fb56-ae92-487b-a3da-73c5b0fc8c1b)

**Comment by AhmeeedMostafa** [comment]
@YashpalModi you couldn't provide a filter, just u could provide [`defaultTabId`](https://github.com/scaleflex/filerobot-image-editor#defaulttabid) with filters tab id, in that case the filters tab would be opened as default but without providing custom filter

**Comment by YashpalModi** [comment]
How can i check that user has not selected any filter option after selecting filter button and click on apply i want alert that please select at least on filter option otherwise disable apply button .How can i achieve it with js?

**Comment by AhmeeedMostafa** [comment]
please check these functions [`onModify`](https://github.com/scaleflex/filerobot-image-editor#onmodify) & [`getCurrentImgDataFnRef`](https://github.com/scaleflex/filerobot-image-editor#getcurrentimgdatafnref) u could use any of them to recognize the changes and check if they have filter or not.

**Comment by YashpalModi** [comment]
How can i check if any of filter option's class is applied or not on click Of Apply Button in Filerobot Image Editor In Js Code? Any Solution Please....

**Comment by AhmeeedMostafa** [comment]
@YashpalModi
