### ISSUE TITLE
Panel Resize don't have "Apply" button

### ISSUE THREAD

**Issue by dmitrykovalevsky89** [scaleflex/filerobot-image-editor#39]
Hi!
Panel "Crop" and other panel have "Apply" button and have chance to "Remove" change
http://joxi.ru/DrlVV48IVE81B2

Panel "Resize" don't have "Apply" button and don't have chance to "Remove" change
http://joxi.ru/xAe00qnsRBnyy2

Please, add this change and button to "Resize" panel in next releases
Thank you!

**Comment by dzmitry-stramavus** [comment]
hey @dmitrykovalevsky89 ,

After resizing an image it makes it difficult to restore canvas. And frankly speaking, I don't think it's important to support as it can be done as last operation
