### ISSUE TITLE
Can't resolve 'canvas' with NextJS 13.5.3

### ISSUE THREAD

**Issue by whistledev0910** [scaleflex/filerobot-image-editor#390]
Hello sir, I am having some problems using your package.

As the title says, I got the error "Can't resolve 'canvas' " when I tried to install your package into package.json.

![Screenshot 2023-10-03 at 16 55 13](https://github.com/scaleflex/filerobot-image-editor/assets/88497295/24c15cb5-4702-459f-85f5-2a59d79a0711)

I followed the instructions and installed the necessary packages as required by the pre-installation.

I look forward to your help. I sincerely thank.

Have a nice day <3

**Comment by whistledev0910** [comment]
I have found a solution.
Basically the error here is because of "canvas".

1. I have added canvas to the dependencies.
2. I use macos, and everyone needs to follow [docs](https://www.npmjs.com/package/canvas) for the installation to complete.
3. Then, to use it with nextjs, you need to add a few settings to be able to use it on nextjs. 
`experimental: {
    esmExternals: 'loose',
  }`
  `webpack: (config) => {
    config.externals = [...config.externals, { canvas: 'canvas' }]
    return config
  },`
4. And finally we need to use nextjs dynamic import to avoid "Window is not defined" error.
![FilerobotImageEditor](https://github.com/scaleflex/filerobot-image-editor/assets/88497295/af0e1605-1ee3-4faf-b299-0b227acaa269)
![page](https://github.com/scaleflex/filerobot-image-editor/assets/88497295/e5825c80-c477-461c-8db1-e0ea1edcdbfb)

**Comment by whistledev0910** [comment]
I hope this helps someone who is also experiencing this.

**Comment by whistledev0910** [comment]
The problem has been resolved so I would like to close the issue here.

**Comment by satishgoml** [comment]
Thankyou

**Comment by satishgoml** [comment]
For some reason i can't drag and edit some of the annotations in brave browser in vercel 
@whistledev0910  Any idea about it. In other browsers it is working

https://filerobot-image-editor-nextjs.vercel.app/
