### ISSUE TITLE
Quality issue

### ISSUE THREAD

**Issue by juhaszmatyas85** [scaleflex/filerobot-image-editor#394]
I would start by saying that I don't necessarily think the issue is with your software, but I'd like to seek advice on what might be the problem.
When I reference an image and simply copy the content of "editedImageObject.imageBase64" from the console.log without making any modifications, I get a lower quality image than the original. I want to emphasize that I'm not using any functions; I'm just pressing the save button.

original image: https://juhaszm.hu/image_a.jpg
exported image: https://juhaszm.hu/image_b.png

I tried playing with the image quality settings, setting it to 1 in advance in the configuration, and experimenting with different image formats, but in each case, the quality deteriorates slightly.

So, I would like to ask if you have any idea why this works differently locally compared to the production environment with the plugin. Do you have any suggestions? I would greatly appreciate it if you could respond as it's relatively urgent for us to figure out if we need to find another plugin. I would also like to mention that the img.ly software doesn't exhibit this issue with the same image source, so I'm completely puzzled. It would be great to use your software since it's free and perfectly meets our needs. Thank you in advance!

**Comment by ukabyl** [comment]
You can pass an attribute "savingPixelRatio", In my case the value of 5 helped me

**Comment by maffintos** [comment]
Thx, but unfortunately, this solution did not help.

**Comment by AhmeeedMostafa** [comment]
@maffintos I couldn't see the difference in quality, so please if u could post other images that clarify the issue also your configurations?
