### ISSUE TITLE
updateStateFnRef doesn't let me delete via annotations update

### ISSUE THREAD

**Issue by KDDeveloper** [scaleflex/filerobot-image-editor#396]
updateStateFnRef merges updated state with previous one which means I can't delete from annotations. Is there a work around for this?

**Comment by AhmeeedMostafa** [comment]
not an intent to delete using this function, but maybe u could try a workaround which is setting the shape's value to null to override the shape's value, and check if all is good or not (make sure there is no bugs/issues once doing that)

**Comment by KDDeveloper** [comment]
@AhmeeedMostafa thanks a lot! that helped! but it make it really easy if we could do it within the context of just updating the state of the annotation
