### ISSUE TITLE
Is there a way to hide the back and save buttons?

### ISSUE THREAD

**Issue by Polydynamical** [scaleflex/filerobot-image-editor#398]
I apologize in advance since this is not an issue but a simple question: Is there a way to completely hide the back/close button and hide the save button? I'd like to hide the save button to implement my own save button (positioned in a more convenient location for my content).

Thanks in advance!

**Comment by AhmeeedMostafa** [comment]
You could achieve that using the static CSS selector

**Comment by AhmeeedMostafa** [comment]
@Polydynamical we have supported a prop for such a behavior, u will find it here [removeSaveButton](https://github.com/scaleflex/filerobot-image-editor#removesavebutton)

**Comment by Polydynamical** [comment]
> @Polydynamical we have supported a prop for such a behavior for save button only, u will find it here [removeSaveButton](https://github.com/scaleflex/filerobot-image-editor#removesavebutton)

Yes, I did notice that initially. However, I was looking for a way to also hide the "back" button since my website was handling the scene management.
