### ISSUE TITLE
Override default canvas/image size

### ISSUE THREAD

**Issue by ThatBusFromSpeed** [scaleflex/filerobot-image-editor#399]
Regardless of the size of the image I load the editor with, it constrains itself to 250px in height, with the total height of the editor being locked to somewhere around 550px. I've tried this with images from 500x500 to 5000x5000, producing the same 250px high canvas.

I checked the documentation and couldn't find an obvious way to set the dimensions of the canvas. What is the recommended way to set the size of the canvas/editor? Is there a way to have it scale automatically with image size?

**Comment by jwbrown** [comment]
Same issue

**Comment by AhmeeedMostafa** [comment]
The editor respects the HTML container dimensions, so you should change the dimensions of your container to what fit your needs
