### ISSUE TITLE
Editor container size adjustment

### ISSUE THREAD

**Issue by jwbrown** [scaleflex/filerobot-image-editor#400]
I am struggling with getting the editor larger on my webpage...   I have set the editor_container size in various ways including:
A. hard style
`<div id="editor_container" style="width:900;height:900"></div>`
B. CSS 
```
.container {
  height: 1000px;
  width: 100%;
  padding: 3rem;
  margin: 0;
  position: relative;
  box-sizing: border-box;
}
```
and in js to be sure
`document.querySelector("#editor_container").setAttribute("class","container");
`
And tried it with 
observePluginContainerSize: true,
observePluginContainerSize: false,
and no observePluginContainerSize element

With no impact on the size.   

I am running plain vanilla version with 
`<script src="https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/latest/filerobot-image-editor.min.js"></script>
`
When I inspect the result i see as the innermost element
`<canvas width="1007" height="250" style="padding: 0px; margin: 0px; border: 0px; background: transparent; position: absolute; top: 0px; left: 0px; width: 1007px; height: 250px; display: block;"></canvas>
`
Which seems descended from:
`<div class="konvajs-content" role="presentation" style="position: relative; user-select: none; width: 1007px; height: 250px;"><canvas width="1007" height="250" style="padding: 0px; margin: 0px; border: 0px; background: transparent; position: absolute; top: 0px; left: 0px; width: 1007px; height: 250px; display: block;"></canvas><canvas width="1007" height="250" style="padding: 0px; margin: 0px; border: 0px; background: transparent; position: absolute; top: 0px; left: 0px; width: 1007px; height: 250px; display: block;"></canvas></div>`

Any direction would be greatly appreciated.

**Comment by AhmeeedMostafa** [comment]
Please double check your code, or make a codesandbox contains your issue...
The editor already respects to the container size,
 the idea behind
```js
observePluginContainerSize: true,
observePluginContainerSize: false
```

is to care for the size changes in the container.
