### ISSUE TITLE
Bring edit options on click of Draw outsite

### ISSUE THREAD

**Issue by dbmediatech** [scaleflex/filerobot-image-editor#404]
How to bring out the edit options which were coming on click of draw option

**Comment by AhmeeedMostafa** [comment]
Could u please explain exactly your issue as it is not clear? and if u are asking for some changes it would be nice to mention your usecase that would be easier for us to decide

**Comment by dbmediatech** [comment]
HI @AhmeeedMostafa, on click of TEXT tool inside the annotate tool, I am getting the text tool enabled, and on double click of that enabled text tool I am able to edit it but my requirement is, if I double click the text tool need the default text text as empty, by default it should be "Double click to edit" and on double click it should be empty

**Comment by AhmeeedMostafa** [comment]
@dbmediatech not possible, but anyway you could change the default text content through the configurations available for the text tool so it might be related to your usecase
