### ISSUE TITLE
What is this loading?

### ISSUE THREAD

**Issue by gametheworld** [scaleflex/filerobot-image-editor#405]
![image](https://github.com/scaleflex/filerobot-image-editor/assets/6021628/1f7c5332-e77d-4a53-9c22-7f8136de7069)

**Comment by AhmeeedMostafa** [comment]
@gametheworld what's the issue? could u please describe it!

**Comment by gametheworld** [comment]
> @gametheworld what's the issue? could u please describe it!

Directly open demo local operation, UI display has been loading, I do not know what is loading
Anyway, the page has been loading, and there are no errors in the console
I don't know what the problem is

**Comment by gametheworld** [comment]
I have found the reason. My current project is react17, so I have been loading

Use react18 in the demo

https://codesandbox.io/s/elegant-khorana-qq5vgq?file=/package.json
