### ISSUE TITLE
Is it possible to have additional predefined shapes and colors?

### ISSUE THREAD

**Issue by davor-layer-four** [scaleflex/filerobot-image-editor#408]
Hi, 
I am trying to integrate the library inside my app, and I have a use case where the user selects a shape and color for an item, now I would like to render that/ pre-load it inside the image editor. 

Is it possible somehow? E.g. I want to allow the user to just create and drag a rectangle shape inside the image editor, and for it to load the color as a input parameter, not have the user manually put the HEX value. 

Thank you very much for your help :)

**Comment by AhmeeedMostafa** [comment]
@davor-layer-four I didn't get your question very well, but I think you are talking about setting the customization from ur code side not from the UI side, in that case u could check the docs' for the tool you want to customize and u will find the customization options available, and if u need to hide some functionality from the UI, you could use the static CSS class to do that for now.

**Comment by davor-layer-four** [comment]
Hi @AhmeeedMostafa , I am talking about something similar to https://github.com/scaleflex/filerobot-image-editor/issues/348 
So basically inside the image editor toolbar, I would like to offer some pre-defined shapes, like a rectangle.

**Comment by AhmeeedMostafa** [comment]
@davor-layer-four not possible to add more shapes apart from the current ones till now.
