### ISSUE TITLE
Text and drag and drop feature for watermarking image

### ISSUE THREAD

**Issue by tobiaszgala** [scaleflex/filerobot-image-editor#41]
Great editor so far guys!

I have a feature suggestion for adding text input and dnd functionality in the watermark menu. For now, we can add picture but it would also be nice to have text input.

Thanks!

**Comment by maksmarty** [comment]
Thanks for great module.

Is there any plan for this feature guys?

Thanks!

**Comment by dzmitry-stramavus** [comment]
hey @maksmarty ,

it's already in work, it'll be available in next release

**Comment by AhmeeedMostafa** [comment]
Hey @tobiaszgala @maksmarty ,
Please note this feature has been added in the new versions let us know if there any problem,
thanks!
