### ISSUE TITLE
Not able to change the text and stroke color

### ISSUE THREAD

**Issue by kishanindegene** [scaleflex/filerobot-image-editor#413]
When  try to edit the text and give the color and stroke color then it is giving below error
**react-dom.development.js:12056 Uncaught ReferenceError: React is not defined
    at ColorPickerModal**
    
  can you please look into this
  @AhmeeedMostafa

**Comment by AhmeeedMostafa** [comment]
@kishanindegene It's fixed in the new release v4.6.3, please re-check
