### ISSUE TITLE
Editor Closes Automatically When Clicks Outside Of It

### ISSUE THREAD

**Issue by YashpalModi** [scaleflex/filerobot-image-editor#418]
Hello There ,Issue I m facing while using filerobot image editor is that when editor is open and click on outside of editor at that time, then editor closes itself automatically.I want data-keyboard='false' functionlity of bootstrap modal to prevent modal being closed automatically in such case.I dont know how to solve it so any help would be appreciated.
Thanks In Advance,
Yash

**Comment by AhmeeedMostafa** [comment]
@YashpalModi As far as I got, your issue is more related to the bootstrap modal, not to the editor so if you add your code someone might help you better.
