### ISSUE TITLE
incorrect position of annotation controls

### ISSUE THREAD

**Issue by gsoec** [scaleflex/filerobot-image-editor#424]
The position of annotation controls is incorrect after the image is rotated with angle.

<img width="293" alt="image" src="https://github.com/scaleflex/filerobot-image-editor/assets/26665579/92a78691-84fc-4d96-b64d-69b40af15ada">

**Comment by AhmeeedMostafa** [comment]
Thanks for reporting, we are aware of the issue but it's duplicated so we are closing this one #336
