### ISSUE TITLE
Small UI design improvements

### ISSUE THREAD

**Issue by HimonRana** [scaleflex/filerobot-image-editor#426]
There is some small issues in the latest design.

1. Slider is not verticle-aligned
Rectangle > Corner radius
![image](https://github.com/scaleflex/filerobot-image-editor/assets/31616276/43a780b0-accb-4132-829c-78e45b3bdb17)
Polygon > Sides
![image](https://github.com/scaleflex/filerobot-image-editor/assets/31616276/9e6603c0-5848-458b-9eb1-1db0c7a82dba)

2. All sliders should have input/tooltip(like before UI update) showing the pixel
![image](https://github.com/scaleflex/filerobot-image-editor/assets/31616276/e1870067-3a60-42b5-b5c7-9c3b85f86ae0)
eg. 
![image](https://github.com/scaleflex/filerobot-image-editor/assets/31616276/11ef1402-e6ab-4b7a-a447-b1be8d82c0b7)

3. Also color picker(for pen/line/arrow) should be outside stroke-button for better UI
![image](https://github.com/scaleflex/filerobot-image-editor/assets/31616276/be98dde8-3c76-4df7-99e6-aff96589d0dd)

**Comment by AhmeeedMostafa** [comment]
@HimonRana thanks for the useful feedback we will process this to our design team to be considered in the next design changes/improvements

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
