### ISSUE TITLE
Request got blocked and the editor stopped working for me 

### ISSUE THREAD

**Issue by JHarithaR** [scaleflex/filerobot-image-editor#427]
Hi team 
Yesterday i tried using filerobot Image editor on react application.it worked fine till yesterday and suddenty the request was blocked 
https://i18n.ultrafast.io/api/export?grid=353297d2-40b4-4684-a875-45a2178a8157 for this url
and today it started working fine
What was the issue . how to overcome in this situations

**Comment by AhmeeedMostafa** [comment]
Hello,
This is our translation grid you could avoid it and use your own translations ,

Just provide `useBackendTranslations: false` and provide your `translations` object contains the key and translated value (in that case you are handling the language changes from your side)
