### ISSUE TITLE
What file formats are supported?

### ISSUE THREAD

**Issue by melsu** [scaleflex/filerobot-image-editor#43]
I noticed that you are using the [image-type library ](https://www.npmjs.com/package/image-type) that is supposed to support jpg, png, gif, webp, flif, cr2, tif, bmp, jxr, psd, ico, bpg, jp2 - JPEG 2000, jpm - JPEG 2000, jpx - JPEG 2000, heic, cur, dcm - DICOM Image File. 

I have only successfully edited jpg, png, and gif. Thanks!

**Comment by dzmitry-stramavus** [comment]
hey @melsu ,

for now, we test only jpg, png, and gif. We will support/test more formats when the main functionality will be ready and polished.

**Comment by ffjanhoeck** [comment]
@dzmitry-stramavus Its now over a year ago... When are you going to support HEIC/HEIF file formats ?

**Comment by FlorianB89** [comment]
Hi, I would need support for .tif images. Is someone already working on additional file types? Otherwise I would take a look how much effort this would be myself.
