### ISSUE TITLE
Potential bug- cancel button for color selection does not reset 

### ISSUE THREAD

**Issue by rainabozhi** [scaleflex/filerobot-image-editor#435]
Dear filerobot team, 

I just noticed that if you open the color picker and change your color selection- and then click on "Cancel" - the new selected color stays as is- shouldn't it go back to the default it had in that case? 

Best regards, 

Reni

**Comment by AhmeeedMostafa** [comment]
Thanks for reporting @rainabozhi , yes you are right, we are going to consider fixing this in the upcoming versions.

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
