### ISSUE TITLE
Value of sliders out of place

### ISSUE THREAD

**Issue by claudiorivetti** [scaleflex/filerobot-image-editor#437]
The position of the sliders text value is out of place. See demo HSV.

**Comment by claudiorivetti** [comment]
caused by css class hAUvFp applied to input field:
min-width: fit-content;

to fix it:
input.SfxInput-Base {min-width: auto}

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
