### ISSUE TITLE
Having problems with the zoom feature

### ISSUE THREAD

**Issue by PedroMFernandes** [scaleflex/filerobot-image-editor#439]
Hello, I'm currently having troubles with the zoom feature. When zooming larger images to 100%, I get some pixelation. To provide context, I'll include an image for comparison using Paint. Thank you and best regards!

![image](https://github.com/scaleflex/filerobot-image-editor/assets/33553298/a835bdda-e5f5-47bb-81cb-face458d40d6)

**Comment by AhmeeedMostafa** [comment]
Hey @PedroMFernandes  sorry for the late reply our time doesn't allow us to keep an eye on the issues regularly recently.

you could play with this property [previewPixelRatio](https://github.com/scaleflex/filerobot-image-editor?tab=readme-ov-file#previewpixelratio) to give better resolution but it will be slower in performance.

**Comment by AhmeeedMostafa** [comment]
@PedroMFernandes please re-open the issue if the last comment didn't help you in your implementation, thanks!
