### ISSUE TITLE
is there any hooks/prop when editor loaded ?

### ISSUE THREAD

**Issue by fadlulazmi** [scaleflex/filerobot-image-editor#44]
i want to add process when editor perfectly displayed on component

**Comment by dzmitry-stramavus** [comment]
hey @fadlulazmi ,

not yet, but I'll add events in next release

**Comment by dzmitry-stramavus** [comment]
hey @fadlulazmi ,

onOpen() callback is available from 3.9.1

https://github.com/scaleflex/filerobot-image-editor/blob/master/README.md#filerobotimageeditorconfig--callbacks--function
