### ISSUE TITLE
Apply filter on single image

### ISSUE THREAD

**Issue by DeanTorto** [scaleflex/filerobot-image-editor#440]
Is there a way to apply the filter to the selected image only. currently when you apply a filter this seems to be applied to all uploaded images.

I'd also like to get the url of the image that has been filtered and display that in the uploaded images when a user selects another image to apply the filter to.

**Comment by AhmeeedMostafa** [comment]
Hello, @DeanTorto  sorry for the late reply our time doesn't allow us to keep an eye on the issues regularly recently.

Unfortunately what u requested for isn't possible for now (we might include it as possible enhancement in the feature once we have enough time to maintain the project more by new feats & improving the behaviors) for the meantime if someone could contribute by applying this we don't mind for sure :)

**Comment by AhmeeedMostafa** [comment]
@DeanTorto I didn't understand your question exactly, if you mean about the code place that is responsible about save button, you'll fine inside `packages/react-filerobot-image-editor/src/components/Topbar/SaveButton.jsx`
