### ISSUE TITLE
Callback "onModify" not triggered by "undo" / "redo"?

### ISSUE THREAD

**Issue by software-mf** [scaleflex/filerobot-image-editor#444]
Hi, when the icons "undo" / "redo" (top right in the editor) are clicked the callback

`onModify`

is not triggered as I see (when I log this callback on the JavaScript console) although the image is
modified by this action.

Is there a possibilty to make sure that this callback 

`onModify`

is called with each modification?

**Comment by AhmeeedMostafa** [comment]
@software-mf yes, this should be considered as an enhancement in the upcoming changes (no specific time yet) if you are in a hurry about it you might contribute by doing that `useAppReducer.js` file would be a hand for you.

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
