### ISSUE TITLE
Application detects change when the main menu point "finetune" is entered

### ISSUE THREAD

**Issue by software-mf** [scaleflex/filerobot-image-editor#445]
Good day, as soon as the main point 

**finetune**

is entered via the main navigation in my test project of Filerobot Image Editor

1. the save button gets enabled then at the latest and 
2. the undo icon gets active although there was no active change on the image in the editor done by user.

Is this a bug or dependent on any configuration? 
Is it possible to suppress this behaviour that the save button gets enabled and the undo icon active when "finetune" is entered?

**Comment by AhmeeedMostafa** [comment]
@software-mf On opening the tab, we apply the finetune so it is considered as a change but since it is the default value of the image you see no diff.

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
