### ISSUE TITLE
Save as Button Modal design issue in firefox browser

### ISSUE THREAD

**Issue by arkasarkar2000** [scaleflex/filerobot-image-editor#446]
When clicking on the "Save" button, a modal opens with height and width fields. This functionality works as expected in Chrome, Brave, and Safari. However, in Firefox, the design appears broken.

![Screenshot 2024-02-22 174944](https://github.com/scaleflex/filerobot-image-editor/assets/48146304/e4836eae-b48c-4596-90fd-d7d7d449fc1c)

**Comment by AhmeeedMostafa** [comment]
Good catch @arkasarkar2000 we are considering it in the upcoming release.

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
