### ISSUE TITLE
add inital textbox

### ISSUE THREAD

**Issue by fgiering** [scaleflex/filerobot-image-editor#447]
Is there any way somehow to set an inital default textbox on rendering the imageEditor?
I already added an default text but I want my customers just to change the text without drawing the textbox:

![grafik](https://github.com/scaleflex/filerobot-image-editor/assets/35344457/3a1d1411-0248-41a1-932a-90fb8ce0f6a3)

**Comment by AhmeeedMostafa** [comment]
You could try that by using this property [loadableDesignState](https://github.com/scaleflex/filerobot-image-editor?tab=readme-ov-file#loadabledesignstate-experimental)

**Comment by fgiering** [comment]
> You could try that by using this property [loadableDesignState](https://github.com/scaleflex/filerobot-image-editor?tab=readme-ov-file#loadabledesignstate-experimental)

this works. awesome. thank you!
