### ISSUE TITLE
Annotating with the pen makes the image disappear randomly

### ISSUE THREAD

**Issue by OFAlexandre** [scaleflex/filerobot-image-editor#449]
Hello,
Sometime I have a strange behavior when a try to editing a picture with the pen.

By editing an image with the pen and tapping the screen several times, from time to time the image disappears and I cannot do  anything. 

This case is not easily reproducible because it is fairly random, but I notice that it comes only from mobile devices like phone or tablet.

Please find enclosed a little video where I had this case and also a printscreen of call stack before the crash.

Has anyone encountered this problem?

Thank you in advance for your help.

![callstack](https://github.com/scaleflex/filerobot-image-editor/assets/160841952/2887486e-6325-4da1-bc47-986650f474cf)

https://github.com/scaleflex/filerobot-image-editor/assets/160841952/d8ab4cce-3fb8-4ac1-8914-4848ca5115dc

**Comment by AhmeeedMostafa** [comment]
Hello @OFAlexandre we are going to check that and would let u know with the updates

**Comment by AhmeeedMostafa** [comment]
@OFAlexandre I couldn't reproduce at all, it would be helpful to provide some codesandbox, thanks

**Comment by OpaqueGlass** [comment]
I also encountered a similar issue, but on desktop (Windows 11, Edge 140.0.3485.66).  
When using the image editor in Annotate - Pen mode, if I quickly draw several lines and then keep clicking continuously, the editor sometimes crashes and exits.  

It can be reproduced in https://scaleflex.github.io/filerobot-image-editor/

![Image](https://github.com/user-attachments/assets/9bff8923-762a-4001-9527-cc996b10c497)
