### ISSUE TITLE
Wagtail CMS Widget

### ISSUE THREAD

**Issue by Nigel2392** [scaleflex/filerobot-image-editor#450]
Hi there,

Just wanted to inform you that I made a widget for a [python CMS](https://github.com/wagtail/wagtail) from your library.
Thank you for the MIT license and the great work!
https://github.com/Nigel2392/wagtail-filerobot

Possibly I could turn this into an official bridge for the entire Django web framework.
Is that something you would be interested in?  
Are there any special requirements for that?

**Comment by AhmeeedMostafa** [comment]
Hey @Nigel2392 thanks for such a good consideration,

That would be great, and no special requirements for that you could also make a PR & add its docs link in the repo's README.
