### ISSUE TITLE
The CDN still using version v4.7.0 instead of v4.7.1

### ISSUE THREAD

**Issue by billyadelphia** [scaleflex/filerobot-image-editor#452]
The CDN still using version v4.7.0 instead of v4.7.1

![cdn](https://github.com/scaleflex/filerobot-image-editor/assets/20699349/a1f0f349-ef4b-473b-bacb-b6ecf20e20b8)

**Comment by K20** [comment]
I think it is because the npm latest version is 4.7.0 : https://www.npmjs.com/package/filerobot-image-editor

**Comment by AhmeeedMostafa** [comment]
Hey, we have updated that and added the v4.7.1 ,
also, there is a new minor version released v4.8.0 I'd advice to use.
