### ISSUE TITLE
compile error with webpack

### ISSUE THREAD

**Issue by z88kat** [scaleflex/filerobot-image-editor#453]
Hi,

I get the following dependancy error when compiling with webpack (I'm just using the plain npm import FilerobotImageEditor from 'filerobot-image-editor';).

Seems to be an issue with the tippy, but i cannot figure out how to solve it.  Can anyone help here?

ERROR in ./node_modules/tippy.js/dist/tippy.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .tippy-box[data-animation=fade][data-state=hidden]{opacity:0}[data-tippy-root]{max-width:calc(100vw - 10px)}.tippy-box{position:relative;background-color:#333;color:#fff;border-radius:4px;font-size:14px;line-height:1.4;white-space:normal;outline:0;transition-property:transform,visibility,opacity}.tippy-box[data-placement^=top]>.tippy-arrow{bottom:0}.tippy-box[data-placement^=top]>.tippy-arrow:before{bottom:-7px;left:0;border-width:8px 8px 0;border-top-color:initial;transform-origin:center top}.tippy-box[data-placement^=bottom]>.tippy-arrow{top:0}.tippy-box[data-placement^=bottom]>.tippy-arrow:before{top:-7px;left:0;border-width:0 8px 8px;border-bottom-color:initial;transform-origin:center bottom}.tippy-box[data-placement^=left]>.tippy-arrow{right:0}.tippy-box[data-placement^=left]>.tippy-arrow:before{border-width:8px 0 8px 8px;border-left-color:initial;right:-7px;transform-origin:center left}.tippy-box[data-placement^=right]>.tippy-arrow{left:0}.tippy-box[data-placement^=right]>.tippy-arrow:before{left:-7px;border-width:8px 8px 8px 0;border-right-color:initial;transform-origin:center right}.tippy-box[data-inertia][data-state=visible]{transition-timing-function:cubic-bezier(.54,1.5,.38,1.11)}.tippy-arrow{width:16px;height:16px;color:#333}.tippy-arrow:before{content:"";position:absolute;border-color:transparent;border-style:solid}.tippy-content{position:relative;padding:5px 9px;z-index:1}
 @ ./node_modules/react-filerobot-image-editor/node_modules/@scaleflex/ui/core/tooltip-v2/tooltip-v2.component.js 6:0-33
 @ ./node_modules/react-filerobot-image-editor/node_modules/@scaleflex/ui/core/tooltip-v2/index.js 1:0-49 1:0-49
 @ ./node_modules/react-filerobot-image-editor/node_modules/@scaleflex/ui/core/index.js 58:0-52 58:0-52
 @ ./node_modules/react-filerobot-image-editor/lib/components/App/App.styled.js 1:0-39 1:1425-1431
 @ ./node_modules/react-filerobot-image-editor/lib/components/App/index.js 1:1826-1919 1:5302-5318 1:5702-5719 1:5781-5791 1:5881-5901
 @ ./node_modules/react-filerobot-image-editor/lib/components/AssemblyPoint/index.js 1:78-102 1:1256-1259
 @ ./node_modules/react-filerobot-image-editor/lib/index.js 1:0-61 1:170-190
 @ ./node_modules/filerobot-image-editor/lib/index.js 1:1313-1381 1:2912-2925 1:3477-3481 1:3528-3533 1:3561-3565 1:3593-3598
 @ ./webclient/js/views/actionpack/render/file-attachment.js 7:0-58 931:10-30 957:24-44
 @ ./webclient/js/views/actionpack/components.js 30:0-94 421:19-39 741:4-29
 @ ./webclient/js/views/actionpack/action-pack.js 18:0-77 291:31-47 295:2-26
 @ ./webclient/app.js 72:0-74 263:12-22
webpack 5.90.0 compiled with 2 errors in 14271 ms

**Comment by MartinoVolcy** [comment]
did you ever solve this, currently having this issue

**Comment by AhmeeedMostafa** [comment]
@z88kat are u including the webpack loader plugin for css?
