### ISSUE TITLE
Memory problem after several saves

### ISSUE THREAD

**Issue by ChGuiFM** [scaleflex/filerobot-image-editor#458]
Hi,

After several tests, I think I have discovered a memory leak when saving an image.
It's easy to reproduce (tests done with Chrome), even on the demo site. After 5-6 saves, you have a kind of black screen and the saved image is fully black.

You can see that the memory usage of the tab is very high. I tried to find something with the debug console but curiously, it does not seem to come from javascript's memory usage.

You can accelerate the problem by just adding an annotation image and then, you save several times until the problem occurs.
It can also be reproduced directly with the method getCurrentImgData().

Did somebody else find this problem?

**Comment by brunoalexsantos** [comment]
I've the same problem. Anyone find a solution?
@AhmeeedMostafa

**Comment by AhmeeedMostafa** [comment]
Hello, the issue is considered in the latest released minor version v4.8.0, please update the plugin and re-open the issue if there is any update.
