### ISSUE TITLE
is it possible to keep only square crop ?

### ISSUE THREAD

**Issue by mezbahalam** [scaleflex/filerobot-image-editor#46]
If I do not want to keep other cropping such as banner. is it possible ?

**Comment by dzmitry-stramavus** [comment]
hey @mezbahalam ,

yes, it's possible. [Here](https://github.com/scaleflex/filerobot-image-editor#croppresets-object) is the property in the config.

You will need to put only what you need in the array

```cropPresets: [{ name: 'square', value: 1 }]```
