### ISSUE TITLE
Problem with text in the rotated image

### ISSUE THREAD

**Issue by XeKT0r** [scaleflex/filerobot-image-editor#473]
I noticed a problem with text substitution after I changed the rotation of the image. I attached the video. Maybe someone has encountered this problem and knows how to solve it, otherwise it is very inconvenient to use.  I use:  next.js 14.2,  react-filerobot-image-editor 4.8.1.

https://github.com/scaleflex/filerobot-image-editor/assets/147561391/edd1a221-e50d-40bb-ad0e-77b83ffe31c4

https://github.com/scaleflex/filerobot-image-editor/assets/147561391/3a6cc4cd-ccbc-4ff9-a8f2-d7cd50637772

**Comment by AhmeeedMostafa** [comment]
Hey @XeKT0r this issue is considered in the next release, you will find it fixed once we release it as prod.

**Comment by AhmeeedMostafa** [comment]
@XeKT0r It has been fixed in the version 4.9.0, please check and if still there is any comment reopen the issue.
