### ISSUE TITLE
How initialize watermark gallery?

### ISSUE THREAD

**Issue by friman** [scaleflex/filerobot-image-editor#475]
Hello
I tried to find where was filled this list and cannot. Can someone tell me?

![Untitled](https://github.com/scaleflex/filerobot-image-editor/assets/274697/fdb94e8e-e27d-45a0-a19b-1564d354044b)

**Comment by AhmeeedMostafa** [comment]
Hey @friman you would find this here [`watermark.gallery`](https://github.com/scaleflex/filerobot-image-editor?tab=readme-ov-file#watermark) as a property called `gallery`
