### ISSUE TITLE
Capturing photo resolution showing higher than normal and crashed

### ISSUE THREAD

**Issue by devhimel** [scaleflex/filerobot-image-editor#479]
I used the Vanilla js and Bootstrap modal to edit the picture. everything is fine when I upload images from my desktop or phone. but my client shows me that when he directly captures photos from his phone instead of uploading from the gallery, its resolution Getting higher. and on save it is getting crashed.

it is not happening for every phone like in my phone it is working perfectly.

![WhatsApp Image 2024-06-30 at 11 08 32_7caeb768](https://github.com/scaleflex/filerobot-image-editor/assets/83213572/01a2d855-d25f-4ab2-a339-eae4d9f99898)

**Comment by AhmeeedMostafa** [comment]
Hey @devhimel , maybe it is something more related to your client's device resources

so if you could to share with us the client's phone model and exact steps to reproduce to be able to check that.
