### ISSUE TITLE
Modify image in local serveur

### ISSUE THREAD

**Issue by micker** [scaleflex/filerobot-image-editor#48]
Hello it possible to use this script to modify image in own serveur without cdn image ?
I am not sure
Thanks

**Comment by dzmitry-stramavus** [comment]
hey @micker ,

it's possible, but it requires some extra work.

Check: 
https://github.com/scaleflex/filerobot-image-editor/issues/10
https://github.com/scaleflex/filerobot-image-editor/issues/6
https://github.com/scaleflex/filerobot-image-editor/issues/35

**Comment by micker** [comment]
ok thanks
