### ISSUE TITLE
Slider tools change min-max value

### ISSUE THREAD

**Issue by XeKT0r** [scaleflex/filerobot-image-editor#480]
It would be nice to add to the config the ability to change the maximum minimum values ​​​​in various slider tools:
1) When changing the text thickness with the slider, it’s not clear why there is such a range of values, after about 7 all the text becomes blurry, and closer to 100 it turns into something incomprehensible.
2) Similar problems in managing line spacing; if you drag the slider further than two, then the second line begins to go completely nowhere.

**Comment by AhmeeedMostafa** [comment]
@XeKT0r Thanks for the suggestion,

I guess it depends on the use-case at the end some other people might need that higher value and maybe not even if they are almost the same.

So in such a case, you could keep using the range you want without going lower/higher but having properties for configuring each of them and making things more complex for no clear reason isn't good to consider.
