### ISSUE TITLE
Cannot load js file in Microsoft Edge

### ISSUE THREAD

**Issue by basdie** [scaleflex/filerobot-image-editor#482]
When trying to load the js file with Microsoft Edge, I receive the following error:
{
    "status": "error",
    "code": "FILE_GONE",
    "msg": "This resource was not found in any Datacenter",
    "trace_id": "AsIACpMJwo569eO",
    "hint": "Please check the upload, the resource might have raised an error",
    "api_version": {
        "datetime": "",
        "hash": "",
        "module": "elastic_v3"
    }
}

I used this URL from your documentation: https://[scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/latest/filerobot-image-editor.min.js](https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/latest/filerobot-image-editor.min.js)

1. Open Microsoft Edge
2. Go to https://[scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/latest/filerobot-image-editor.min.js](https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/latest/filerobot-image-editor.min.js)
3. See error

Desktop:
 - OS: Windows 11 Pro
 - Browser: Microsoft Edge Version 126.0.2592.102 (Offizielles Build) (64-Bit)

**Comment by esnim** [comment]
I am trying to load from CDN and the request is failing with a 410 http status. I tried on Firefox, Chrome and Edge.

Request URL: https://scaleflex.cloudimg.io/v7/plugins/filerobot-image-editor/latest/filerobot-image-editor.min.js
Request Method: GET
Status Code: 410 Gone
Referrer Policy: strict-origin-when-cross-origin

**Comment by AhmeeedMostafa** [comment]
I couldn't produce your mentioned issue,
here you are a screenshot from a device same as ur OS and Edge -- 127.0.2651.98 (Official build) (64-bit) -- so please check your browser or if u still having an issue add the curl this might help,

![image](https://github.com/user-attachments/assets/b9c4f559-5a52-4c61-8763-3a98e02818f4)
