### ISSUE TITLE
 ReferenceError: React is not defined after upgrading version

### ISSUE THREAD

**Issue by BinarySenseiii** [scaleflex/filerobot-image-editor#483]
I recently upgraded my project from version 4.8.1 to 5.0.1 and encountered a ReferenceError: React is not defined error. This issue appears despite no changes being made to my codebase that would typically cause this error. I suspect it might be related to changes in the package.

_**Steps to Reproduce:**_

- Upgrade from pkg 4.8.1 to 5.0.1.
- Run the project.
- Observe the error in the console: ReferenceError: React is not defined.

**_Expected Behavior:_**
The project should run without any reference errors, as it did in version 4.8.1.

**_Actual Behavior:_**
After upgrading to version 5.0.1, the following error is thrown:

- ReferenceError: React is not defined

I have verified that my code has not changed in a way that would cause this error. I have also tried clearing the cache and reinstalling node_modules, but the issue persists

![image](https://github.com/user-attachments/assets/1dcff29d-2603-42e0-9882-72ab4077d166)
![image](https://github.com/user-attachments/assets/6e411ab3-80fe-4c76-a9cf-dfd0671d8229)

**Comment by AhmeeedMostafa** [comment]
@BinarySenseiii V5 isn't yet released officially these are some tests being done there, you should use the NPM's latest stable version 4.8.1.
