### ISSUE TITLE
Can't save image from the browser

### ISSUE THREAD

**Issue by naidadem** [scaleflex/filerobot-image-editor#489]
Steps to reproduce:

1. Open the image in Filerobot Image Editor in e.g. Google Chrome
2. Right click on the image and choose "Save Image As"
3. The downloaded image is blank

Same happens when I try to follow these steps in the demo https://scaleflex.github.io/filerobot-image-editor/?ref=producthunt. Attached you can see the images that got saved to my device.
![download](https://github.com/user-attachments/assets/dae9597e-3c71-47b1-8508-91c081ac9fbd)
![download (1)](https://github.com/user-attachments/assets/67ca1a02-1533-4a5c-8f4a-d11196f12074)

**Comment by AhmeeedMostafa** [comment]
@naidadem This is not the intended usage of the library, you have to use the [`onSave`](https://github.com/scaleflex/filerobot-image-editor?tab=readme-ov-file#onsave) property with your own implementation.
