### ISSUE TITLE
Missing dependencies requested by @filerobot/core and other dependencies

### ISSUE THREAD

**Issue by z88kat** [scaleflex/filerobot-image-editor#490]
When installing filerobot-image-editor I am getting the following dependency errors.  I'm not using react in my environment. Attempting to manually installed all these missing dependencies does not solve the problem. It's like alice in wonderland, just keeps going on and on with more missing dependencies or version errors. I cannot solve through manually installing the missing packages.

yarn add filerobot-image-editor react-filerobot-image-editor

➤ YN0000: · Yarn 4.4.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + react-filerobot-image-editor@npm:4.8.1, @scaleflex/icons@npm:2.6.3, @scaleflex/ui@npm:2.7.0
➤ YN0000: └ Completed in 1s 473ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ xx@workspace:. doesn't provide @types/react (p091ce), requested by @filerobot/core and other dependencies.
➤ YN0002: │ xx@workspace:. doesn't provide @types/react-dom (p6c812), requested by @filerobot/core and other dependencies.
➤ YN0002: │ xx@workspace:. doesn't provide react (pcaa22), requested by @filerobot/core and other dependencies.
➤ YN0002: │ xx@workspace:. doesn't provide react-dom (p05532), requested by @filerobot/core and other dependencies.
➤ YN0002: │ xx@workspace:. doesn't provide react-konva (pcb915), requested by react-filerobot-image-editor.
➤ YN0002: │ xx@workspace:. doesn't provide react-redux (p700d6), requested by @filerobot/image-editor and other dependencies.
➤ YN0002: │ xx@workspace:. doesn't provide styled-components (p03cc8), requested by react-filerobot-image-editor.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 2s 694ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 17s 162ms
➤ YN0000: · Done with warnings in 21s 863ms

**Comment by AhmeeedMostafa** [comment]
@z88kat nothing @filerobot/* packages is used in the plugin, please add codesandbox contains ur implementation or additional info to help.
