### ISSUE TITLE
Default cropping ratio only sets image dimension at first rendering

### ISSUE THREAD

**Issue by D0m1N1k999** [scaleflex/filerobot-image-editor#493]
When cropping an image with a configured default ratio (e.g. 1 / 1) at first the cropped image dimensions are set correctly (e.g. 100px / 100px). But after 1. uploading the same image again or 2. reinitializing the container, the image dimensions of the whole picture are displayed (e.g. 150px / 100px) and not only of the cropped part. The correct cropped dimensions only get set when dragging or changing the size of the cropping area.

https://codepen.io/D0m1N1k999/pen/qBzeVoz

1. Click on "Test" button and look at the dimensions of the image
2. Click on "Test" button again and look again

**Comment by AhmeeedMostafa** [comment]
Hey @D0m1N1k999 It has been fixed in v4.9.0 please check it and reopen the issue if still there is any comment.
