### ISSUE TITLE
This package sends data to a hard coded external website without asking permission 

### ISSUE THREAD

**Issue by JohnSmall** [scaleflex/filerobot-image-editor#496]
**Describe the bug (required)**

Read the code in src/utils/translator.js, you'll find this 
`xhr.open(
      'POST',
      `https://neo.wordplex.io/api/import/request-translations?grid_uuid=${TRANSLATIONS_GRID_UUID}`,
    );
    xhr.send(JSON.stringify(payload));`

Why is this package sending data to a hardcoded external website without asking permission to do so?

It also does a GET request from another external website, which fails. That's how I discovered this, I saw the failure in the console log and dug into it. 

It means that we can't use the package because it is definitely going to fail security checks.

**Comment by MrVibe** [comment]
Exactly, this is sending out unwanted calls 
https://prnt.sc/zy8KfArLA0ke
https://prnt.sc/65Ps3-OWLcQ8

**Comment by AhmeeedMostafa** [comment]
@JohnSmall @MrVibe 
Seems like you didn't read the documentation clearly, we are not hiding anything , this is the translation service we are using on the servers to keep the translation always updated, and easily you could disable that (all of that is mentioned in the documentation), [`useBackendTranslations`](https://github.com/scaleflex/filerobot-image-editor?tab=readme-ov-file#usebackendtranslations)

**Comment by MrVibe** [comment]
ok, thanks for clarification. Unfortunately, this issue led us to not use this amazing code in our project. 

One suggestion : If possible, my recommendation would be to remove this feature or provide a way to disable these translations as we would like to provide our own in the projects.

**Comment by AhmeeedMostafa** [comment]
@MrVibe I have already mentioned the property used in disabling this feature in my last comment.

Also, you could provide your custom translations through other related properties please check the documentation.
