### ISSUE TITLE
 In vue project! error: AssemblyPoint:'"Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters "

### ISSUE THREAD

**Issue by justseeseesee** [scaleflex/filerobot-image-editor#497]
**Describe the bug (required)**

**Codesandbox demo (required)**
 I Use this lib in vue project

"Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters "

**To Reproduce (required)**

**Expected behavior**

**Videos/Screenshots**
![image](https://github.com/user-attachments/assets/14cf3755-22ae-4e4b-96cb-a940c9a22262)

**Desktop (please complete the following information):**
 - OS: [e.g. windows11]
 - Browser [e.g. chrome, edge]
 - Version [e.g. 129]

**Additional context**

**Comment by AhmeeedMostafa** [comment]
Hey @justseeseesee this is just a warning has no effect on the application please disregard it for now, and this will be removed in the major release.
