### ISSUE TITLE
How can i crop a photo everytime even if user doesn't make any changes to crop boundings?

### ISSUE THREAD

**Issue by rsainiWin** [scaleflex/filerobot-image-editor#498]
Currently
If a user Clicks on save button after adding annotation the photo is saved in full size.
However I want to save the cropped section of the image , 
I'm opening the crop as default but sometime the user does not move the crop bounding and the full image gets saved

**Comment by AhmeeedMostafa** [comment]
Hey @rsainiWin please share your way of usage as it is expected to work as you are asking.

**Comment by DanielZhangQingLong** [comment]
Hi, AhmeeedMostafa, In `onModify` method, can you add `editedImageObject` like `onSave`? Actually I want upload current photo.
