### ISSUE TITLE
Draw on image?

### ISSUE THREAD

**Issue by nikolayg** [scaleflex/filerobot-image-editor#5]
Hey guys,

I just came across this project - it's looking great!

However, I couldn't see the capability to draw lines and polygons on top of the image? Is this on the timeline?

**Comment by dzmitry-stramavus** [comment]
hey @nikolayg ! thx! 

yes, it's on our road map.

**Comment by nikolayg** [comment]
Thanks @dzmitry-stramavus - that's great!

I'll keep an eye on the new releases :)
