### ISSUE TITLE
Can you make it responsive?

### ISSUE THREAD

**Issue by secmin** [scaleflex/filerobot-image-editor#50]
The demo page was not responsive.
On a smartphone, the slide tab at the top is hard to see and editing is complicated.
There is no problem if the size is large like a PC screen.
It's a wonderful project, so please do your best. I'm rooting for you.

**Comment by dzmitry-stramavus** [comment]
hey @secmin ,

sure, we will work on it soon!

**Comment by dzmitry-stramavus** [comment]
@secmin , improved in **3.7.6**

![IMAGE 2020-05-17 7:00:45 PM](https://user-images.githubusercontent.com/10708539/82154798-b6de4300-9870-11ea-989f-f67327ed8e72.jpg)
![IMAGE 2020-05-17 7:00:51 PM](https://user-images.githubusercontent.com/10708539/82154799-ba71ca00-9870-11ea-95a1-ddf8090ef376.jpg)
![IMAGE 2020-05-17 7:00:59 PM](https://user-images.githubusercontent.com/10708539/82154806-bf367e00-9870-11ea-93ab-00465de206d6.jpg)
![IMAGE 2020-05-17 7:01:04 PM](https://user-images.githubusercontent.com/10708539/82154807-c2316e80-9870-11ea-8cf6-83d814977ce0.jpg)
