### ISSUE TITLE
Image loading is blurred for no reason

### ISSUE THREAD

**Issue by piyushhsainii** [scaleflex/filerobot-image-editor#503]
Image loading is blurred for no reason

![image](https://github.com/user-attachments/assets/0d2c7f57-6c60-4e79-b7e6-fa80d09b940a)

**Smartphone (please complete the following information):**
]
 - Browser Chrome

**Additional context**

**Comment by AhmeeedMostafa** [comment]
@piyushhsainii I don't see any useful info you provided unless of the screenshot, I couldn't produce on my side.
so please provide your producing steps also a codesandbox if possible to investigate the issue.

**Comment by piyushhsainii** [comment]
> @piyushhsainii I don't see any useful info you provided unless of the screenshot, I couldn't produce on my side. so please provide your producing steps also a codesandbox if possible to investigate the issue.

Using the CDN fixed the issue for me
