### ISSUE TITLE
Allow saving without dialog with default options

### ISSUE THREAD

**Issue by muuvmuuv** [scaleflex/filerobot-image-editor#513]
**Is your feature request related to a problem? Please describe.**

I dont want my users to choose any save options but define my defaults.

**Describe the solution you'd like**

A new option "saveOptionsAfterSave".

**Describe alternatives you've considered**

-

**Additional context**

We are on the latest release.

**Comment by AhmeeedMostafa** [comment]
Hey @muuvmuuv have u checked the notes of this param ['onBeforeSave'](https://github.com/scaleflex/filerobot-image-editor?tab=readme-ov-file#onbeforesave) ?

**Comment by muuvmuuv** [comment]
Nope, didn't read the hole documentation and didn't expect it to be onBeforeSave because I would not have needed that event. Thanks!
