### ISSUE TITLE
Localization bug

### ISSUE THREAD

**Issue by Ulgerd** [scaleflex/filerobot-image-editor#52]
Hello! 

I have a problem with custom localization. It always English, even if you provide a translation. 
It's in `projects/react/ImageEditorWrapper.js` 
In line 18:
`config.language = translations[config.language] ? config.language : 'en';` we check only local `translations`, not `config.translations` provided by user. 

I'm sure something like `config.language = (config.translations[config.language] || translations[config.language]) ? config.language : 'en';` would solve the problem.

I hope this would help!
Anyway, thanks! You're doing a great job!

**Comment by dzmitry-stramavus** [comment]
@Ulgerd , hey thanks a lot for debugging

done in **3.7.7**
