### ISSUE TITLE
It is no longer possible to use a Blob as a "src" of image?

### ISSUE THREAD

**Issue by novikov1337danil** [scaleflex/filerobot-image-editor#53]
Hello! firstly, thanks for the wonderful library.
In the latest update, I can no longer use blobs as the image source for the image editor. In the previous version, it was available and it was convenient, because this format is used to send files to the server.
Is it possible to count on the return of this feature, or now it will be necessary to convert dataURL to blob?

If i try to use blob, i get such an error:
`src.split is not a function`

![Снимок экрана от 2020-06-04 21-14-52](https://user-images.githubusercontent.com/44060868/83795708-87209f00-a6a8-11ea-8f46-fc661849ccf0.png)

**Comment by dzmitry-stramavus** [comment]
hey @novikov1337danil ,

thx for reporting the bug. I'll try to check it asap

**Comment by dzmitry-stramavus** [comment]
fixed in **3.9.2**
