### ISSUE TITLE
Question: Instead of download, how can I upload it to a third party hosting service (S3)

### ISSUE THREAD

**Issue by DeanKamali** [scaleflex/filerobot-image-editor#6]
Hi 
I'm wondering which function/method is responsible for downloading the image? 
I'm trying to change the behavior so I could upload the transformed image and later upload it to S3 for example.

Thanks

**Comment by dzmitry-stramavus** [comment]
@DeanKamali , you can use onBeforeComplete method.

```onBeforeComplete={(props) => { console.log(props); return true; }}```

where `props: { status, canvas }`

![image](https://user-images.githubusercontent.com/10708539/65319390-36175c00-dba8-11e9-93b9-d60364428b35.png)

to block downloading image you need to return false in the onBeforeComplete method

check the example in code sandbox below

https://codesandbox.io/s/example-onbeforecomplete-handler-vcovn

**Comment by DeanKamali** [comment]
Thanks @dzmitry-stramavus for your prompt response

**Comment by justinh00k** [comment]
How do you prevent downloading in vanilla JS? Returning false in uploadHandler doesn't seem to do the trick.

**Comment by uniyalalok** [comment]
> How do you prevent downloading in vanilla JS? Returning false in uploadHandler doesn't seem to do the trick.

Hi, did you get any way to prevent downloading in vanilla JS?
