### ISSUE TITLE
FullSize don't work

### ISSUE THREAD

**Issue by dmitrykovalevsky89** [scaleflex/filerobot-image-editor#62]
Hi!
FullSize don't work
http://joxi.ru/xAe00qnsR8vdl2
blank screen
http://joxi.ru/1A5ppP3FD6xLO2

But in your example everything works
http://joxi.ru/DmBDDOQSJkp3oA

I am using a fresh version library for js

**Comment by AhmeeedMostafa** [comment]
Hey @dmitrykovalevsky89 
Could you please make sure that you don't have duplicated or another element with the id "filerobot-image-editor" on the same page and see if it works?

**Comment by ahmeeedkhallaf** [comment]
Hey @dmitrykovalevsky89 ,
Could you please make sure that you don't have duplicated or another element with the id "filerobot-image-editor" on the same page and see if it works?

**Comment by dmitrykovalevsky89** [comment]
Hey @ahmeeedkhallaf 
http://joxi.ru/p2777QniKdJD82
This block is one and it is empty

**Comment by dmitrykovalevsky89** [comment]
Hey @ahmeeedkhallaf 
Yes you are right
When you open, therefore, two blocks were created
Thanks
