### ISSUE TITLE
Write text and draw on image

### ISSUE THREAD

**Issue by Zayn484** [scaleflex/filerobot-image-editor#63]
Just found this editor and its great. There are some missing features like:

- Writing text

- Drawing on image

 It would be great if these features are done with drag n drop, so do you have these features in your roadmap. If yes then how long will it take to implement these?

**Comment by dzmitry-stramavus** [comment]
hey @Zayn484 ,

Yes, it's on roadmap. We don't have exact ETA for it yet

**Comment by AhmeeedMostafa** [comment]
@Zayn484 Please note that writing text & adding different shapes are now available to use starting from 3.11.x versions
for drawing on an image still on our roadmap.
Thanks

**Comment by Textras** [comment]
With the draw functionality, stickers/emoji like Img.ly or Pqina might be great. This is a super project.

**Comment by AhmeeedMostafa** [comment]
@Textras it would be better opening a new issue with your suggestions for improving the plugin and let's see if it's possible to consider.
Please note that the draw functionality is coming in the new major version
