### ISSUE TITLE
Translation words start with capital letters

### ISSUE THREAD

**Issue by novikov1337danil** [scaleflex/filerobot-image-editor#65]
Maybe it’s worth giving the user the opportunity to determine the case of translation words on their own?

**Comment by dzmitry-stramavus** [comment]
@novikov1337danil , hey 

Yes, we can improve this aspect. I'll add this to our roadmap. Thx!

**Comment by AhmeeedMostafa** [comment]
Hey @novikov1337danil ,
We have added noCapitalStrs prop in the config you could use this in disabling such behavior in the new release v3.12.0!
