### ISSUE TITLE
CSP Issues

### ISSUE THREAD

**Issue by TheLeePriest** [scaleflex/filerobot-image-editor#69]
Hi,

I have just setup the editor on a react project i'm working on. The setup was nice and smooth but I am getting errors from the CSP that is setup on the project due to the use of 'unsafe-eval'. 

Is there a fix or a workaround for this?

**Comment by ahmeeedkhallaf** [comment]
Currently, you should add unsafe-eval to the CSP whether for the editor only through using some nonce or generally.

**Comment by TheLeePriest** [comment]
The CSP is set within the backend PHP code and i'm not able to modify it. 

The error that is fired points to this block of code:

` {
      // Hack: trick Babel/TypeScript into allowing this before super.
      if (false) { super(); }
      let thisFn = (() => { return this; }).toString();
      let thisName = thisFn.match(/return (?:_assertThisInitialized\()*(\w+)\)*;?/)[1];

      eval(`${thisName} = this;`);
    }
`
