### ISSUE TITLE
Integration for editing images and storing edited images on server instead of downloading.

### ISSUE THREAD

**Issue by DiemenDesign** [scaleflex/filerobot-image-editor#7]
Hi, I'm looking at integrating your project into https://github.com/DiemenDesign/AuroraCMS/ to allow clients to quickly edit images. I'm currently allowing uploads in Summernote with elFinder integrated which has simple cropping and resizing and auto thumbnail creation, but I'd like to give my clients more options using filerobot.
I may have missed it, but I couldn't find where I can open an image from the server, and have it saved back to the server, not downloaded, or sent to another storage service, then have the thumbnail/image updated on the page to reflect the editing changes.
I'm also hoping it's going to integrate easily with Bootstrap 4, which is what I use for the Administration area.

**Comment by dzmitry-stramavus** [comment]
hey @DiemenDesign , the example configuration [here](https://github.com/scaleflex/filerobot-image-editor/tree/master/examples/js-with-filerobot)

**Comment by DiemenDesign** [comment]
Thank you. Not sure why I didn't get notified that you commented and closed the issue.
