### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by Kaoschuks** [scaleflex/filerobot-image-editor#72]
Hello first off I love this plugin.

Just a quick question though is there anyway to make this editor fit a parent div height and width and also not display as a modal for both mobile and desktop view???

Thanks a lot for your response

**Comment by ahmeeedkhallaf** [comment]
@Kaoschuks Yes, such a feature has been added on the new release v3.11.0 through openInModal prop you could review it in the readme
