### ISSUE TITLE
Watermark Issue

### ISSUE THREAD

**Issue by DanielGregatto** [scaleflex/filerobot-image-editor#74]
Hello, first of all this plugin is awesome, congratulations.
When I update the version 3.9.5 to 3.11.0 the feature watermark stoped to work, it keep loading and don`t go ahead.
And it didn`t shows any error message.

![Capturar](https://user-images.githubusercontent.com/5113536/93234950-534b2000-f753-11ea-8048-5c611c8a8268.JPG)

**Comment by AhmeeedMostafa** [comment]
Hello @DanielGregatto ,
Have you checked the network tab and see if the watermark's image is loaded, still loading or failed?
And if it is loaded and loading icon still is shown, could you could provide more details of how do u produce this problem?

**Comment by DanielGregatto** [comment]
I returned my system to version 3.9.5, but I created a test view with only the basic code described in the guide.
I published the test view so you can see it.
Link: https://www.nutrigram.com.br/testeeditorimage

![Capturar](https://user-images.githubusercontent.com/5113536/93239252-e76bb600-f758-11ea-826d-0bb75db3a803.JPG)

**Comment by AhmeeedMostafa** [comment]
@DanielGregatto Thank you for giving us more info.,
The issue is solved now in the new version v3.11.1
feel free to check it & let us know if there is any other problem!

**Comment by DanielGregatto** [comment]
Hello @AhmeeedMostafa 
Thank you!!
