### ISSUE TITLE
Watermark Issue - Using predefined url in configs

### ISSUE THREAD

**Issue by DanielGregatto** [scaleflex/filerobot-image-editor#75]
Hello,
When I am trying to build a instance of FilerobotImageEditor using a predefined watermark url it doesn`t open and show me some error messages.
To reproduce the error you can access the link bellow and click on the icon Watermark.
Link: https://www.nutrigram.com.br/testeeditorimage

Code implemented:
![Capturar](https://user-images.githubusercontent.com/5113536/93494349-51b06200-f8e3-11ea-8abb-41a9d044920e.JPG)

Screen afrer build
![Capturar 2](https://user-images.githubusercontent.com/5113536/93494452-6bea4000-f8e3-11ea-8b9c-3e23afbb77b2.JPG)

Error after click on Watermark
![Capturar](https://user-images.githubusercontent.com/5113536/93494592-93d9a380-f8e3-11ea-9d8d-30371b4648c8.JPG)

**Comment by AhmeeedMostafa** [comment]
Hello @DanielGregatto,
solved in the new release v3.11.2
Thanks for your report.
