### ISSUE TITLE
Drag and Drop Watermark Issue

### ISSUE THREAD

**Issue by DanielGregatto** [scaleflex/filerobot-image-editor#76]
Hello, 
I am trying to drag and drop a watermark but It throw a lot of errors in the console and don`t work.

Page where you can try like me:
https://www.nutrigram.com.br/testeeditorimage

Code implemented:
![Capturar](https://user-images.githubusercontent.com/5113536/93785933-0e1c6780-fc05-11ea-91bd-cac65e36e66c.JPG)

Console errors:
![Capturar](https://user-images.githubusercontent.com/5113536/93786011-2a200900-fc05-11ea-84af-f80d5ccb9c59.JPG)

Ps: Same error to drag and drop a text.

**Comment by AhmeeedMostafa** [comment]
Hello @DanielGregatto ,
Thanks for your report it's solved in the released version (v3.11.3)
