### ISSUE TITLE
UNSAFE_componentWillMount

### ISSUE THREAD

**Issue by adsee42** [scaleflex/filerobot-image-editor#77]
Hi, I'm using `react: "^16.13.1"` and tried `filerobot-image-editor: "^3.11.3"`

Anf react compalined: `Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code`.

**Comment by AhmeeedMostafa** [comment]
Hello @adsee42 ,
We have replaced all the unsafe methods in the new release v3.12.0 feel free to try it!

Thanks!
