### ISSUE TITLE
Watermark quality deteriorates

### ISSUE THREAD

**Issue by DanielGregatto** [scaleflex/filerobot-image-editor#79]
Hello,
There are some way to don't loss quality when download the image with Watermark? 
When I downloaded the image after insert watermark the image result has loss quality only in the watermark.
You can try it here: https://www.nutrigram.com.br/testeeditorimage
Watermark that I'm using: https://www.nutrigram.com.br/arquivos/watermark/watermark.png

**Comment by AhmeeedMostafa** [comment]
Hello @DanielGregatto ,
Sorry but I couldn't notice any quality loss in the image if you could differentiate with some examples would be better.

**Comment by DanielGregatto** [comment]
Hello @ahmeeedkhallaf 
I think I noticed what is happening.
I have a watermark with width 198x47px while I am editing through the editor It still has 198x47px but the main image is resized, when I apply and download the image, my watermark expands along with the main image.

Look my main image has 1080x1080px:
https://www.nutrigram.com.br/Arquivos/Post/990692f7-2102-452c-98c9-c8352b89d7c6.jpg

Watermark has 198x47px:
https://www.nutrigram.com.br/Arquivos/Pessoa/37ba6bc7-3080-4322-8ba1-13033102f423.png

While I am editing my main image is resized to 618x618px but my watermark still has 200px:
![Capturar](https://user-images.githubusercontent.com/5113536/94179820-740e2680-fe73-11ea-9ce7-88053e359d93.JPG)

So the result is that my watermark is resized togheter and ends with 345x84px:
https://www.nutrigram.com.br/Arquivos/PostPersonalizado/501b009a-40b6-440c-9719-cd9f4595f45f.jpg

There are any way to preserve the dimensions?

**Comment by DanielGregatto** [comment]
I believe that when I insert the watermark It has to be resized the same percentual that my main image was resized, so when it expand the result will be the correct size.

**Comment by DanielGregatto** [comment]
Hello @AhmeeedMostafa, could you see?

**Comment by AhmeeedMostafa** [comment]
Hey @DanielGregatto  sorry for late response,
There is a new improvement implemented in the new version v3.12.0, for the way objects (images, watermark...etc) are being implemented which became more relative to the original image size so it would help to avoid such image destroying.
So please try the new version & I hope it would fix this :), let us know if still there such a problem by re-opening the issue.

Thanks!

**Comment by DanielGregatto** [comment]
Hello @AhmeeedMostafa 
It works, thank you so much
