### ISSUE TITLE
How can i fix the size of cropper and prevent user from changing the size of cropper box ?

### ISSUE THREAD

**Issue by lavish0000** [scaleflex/filerobot-image-editor#81]

**Comment by lavish0000** [comment]
i want to fix the size of cropper and provide a fix size of cropper according to the aspect ratio of image, user should not be able to decrease the size of cropper below the size i have provided as default

**Comment by dzmitry-stramavus** [comment]
hey @lavish0000 , I'll add it to our roadmap.

**Comment by lavish0000** [comment]
ok thanks so much, and one more thing that i am facing some issue can you please check them.

**Comment by lavish0000** [comment]
Issue 1: Responsiveness in text filter.
When i click on font family , its dropdown is opened
![Screenshot from 2020-10-05 13-30-17](https://user-images.githubusercontent.com/46993225/95054499-94f63780-070f-11eb-85b2-7834fde0cb42.png)
 outside the screen

**Comment by lavish0000** [comment]
Issue 2: When i tap on the dots around the text area , i am not able to expand the text area.
![Screenshot from 2020-10-05 13-31-04](https://user-images.githubusercontent.com/46993225/95054613-c242e580-070f-11eb-81a8-d3fef809566e.png)

**Comment by lavish0000** [comment]
@dzmitry-stramavus can you please help me with these issues ?

**Comment by AhmeeedMostafa** [comment]
Hello @lavish0000 Thank you for your reporting,
Both custom crop area locking/fixing by adding minimum values for width & height  and dropdown of font family input are added & fixed in the new release v3.12.0
but for issue 2 (which is expanding text area) you couldn't expand the text area whether on phone or desktop you could only change the text size, also for you to notice touch isn't supported 100% yet.

hope everything is clear for you now :)

**Comment by lavish0000** [comment]
ok, thanks for fixing the bugs and adding the feature.

**Comment by lavish0000** [comment]
@AhmeeedMostafa , i updated the package but the font family dropdown is still opening outside at the right side of the screen.

**Comment by AhmeeedMostafa** [comment]
@lavish0000 what's the screen width you are using?
And could you provide a screenshot for it looks now if it looks different than first screenshot

**Comment by lavish0000** [comment]
![Screenshot from 2020-10-07 19-05-10](https://user-images.githubusercontent.com/46993225/95337991-14326980-08d0-11eb-975d-42ed3ffb7c1a.png)

i am using it in my pc, with iphone x config, with: 375, height: 812

**Comment by AhmeeedMostafa** [comment]
@lavish0000 Okay, I'd check it again and see what is the problem.

**Comment by lavish0000** [comment]
ok, thanks :+1:

**Comment by AhmeeedMostafa** [comment]
@lavish0000 I have checked and seems fine on that screen too, could you please make sure that you have the new version v3.12.0 ?
you could also try the demo here with the same screen you are facing that problem with and you would find it work fine :)
https://scaleflex.github.io/filerobot-image-editor/

let me know!

**Comment by lavish0000** [comment]
![Screenshot from 2020-10-12 22-27-56](https://user-images.githubusercontent.com/46993225/95772711-d1f79680-0cda-11eb-9788-85fe0c41884b.png)
@AhmeeedMostafa , sorry for the late reply,  now its working fine, as in the above link you provided, i just want to confirm that , when i click on font family the whole menu bar is expended with it , is it suppose to be like this , or is this a bug. but as for now it is fine. this will work for me, thanks for the help :+1:

**Comment by AhmeeedMostafa** [comment]
@lavish0000 yes this is the behavior it expands while opening and shrinks while closing on phones
