### ISSUE TITLE
Local Pathes in Code

### ISSUE THREAD

**Issue by fx1234** [scaleflex/filerobot-image-editor#83]
hi

when i look at the code, i see thousands of paths that look like local paths ("D:\\Work\\Projects\\filerobot-image-editor\\)"

what are those paths?

**Comment by AhmeeedMostafa** [comment]
Hey @fx1234 
Could you please provide more details? 
Maybe a screenshot for what you see, and inside which file?

**Comment by fx1234** [comment]
this:

![git](https://user-images.githubusercontent.com/37163623/95331070-be4acb00-08a9-11eb-9edf-a7f70d9c94d4.jpg)

**Comment by AhmeeedMostafa** [comment]
Hello @fx1234 
Thanks for your report
those paths were related to react hot loader & they are removed in the release v3.12.1
