### ISSUE TITLE
self-hosting filerobot-image-editor

### ISSUE THREAD

**Issue by fx1234** [scaleflex/filerobot-image-editor#84]
hi

we want to try out filerobot-image-editor for our companie

for legal reasons, we are not allowed to use external CDNs. is there a way to self-host everything (images, javascript, css)?

**Comment by AhmeeedMostafa** [comment]
You could use either NPM package or download the JS lib. from our CDN link/Github repo. on your host

**Comment by fx1234** [comment]
so is it enough to download this file:

https://cdn.scaleflex.it/plugins/filerobot-image-editor/3.12.17/filerobot-image-editor.min.js

or do you need more dependencies  (like images, fonts...)?

**Comment by carlos22** [comment]
Yes. But it loads the font from: `https://cdn.scaleflex.it/plugins/filerobot-image-editor/assets/fonts/filerobot-image-editor-font/v5/filerobot-image-editor-font.ttf?ua0hzun3=`. If you want to avoid that you need to change the code that loads this file.
