### ISSUE TITLE
Change FIlter image

### ISSUE THREAD

**Issue by Kaoschuks** [scaleflex/filerobot-image-editor#85]
Hello I was wondering if it was possible to change the filter images to the photo currently been edited rather than the default images been used??

**Comment by AhmeeedMostafa** [comment]
Hello @Kaoschuks ,
Currently, it's not possible but we would consider this suggestion in the future

**Comment by Kaoschuks** [comment]
Hello I would love to know the status of this???

**Comment by AhmeeedMostafa** [comment]
@Kaoschuks no ETA is determined yet

**Comment by AhmeeedMostafa** [comment]
@Kaoschuks Such a feature is considered in the new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) , you could check it and let us know your feedback!
