### ISSUE TITLE
colorScheme: "light" - shapes are not visible

### ISSUE THREAD

**Issue by siccolo** [scaleflex/filerobot-image-editor#86]
Hello, thank you for providing such an awesome editing component.

While testing image editor (version 3.12.1/3.12.0), noticed an issue with displaying shapes - when color scheme is set to "light" , then, shapes outlines are not visible, because they're white-on-white:

![image](https://user-images.githubusercontent.com/929200/95601224-2bcd3780-0a21-11eb-871a-d4a36ea5933e.png)

Is there a way to set/control "outline" color via config settings? 

Thank you!

**Comment by AhmeeedMostafa** [comment]
@siccolo Thanks for your report we would consider this in next releases

**Comment by AhmeeedMostafa** [comment]
Hey @siccolo ,
this has been fixed in the new release v3.12.2, try it and let us know if there any problem
Thanks!
