### ISSUE TITLE
question about config/settings

### ISSUE THREAD

**Issue by siccolo** [scaleflex/filerobot-image-editor#87]
Hello, 
is there a way to set/provide list of fonts to be available in the image editor?
(* passing list in config, such as 
theme: {
    fonts: [{ label: "Segoe UI", value: "Segoe UI" }]
  }
doesn't  change font list shown under "Text" tool).

Please let me know,
Thank you!

**Comment by AhmeeedMostafa** [comment]
Yes it would be configured soon

**Comment by AhmeeedMostafa** [comment]
@siccolo Hello,
this has been added in the new release v3.12.2, try it and let us know if there any problem
Thanks!
