### ISSUE TITLE
React Native / Expo crash | filerobot-font.css

### ISSUE THREAD

**Issue by dima-tab** [scaleflex/filerobot-image-editor#89]
When importing the filerobot, it crashes with this error
Unable to resolve module `./assets/fonts/filerobot-font.css` from `node_modules\filerobot-image-editor\dist\ImageEditorWrapper.js`: 
I am using React Native + Expo.
Does this package include work with Expo?

**Comment by AhmeeedMostafa** [comment]
Hello @dima-tab ,
since this module is made for web applications it's not supported through React native as it uses different components (web components) than that are being used by ReactNative.

Hope this answered your question & sorry for v. late reply.

**Comment by AhmeeedMostafa** [comment]
You could re-open the issue if you still have more inquiries

**Comment by magicspon** [comment]
I'm seeing the same issue when using with nextjs

It looks like the assets are missing from the package:
![image](https://user-images.githubusercontent.com/3268717/110253784-10d90200-7f84-11eb-88ba-4cb5baf75222.png)

**Comment by AhmeeedMostafa** [comment]
@magicspon 
![image](https://user-images.githubusercontent.com/22754338/110284168-08b3ad80-7fea-11eb-9c95-729875ba981c.png)

this is a screenshot of the files after installing the module from NPM, so seems everything is fine... could you give us more info about the problem and make sure there were no issues while installing the module?

**Comment by magicspon** [comment]
I've installed using yarn.

`yarn filerobot-image-editor` 

Just removed it, tried again, still no assets directory.

Installed using `npm i filerobot-image-editor`, now I can see the assets directory.

**Comment by AhmeeedMostafa** [comment]
@magicspon it should be 
`yarn add filerobot-image-editor`

If it doesn't work fine maybe u have some problem with yarn.

**Comment by magicspon** [comment]
Correct, forget to write `add` in my reply.

**Comment by magicspon** [comment]
are you able to successfully install this package with yarn?

**Comment by AhmeeedMostafa** [comment]
Yes I have used yarn for installing it and the result as shown in the screenshot above

**Comment by andysteinwachs** [comment]
I was having the same issue but found a way to get it to work. 

## Issue
`yarn add filerobot-image-editor`

resulted in a broken installation with a missing `assets` directory.

Error message:
```
./node_modules/filerobot-image-editor/dist/ImageEditorWrapper.js
Module not found: Can't resolve './assets/fonts/filerobot-font.css' in '.../<PROJECT-DIR>/node_modules/filerobot-image-editor/dist'
```

Switching to npm would need us to make some changes in our project, and we do prefer yarn.

## Cause
However, in our case, the issue was the presence of the `.yarnclean` file, which is created when using `yarn autoclean`. 

## Solution
Try deleting the `.yarnclean` file and the `node_modules` directory, and **avoid** using `yarn autoclean`.

```
rm -rf node_modules
rm .yarnclean
yarn
```

## What is autoclean?
From yarn's docs:

> The autoclean command frees up space by removing unnecessary files and folders from dependencies. It reduces the number of files in your project’s node_modules folder which is useful in an environment where packages are checked into version control directly.

> Note: This command is considered for advanced use cases only. Unless you are experiencing issues with the amount of files that are installed as part of node_modules it is not recommended to use this command. It will permanently delete files in node_modules which could cause packages to stop working.

and

> When the .yarnclean file exists in a package, autoclean functionality will be enabled. The clean will be performed:
>
> After an install
> After an add
> If yarn autoclean --force is run
