### ISSUE TITLE
Максимальное значение Exposure выдает ошибку

### ISSUE THREAD

**Issue by dmitrykovalevsky89** [scaleflex/filerobot-image-editor#9]
Приветствую!
Обнаружил при работе с редактором, что при максимальном значении Экспозиции в Редактировании выбивает ошибку
TypeError: Cannot read property '1' of undefined
http://joxi.ru/4Akee47tobdWlm

Данная ошибка и в примерах
https://codesandbox.io/s/k3q9vrk707

**Comment by dzmitry-stramavus** [comment]
hey, @dmitrykovalevsky89 

fixed in **v3.4.0**

**Comment by dmitrykovalevsky89** [comment]
Thanks!
