### ISSUE TITLE
[BUG] Style error (React)

### ISSUE THREAD

**Issue by oliuradu** [scaleflex/filerobot-image-editor#90]
How to reproduce:
-Install filerobot with React

![image](https://user-images.githubusercontent.com/42614946/98311321-c8123c00-1fd7-11eb-8257-66c59134273d.png)

After rotating
![image](https://user-images.githubusercontent.com/42614946/98311410-04459c80-1fd8-11eb-921c-cdf2e7518752.png)

After crop
![image](https://user-images.githubusercontent.com/42614946/98311439-14f61280-1fd8-11eb-8fc8-02e9370d7ee4.png)
![image](https://user-images.githubusercontent.com/42614946/98311456-1c1d2080-1fd8-11eb-97b8-119f9ee0fa99.png)

**Comment by AhmeeedMostafa** [comment]
Hey @oliuradu , I would check it and let you know

**Comment by AhmeeedMostafa** [comment]
Hey again @oliuradu , thank you for your reporting

This issue has been solved in the new release v3.12.3 check it and let us know thanks!

**Comment by fairhat** [comment]
this issue still persists in 3.12.9

**Comment by fairhat** [comment]
adding to that: 
looks like after cropping the crop container is not disabled (and replaced with the current preview)

Cropping multiple times leads to multiple images (crop containers) being added under the photo
