### ISSUE TITLE
Preload Text with position

### ISSUE THREAD

**Issue by IronLady** [scaleflex/filerobot-image-editor#91]
Hi, 

This looks promising. 
I've been playing with the demo, but can't find a way to preload a text. 
I have a use case where I create the template and user can just edit it.
Is this possible?

Thanks

**Comment by AhmeeedMostafa** [comment]
Hello @IronLady but we haven't this feature supported yet,
we are considering this in the future to be able to save the canvas and re-load it to be re-used

**Comment by AhmeeedMostafa** [comment]
@IronLady you could check `loadableDesignState` it's the proper property for this but it's experimental currently and might have some improper behavior, it's in the new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) released in BETA now
let us know your feedback in a new issue to improve it !
