### ISSUE TITLE
Text Position Changes On Undo-Redo Operations

### ISSUE THREAD

**Issue by mushirkhan** [scaleflex/filerobot-image-editor#92]
After applying "sometext" on the picture using text tool, doing undo - redo operations and after that if we download the image the text changes the position on the downloaded image.  

![text_issue2](https://user-images.githubusercontent.com/74170019/98648748-b1177500-235c-11eb-90f1-c2af503a4aae.jpg)

![text_issue1](https://user-images.githubusercontent.com/74170019/98648754-b2e13880-235c-11eb-834c-3d89ba5afe14.jpg)

**Comment by AhmeeedMostafa** [comment]
Hey @mushirkhan , please note that this issue has been solved in the new release v3.12.3

check it and if still there is any issue like this u could re-open this issue again, thank you!
