### ISSUE TITLE
On cancelling crop tool the canvas shift the position below the footer

### ISSUE THREAD

**Issue by mushirkhan** [scaleflex/filerobot-image-editor#94]
When using filerobot-image-editor as an npm component:

Opening the crop tool and clicking the cancel button shift the canvas position and does not remove the cropper from it

![cropIssue1](https://user-images.githubusercontent.com/74170019/99387447-04a83680-28fa-11eb-948e-e16a7effac7b.jpg)

**Comment by karpovich-philip** [comment]
Hello @mushirkhan ! What version of npm package are you using? The last release shouldn't have such problem. Check please and notify if you still have some bugs

**Comment by mushirkhan** [comment]
Hello @karpovich-philip, I am using the "filerobot-image-editor": "^3.12.3" version.
I guess the latest one

**Comment by mushirkhan** [comment]
Hi, I have crossed checked it again, I am using the latest version 3.12.3

**Comment by AhmeeedMostafa** [comment]
Hey @mushirkhan ,
The issue is not reproducible on our side also u could check the [demo](https://scaleflex.github.io/filerobot-image-editor/)
and sandbox using NPM package [here](https://codesandbox.io/s/hopeful-knuth-zytic)

if you could provide us with more useful info for re-producing this issue would be great

**Comment by mushirkhan** [comment]
Hello,

I have created a new react project and install the npm package for filerobot-image-editor 3.12.3
Once I click the crop tool and click on cancel tool the above issue can be reproduced.

I have ask a colleague to do the same he does not seems to reproduce the issue on his machine after following the above steps,
then I shared my project with him with node modules with the same version 3.12.3 and he also get the issue on his machine,
now if he also creates a new project and install the npm package or in any existing project also if he install this version 3.12.3 this issue can be reproduce.

**Comment by AhmeeedMostafa** [comment]
Hello again @mushirkhan ,
Please make sure that u don't have some library that overrides the styles of ours, also u could create some codesandbox with your code if it's possible and make it producible there to check it otherwise it is very hard for us to produce and fix!

**Comment by mushirkhan** [comment]
Hello @AhmeeedMostafa, Okay I can understand this, We can close this issue for now then. Ill open it again when I am being able to show you on sandbox or any other platform.
