### ISSUE TITLE
Missing the cancel/close button

### ISSUE THREAD

**Issue by Benbinbin** [scaleflex/filerobot-image-editor#96]
I use the 3.12.9 version, and the cancel button didn't show, and only show the download button on the header.
It makes more sense to add cancel button and complete/download button on the top-right corner of the modal.

![Missing close button](https://user-images.githubusercontent.com/40909550/103441964-bb832a80-4c8c-11eb-9188-2ad873e79f4e.png)

**Comment by AhmeeedMostafa** [comment]
Hello @Benbinbin ,
We have added the close button back on the top left corner of the modal for now in the new release v3.12.10 you could check it out.
