### ISSUE TITLE
Edit Image with Templated Control Layout (i.e., textboxes and images placed relative to preloaded background image)

### ISSUE THREAD

**Issue by webdevandeverythingelse** [scaleflex/filerobot-image-editor#97]
Is this possible with the configuration JS potentially? (I didn't see anything in the documentation.)

I'd like to have a background image preloaded and multiple controls prepopulated with text, making it easy for the user to see an example and then edit it.

**Comment by AhmeeedMostafa** [comment]
For now, it is not possible but we are considering this feature in our upcoming new features

**Comment by AhmeeedMostafa** [comment]
@webdevandeverythingelse such a feature is available as experimental feature in new [V4](https://github.com/scaleflex/filerobot-image-editor/tree/v4) which is in BETA now, u could check property `loadableDesignState` but you might face some improper behavior cause it still experimental so it would be nice to know your feedback about such a feature by opening other issue
