### ISSUE TITLE
Please include the non minified source code

### ISSUE THREAD

**Issue by nikto1** [scaleflex/filerobot-image-editor#99]
Please include the non minified source code.
Thanks

**Comment by AhmeeedMostafa** [comment]
It's already there inside the repository (master) branch contains the latest source code for latest version.

**Comment by nikto1** [comment]
I've only found the minified version otherwise i wouldn't have asked. 
Can you provide a link to the non minified version please? 
Thanks

**Comment by AhmeeedMostafa** [comment]
@nikto1 the whole github repository except (build) folder is the non-minified source code!

And the main source code of the library with no build configurations, examples...etc is found here:
https://www.github.com/scaleflex/filerobot-image-editor/tree/master/projects/react

**Comment by nikto1** [comment]
oh ok, thanks, didn't look into the react folder because i don't use react, sorry. 
Btw, i didn't find any "donate button" on your website.
Have fun
